<div class="form-group">
	<?=Form::label(t('name'), 'name', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::text('name', ['value' => $field['name'], 'class' => 'form-control'])?>
	</div>
</div>
<div class="form-group">
	<?=Form::label(t('slug'), 'slug', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::text('slug', ['value' => $field['slug'], 'class' => 'form-control'])?>
	</div>
</div>
<div class="form-group">
	<?=Form::label(t('type'), 'type', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::select('type', Traq\Models\CustomField::typesSelectOptions(), ['value' => $field['type'], 'id' => 'field_type', 'class' => 'form-control'])?>
	</div>
</div>

<div class="dynamic-fields">
	<div class="form-group cf-type-text cf-type-integer">
		<?=Form::label(t('min_length'), 'min_length', ['class' => 'control-label col-md-3'])?>
		<div class="col-md-9">
			<?=Form::text('min_length', ['class' => 'form-control', 'value' => $field['min_length']])?>
			<small class="help-text"><?=t('help.custom_fields.min_length')?></small>
		</div>
	</div>

	<div class="form-group cf-type-text cf-type-integer">
		<?=Form::label(t('max_length'), 'max_length', ['class' => 'control-label col-md-3'])?>
		<div class="col-md-9">
			<?=Form::text('max_length', ['class' => 'form-control', 'value' => $field['max_length']])?>
			<small class="help-text"><?=t('help.custom_fields.max_length')?></small>
		</div>
	</div>

	<div class="form-group cf-type-text cf-type-integer">
		<?=Form::label(t('regex'), 'regex', ['class' => 'control-label col-md-3'])?>
		<div class="col-md-9">
			<?=Form::text('regex', ['class' => 'form-control', 'value' => $field['regex']])?>
			<small class="help-text"><?=t('help.custom_fields.regex')?></small>
		</div>
	</div>

	<div class="form-group cf-type-text cf-type-integer">
		<?=Form::label(t('default_value'), 'default_value', ['class' => 'control-label col-md-3'])?>
		<div class="col-md-9">
			<?=Form::text('default_value', ['class' => 'form-control', 'value' => $field['default_value']])?>
		</div>
	</div>

	<div class="form-group cf-type-select">
		<div class="col-md-9 col-md-offset-3">
			<label>
				<input type="checkbox"> <?=t('multichoice')?>
			</label>
		</div>
	</div>

	<div class="form-group cf-type-select">
		<?=Form::label(t('values'), 'values', ['class' => 'control-label col-md-3'])?>
		<div class="col-md-9">
			<?=Form::textarea('values', ['class' => 'form-control', 'value' => isset($field['values']) ? $field['values'] : ''])?>
			<small class="help-text"><?=t('help.custom_fields.values')?></small>
		</div>
	</div>
</div>

<div class="form-group">
	<?=Form::label(t('ticket_types'), 'ticket_type_ids[]', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::select(
			'ticket_type_ids[]',
			array_merge(
				[['label' => t('all'), 'value' => 0]],
				Traq\Models\Type::selectOptions()
			),
			[
				'class' => 'form-control',
				'value' => $field['ticket_type_ids'],
				'multiple' => true
			]
		)?>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	// Show only text field properties
	show_properties_for($('#field_type').val());

	function show_properties_for(type) {
		// Text field
		if (type == 'text') {
			$('.cf-type-integer').hide();
			$('.cf-type-select').hide();
			$('.cf-type-text').show();
		}
		// Integer field
		else if (type == 'integer') {
			$('.cf-type-text').hide();
			$('.cf-type-select').hide();
			$('.cf-type-integer').show();
		}
		// Select field
		else if (type == 'select') {
			$('.cf-type-text').hide();
			$('.cf-type-integer').hide();
			$('.cf-type-select').show();
		}
	}

	$("#field_type").change(function(){
		var e = $(this);
		show_properties_for(e.val());
	});
});
</script>
