<div class="modal fade">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<form action="<?=routeUrl('project_settings_save_custom_field')?>" method="post" class="form-horizontal">
				<?=TWBS::modalHeader(t('edit_custom_field'))?>
				<div class="modal-body">
					<?=View::render('project_settings/custom_fields/_form.phtml', ['field' => $field])?>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-success"><?=t('save')?></button>
					<button type="button" class="btn btn-default" data-dismiss="modal"><?=t('cancel')?></button>
				</div>
			</form>
		</div>
	</div>
</div>
