<div class="project-settings components container">
	<div class="page-actions">
		<a href="<?=routeUrl('project_settings_new_custom_field')?>" class="btn btn-success" data-overlay="1">
			<span class="fa fa-plus"></span> <?=t('new_field')?>
		</a>
	</div>

	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th><?=t('name')?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($fields as $field) : ?>
			<tr>
				<td>
					<a href="<?=routeUrl('project_settings_edit_custom_field', ['id' => $field['id']])?>" data-overlay="1">
						<?=$field['name']?>
					</a>
				</td>
				<td class="actions">
					<a href="<?=routeUrl('project_settings_edit_custom_field', ['id' => $field['id']])?>" class="btn btn-xs btn-warning" data-overlay="1">
						<span class="fa fa-edit"></span> <?=t('edit')?>
					</a>
					<a href="<?=routeUrl('project_settings_delete_custom_field', ['id' => $field['id']])?>" class="btn btn-xs btn-danger" data-confirm="<?=t('confirm.delete')?>">
						<span class="fa fa-times"></span> <?=t('delete')?>
					</a>
				</td>
			</tr>
		<?php endforeach ?>
		</tbody>
	</table>
</div>
