<?php $this->extend('layouts/project_settings.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="project-settings new-custom-field content container">
	<h1 class="page-header"><?=t('new_custom_field')?></h1>

	<form action="<?=routeUrl('project_settings_create_custom_field')?>" method="post" class="form-horizontal">
		<?=View::render('project_settings/custom_fields/_form.phtml', ['field' => $field])?>
		<div class="form-actions">
			<?=Form::submit(t('create'), ['class' => 'btn btn-success'])?>
		</div>
	</form>
</div>
<?php $this->endSection(); ?>
