<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="admin admin-permissions content container">
	<h1 class="page-header"><?=t('permissions')?></h1>

	<nav id="admin-permissions-nav">
		<ul class="nav nav-tabs" role="tablist">
			<li class="<?=iif(Request::matches('/admin/permissions/usergroups$'), 'active')?>">
				<a href="<?=RouteUrl('admin_permissions_usergroups')?>"><?=t('groups')?></a>
			</li>
			<li class="<?=iif(Request::matches('/admin/permissions/roles$'), 'active')?>">
				<a href="<?=RouteUrl('admin_permissions_roles')?>"><?=t('roles')?></a>
			</li>
		</ul>
	</nav>

	<form action="<?=routeUrl($type == 'usergroups' ? 'admin_permissions_usergroups_save' : 'admin_permissions_roles_save')?>" method="post">
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th></th>
					<th><?=t('default')?></th>
				<?php foreach ($permissions as $info) : ?>
					<th><?=$info['name']?></th>
				<?php endforeach ?>
				</tr>
			</thead>
			<tbody>
			<?php foreach (Traq\Permissions::getPermissions(true) as $category => $perms) : ?>
				<tr>
					<th colspan="<?=count($permissions) + 2?>" class="ticket-permissions-category"><?=t($category)?></th>
				</tr>
				<?php foreach ($perms as $permission => $defaultValue) : ?>
				<tr>
					<td><?=t('permissions.' . $permission)?></td>
					<td>
						<input type="checkbox" name="permissions[defaults][<?=$permission?>]" value="1" <?=iif(isset($defaults[$permission]) && $defaults[$permission], 'checked')?>>
					</td>
					<?php foreach ($permissions as $info) :
						$permValue = isset($info['permissions'][$permission])
									 ? $info['permissions'][$permission]
									 : null;
						?>
						<td>
						<?php if ($type == 'usergroups' && $info['is_admin']) : ?>
							<select disabled>
								<option><?=t('confirm.yes')?></option>
							</select>
						<?php else : ?>
							<select name="permissions[<?=$info['id']?>][<?=$permission?>]">
								<option value="null" <?=iif($permValue === null, 'selected')?>><?=t('default')?></option>
								<option value="1" <?=iif($permValue === true, 'selected')?>><?=t('confirm.yes')?></option>
								<option value="0" <?=iif($permValue === false, 'selected')?>><?=t('confirm.no')?></option>
							</select>
						<?php endif ?>
						</td>
					<?php endforeach ?>
				</tr>
				<?php endforeach ?>
			<?php endforeach ?>
			</tbody>
		</table>

		<div class="form-actions text-center">
			<button type="submit" class="btn btn-success"><?=t('save')?></button>
		</div>
	</form>
</div>
<?php $this->endSection(); ?>
