<?php extendView('layouts/admin.phtml'); ?>

<div class="content">
	<h3><?= l('edit_status'); ?></h3>
	<form action="<?= Request::uri(); ?>" method="post">
		<?= show_errors($status->errors); ?>
		<div class="panel">
			<div class="panel-content">
				<?= view('admin/statuses/_form', ['status' => $status]); ?>
			</div>
		</div>
		<div class="actions">
			<input type="submit" value="<?= l('save'); ?>" class="btn-primary" />
		</div>
	</form>
</div>
