<div class="group">
	<label><?php echo l('label'); ?></label>
	<?php echo Form::text('label', array('value' => $tab->label)); ?>
</div>
<div class="group">
	<label><?php echo l('url'); ?></label>
	<?php echo Form::text('url', array('value' => $tab->url)); ?>
</div>
<div class="group">
	<label><?php echo l('groups'); ?></label>
	<?php echo Form::multiselect("groups[]", traq\models\Group::select_options(), explode(',', $tab->groups)); ?>
</div>
<div class="group">
	<label><?php echo l('project'); ?></label>
	<?php echo Form::select("project_id", array_merge(array(array('label' => l('all'), 'value' => 0)), traq\models\Project::select_options()), array('value' => $tab->project_id)); ?>
</div>
<div class="group">
	<label><?php echo l('display_order'); ?></label>
	<?php echo Form::text('display_order', array('value' => $tab->display_order)); ?>
</div>
