<?php $this->extend('layouts/project_settings.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="project-settings options content container">
	<h1 class="page-header"><?=t('settings')?></h1>

	<form action="<?=routeUrl('project_settings_save')?>" method="post" class="form-horizontal">
		<input type="hidden" name="_method" value="put">
		<?=View::render('project_settings/options/_form.phtml', ['project' => $proj])?>
		<div class="form-actions text-center">
			<button type="submit" class="btn btn-success"><?=t('save')?></button>
		</div>
	</form>
</div>
<?php $this->endSection(); ?>
