<h3><?= l('edit_component'); ?></h3>
<form action="<?= Request::requestUri(); ?>" method="post" class="overlay_thin">
	<?= show_errors($component->errors); ?>
	<div class="content">
		<?= view('project_settings/components/_form', [
			'component' => $component,
		]); ?>
	</div>
	<div class="actions">
		<input type="submit" value="<?= l('save'); ?>" />
		<input type="button" value="<?= l('cancel'); ?>" onclick="close_overlay();" />
	</div>
</form>
