<?php extendView('layouts/default.phtml'); ?>

<div class="content">
	<h2 class="page-title"><?php echo l('project_settings'); ?></h2>
</div>
<?= view('project_settings/_nav'); ?>
<div class="content">
	<h3><?php echo l('new_component'); ?></h3>
	<form action="<?= Request::requestUri(); ?>" method="post">
		<?php echo show_errors($component->errors); ?>
		<div class="tabular box">
			<?= view('project_settings/components/_form', [
				'component' => $component,
			]); ?>
		</div>
		<div class="actions">
			<input type="submit" value="<?= l('create'); ?>" />
		</div>
	</form>
</div>
