<div class="admin content">
	<h2><?= l('dashboard') ?></h2>

	<?php if (DB_HAS_PREFIX) { ?>
		<div class="alert alert-danger">
			This Traq installation has a database table prefix. This feature was deprecated in Traq 3.9 and will be removed in Traq 3.11.
		</div>
	<?php } ?>

	<div id="update">
		<?php if (settings('check_for_update')) { ?>
			<?php echo View::render('admin/dashboard/_update'); ?>
		<?php } else { ?>
			<strong><?php echo HTML::link(l('check_for_update'), '/admin/check_for_update'); ?></strong>
		<?php } ?>
	</div>

	<div class="flex mt-2">
		<div class="flex-grow mr-1">
			<h3><?= l('tickets') ?></h3>
			<div class="box">
				<dl>
					<dt><?php echo l('open'); ?></dt>
					<dd><?php echo $tickets['open']; ?></dd>

					<dt><?php echo l('closed'); ?></dt>
					<dd><?php echo $tickets['closed']; ?></dd>

					<dt><?php echo l('total'); ?></dt>
					<dd><?php echo $tickets['open'] + $tickets['closed']; ?></dd>
				</dl>
			</div>
		</div>

		<div class="flex-grow ml-1">
			<h3><?= l('users') ?></h3>
			<div class="box">
				<dl>
					<dt><?php echo l('total'); ?></dt>
					<dd><?php echo $users; ?></dd>

					<dt><?php echo l('newest'); ?></dt>
					<dd><?php echo HTML::link($latest_user->username, $latest_user->href()); ?></dd>
				</dl>
			</div>
		</div>
	</div>

</div>
