<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1 class="page-header">Admin Account</h1>

			<?php if (isset($errors)): ?>
				<?=View::render('partials/errors.phtml', ['errors' => $errors])?>
			<?php endif; ?>

			<form action="<?=$installStep("confirm")?>" method="post" class="form-horizontal">
				<div class="form-group">
					<label for="username" class="control-label col-md-3">Username</label>
					<div class="col-md-9">
						<input type="text" name="username" id="username" class="form-control">
					</div>
				</div>

				<div class="form-group">
					<label for="password" class="control-label col-md-3">Password</label>
					<div class="col-md-9">
						<input type="password" name="password" id="password" class="form-control">
					</div>
				</div>

				<div class="form-group">
					<label for="email" class="control-label col-md-3">Email</label>
					<div class="col-md-9">
						<input type="text" name="email" id="email" class="form-control">
					</div>
				</div>

				<div class="form-actions">
					<button type="submit" class="btn btn-primary">Next</button>
				</div>
			</form>
		</div>
	</div>
</div>
