<div class="container">
	<script type="text/javascript">
		$(document).ready(function(){
			var updateForm = function(element) {
				var driver = element.val();
				$(".form-group.driver-info").hide();
				$(".form-group.driver-info." + driver).show();
			}

			updateForm($("#driver"));

			$("#driver").on('change', function(){
				updateForm($(this));
			});
		});
	</script>

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1 class="page-header">Database Information</h1>

			<?php if (isset($errors)): ?>
				<?=View::render('partials/errors.phtml', ['errors' => $errors])?>
			<?php endif; ?>

			<form action="<?=$installStep("account_info")?>" method="post" class="form-horizontal">
				<div class="form-group">
					<label for="driver" class="control-label col-md-3">Database Type</label>
					<div class="col-md-9">
						<select name="driver" id="driver" class="form-control">
						<?php foreach ($drivers as $driver => $name): ?>
							<?php if (Request::post('driver') == $driver): ?>
								<option value="<?=$driver?>" selected="selected"><?=$name?></option>
							<?php else: ?>
								<option value="<?=$driver?>"><?=$name?></option>
							<?php endif; ?>
						<?php endforeach; ?>
						</select>
					</div>
				</div>

				<div class="form-group driver-info pdo_mysql pdo_pgsql">
					<label for="server" class="control-label col-md-3">Server</label>
					<div class="col-md-9">
						<input type="text" name="host" id="server" class="form-control" value="<?=Request::post('host')?>">
					</div>
				</div>

				<div class="form-group driver-info pdo_mysql pdo_pgsql">
					<label for="username" class="control-label col-md-3">Username</label>
					<div class="col-md-9">
						<input type="text" name="user" id="username" class="form-control" value="<?=Request::post('user')?>">
					</div>
				</div>

				<div class="form-group driver-info pdo_mysql pdo_pgsql">
					<label for="password" class="control-label col-md-3">Password</label>
					<div class="col-md-9">
						<input type="password" name="password" id="password" class="form-control" value="<?=Request::post('password')?>">
					</div>
				</div>

				<div class="form-group driver-info pdo_mysql pdo_pgsql">
					<label for="dbname" class="control-label col-md-3">Database name</label>
					<div class="col-md-9">
						<input type="text" name="dbname" id="dbname" class="form-control" value="<?=Request::post('dbname')?>">
					</div>
				</div>

				<div class="form-group driver-info pdo_sqlite">
					<label for="path" class="control-label col-md-3">Database Path</label>
					<div class="col-md-9">
						<input type="text" name="path" id="path" class="form-control"  value="<?=Request::post('path')?>">
					</div>
				</div>

				<div class="form-actions">
					<button type="submit" class="btn btn-primary">Next</button>
				</div>
			</form>
		</div>
	</div>
</div>
