<nav id="project-settings-nav" class="container">
	<ul class="nav nav-tabs" role="tablist">
		<li<?=Request::matches('/{pslug}/settings') ? ' class="active"' :''?>>
			<a href="<?=routeUrl('project_settings')?>"><?=t('project_settings')?></a>
		</li>
		<li<?=Request::matches('/{pslug}/settings/milestones(.*)') ? ' class="active"' :''?>>
			<a href="<?=routeUrl('project_settings_milestones')?>"><?=t('milestones')?></a>
		</li>
		<li<?=Request::matches('/{pslug}/settings/components(.*)') ? ' class="active"' :''?>>
			<a href="<?=routeUrl('project_settings_components')?>"><?=t('components')?></a>
		</li>
		<li<?=Request::matches('/{pslug}/settings/members(.*)') ? ' class="active"' :''?>>
			<a href="<?=routeUrl('project_settings_members')?>"><?=t('members')?></a>
		</li>
		<li<?=Request::matches('/{pslug}/settings/custom-fields(.*)') ? ' class="active"' :''?>>
			<a href="<?=routeUrl('project_settings_custom_fields')?>"><?=t('custom_fields')?></a>
		</li>
		<?=Hook::run('template:project_settings/_nav', [$currentProject])?>
	</ul>
</nav>
