<div class="traq_settings title content">
	<h2 id="page_title"><?php echo l('Settings'); ?></h2>
</div>
<?php echo View::render('admin/settings/_nav'); ?>
<div class="traq_settings content">
	<?php if (count($errors)): ?>
	<div class="error">
		<?php echo l('errors.security_questions.fill_in_fields_marked_red'); ?>
	</div>
	<?php endif; ?>
	<form action="<?php echo Request::requestUri(); ?>" method="post">
		<div id="questions">
		<?php foreach ($questions as $id => $question) {
			echo View::render('questions/_question', compact('id', 'question'));
		} ?>
		</div>
		<div class="actions">
			<input type="button" value="<?php echo l('add_question'); ?>" id="add_question" />
			<input type="submit" value="<?php echo l('save'); ?>" />
		</div>
	</form>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$('#add_question').click(function(){
		$.get('<?php echo Request::base('/admin/settings/security_questions/new_question'); ?>', function(data){
			$('#questions').append(data);
		});
	});
});
</script>
