<?php form('/step/2'); ?>
	<div class="tabular">
		<div class="group<?php echo isset($errors['type']) ? ' error' :'' ?>">
			<label for="type">Type</label>
			<select name="type" id="type">
				<option value="mysql"<?php echo (isset($_POST['type']) and $_POST['type'] == 'mysql') ? ' selected' :'' ?>>MySQL</option>
				<option value="sqlite"<?php echo (isset($_POST['type']) and $_POST['type'] == 'sqlite') ? ' selected' :'' ?>>SQLite</option>
				<option value="postgresql"<?php echo (isset($_POST['type']) and $_POST['type'] == 'postgresql') ? ' selected' :'' ?>>PostgreSQL</option>
			</select>
		</div>
		<div id="mypostgresql"<?php echo (isset($_POST['type']) and $_POST['type'] == 'sqlite') ? ' style="display: none;"' : ''; ?>>
			<div class="group<?php echo isset($errors['host']) ? ' error' :'' ?>">
				<label for="host">Server</label>
				<input type="text" name="host" id="host" value="127.0.0.1" />
			</div>
			<div class="group<?php echo isset($errors['username']) ? ' error' :'' ?>">
				<label for="username">Username</label>
				<input type="text" name="username" id="username" placeholder="Database username" />
			</div>
			<div class="group<?php echo isset($errors['password']) ? ' error' :'' ?>">
				<label for="password">Password</label>
				<input type="password" name="password" id="password" placeholder="Database password" />
			</div>
			<div class="group<?php echo isset($errors['database']) ? ' error' :'' ?>">
				<label for="database">Database</label>
				<input type="text" name="database" id="database" placeholder="Database name" />
			</div>
		</div>
		<div id="sqlite"<?php echo (!isset($_POST['type']) or $_POST['type'] != 'sqlite') ? ' style="display: none;"' : ''; ?>>
			<div class="group<?php echo isset($errors['path']) ? ' error' :'' ?>">
				<label for="path">Path</label>
				<input type="text" name="path" id="path" placeholder="Database path" />
			</div>
		</div>
		<div class="group<?php echo isset($errors['host']) ? ' error' :'' ?>">
			<label for="prefix">Prefix</label>
			<input type="text" name="prefix" id="prefix" placeholder="Table prefix" />
		</div>
		<div class="group">
			<input type="submit" value="Next" />
		</div>
	</div>
</form>
<script type="text/javascript">
$(document).ready(function(){
	$('#type').change(function(){
		var val = $('#type').val();

		if (val == 'mysql' || val == 'postgresql') {
			$('#mypostgresql').show();
			$('#sqlite').hide();
		} else if (val == 'sqlite') {
			$('#sqlite').show();
			$('#mypostgresql').hide();
		}
	});
});
</script>