<?php if ($config_created) { ?>
<div align="center">
	<strong>Installation Completed</strong><br />
	You may now <a href="<?php echo str_replace('/install', '', Nanite::base_uri()); ?>">login</a>.
</div>
<?php } else { ?>
<div align="center">
	The installer was unable to create the config file,
	You will need to save the code below to: <code>vendor/traq/config/database.php</code>
</div>
<br />
<pre id="config_code">
<?php echo htmlentities($config_code); ?>
</pre>
<?php } ?>
