<!doctype html>
<html lang="en" dir="ltr">
	<head>
		<title>Traq <?php echo $page_title; ?><?php echo isset($title) ? " / {$title}" :''; ?></title>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js" type="text/javascript"></script>
		<link rel="stylesheet" href="<?php echo Nanite::base_uri(); ?>install.css" />
	</head>
	<body>
		<div id="wrapper">
			<header id="head">
				<h1>Traq <?php echo $page_title; ?></h1>
				<h2><?php echo isset($title) ? $title :''; ?></h2>
			</header>
			<div id="page">
				<?php echo $output; ?>
			</div>
			<footer>
				Traq &copy; 2009-<?php echo date("Y"); ?> Traq.io
			</footer>
		</div>
	</body>
</html>
