<div class="form-group <?=$user->hasError('username') ? 'has-error' : ''?>">
	<label for="username" class="control-label col-md-3"><?=t('username')?></label>
	<div class="col-md-9">
		<input type="text" name="username" id="username" class="form-control" value="<?=e($user['username'])?>">
		<?php if ($user->hasError('username')) : ?>
		<div class="help-block"><?=$user->getError('username')[0]?></div>
		<?php endif ?>
	</div>
</div>
<div class="form-group">
	<label for="name" class="control-label col-md-3"><?=t('name')?></label>
	<div class="col-md-9">
		<input type="text" name="name" id="name" class="form-control" value="<?=e($user['name'])?>">
	</div>
</div>
<div class="form-group <?=$user->hasError('password') ? 'has-error' : ''?>">
	<label for="password" class="control-label col-md-3"><?=t('password')?></label>
	<div class="col-md-9">
		<?=Form::password('password', [
			'class' => 'form-control',
			'placeholder' => !$user->isNew() ? t('leave_blank_for_current') : ''
		])?>
		<?php if ($user->hasError('password')) : ?>
		<div class="help-block"><?=$user->getError('password')[0]?></div>
		<?php endif ?>
	</div>
</div>
<div class="form-group <?=$user->hasError('email') ? 'has-error' : ''?>">
	<label for="email" class="control-label col-md-3"><?=t('email')?></label>
	<div class="col-md-9">
		<input type="text" name="email" id="email" class="form-control" value="<?=e($user['email'])?>">
		<?php if ($user->hasError('email')) : ?>
		<div class="help-block"><?=$user->getError('email')[0]?></div>
		<?php endif ?>
	</div>
</div>
<div class="form-group <?=$user->hasError('group') ? 'has-error' : ''?>">
	<label for="group" class="control-label col-md-3"><?=t('group')?></label>
	<div class="col-md-9">
		<?=Form::select('group_id', Traq\Models\Group::selectOptions(), [
			'value' => $user['group_id'],
			'id' => 'group',
			'class' => 'form-control'
		])?>
	</div>
</div>
