<div class="admin users container">
	<h1 class="page-header"><?=$t('users')?></h1>

	<div class="page-actions">
		<?=HTML::link(TWBS::fa('plus', $t('new_user')), $route('new_admin_user'), [
			'class' => 'btn btn-success',
			'data-overlay' => true
		])?>
	</div>

	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th><?=$t('username')?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($users as $user): ?>
			<tr>
				<td><?=HTML::link($user->username, $route('edit_admin_user', ['id' => $user->id]))?></td>
				<td class="actions">
					<?=HTML::link(TWBS::fa('edit', $t('edit')), $route('edit_admin_user', ['id' => $user->id]), [
						'class' => 'btn btn-xs btn-warning',
						'data-overlay' => true
					])?>
					<?=HTML::link(TWBS::fa('times', $t('delete')), $route('delete_admin_user', ['id' => $user->id]), [
						'class' => 'btn btn-xs btn-danger',
						'data-confirm' => $t('confirm.delete')
					])?>
				</td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>
