<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="admin admin-users-new content container">
	<h1 class="page-header"><?=t('new_user')?></h1>

	<form action="<?=routeUrl('admin_create_user')?>" method="post" class="form-horizontal">
		<?=View::render('admin/users/_form.phtml', ['user' => $user])?>
		<div class="form-actions text-center">
			<button type="submit" class="btn btn-success"><?=t('create')?></button>
		</div>
	</form>
</div>
<?php $this->endSection(); ?>
