<section id="login_form" class="content">
	<div class="mx-auto w-96">
		<h2 class="page-title"><?= l('login'); ?></h2>
		<?php if (!isset($validation_required)) : ?>
			<?php if (isset($error) and $error) : ?>
				<div class="alert-danger">
					<?= l('errors.invalid_username_or_password'); ?>
				</div>
			<?php endif; ?>
			<?php if (isset($validated) && $validated) : ?>
				<div class="alert alert-success">
					<?= l('account_validated') ?>
				</div>
			<?php endif; ?>
			<form action="<?= Request::base('login'); ?>" method="post">
				<div class="panel">
					<div class="panel-content">
						<?php if (isset($redirect)) : ?>
							<input type="hidden" name="redirect" value="<?= $redirect; ?>" />
						<?php endif; ?>
						<div class="form-group-group">
							<label><?= l('username'); ?></label>
							<?= Form::text('username'); ?>
						</div>
						<div class="form-group-group">
							<label><?= l('password'); ?></label>
							<?= Form::password('password'); ?>
						</div>
					</div>

					<div class="panel-footer">
						<input type="submit" value="<?= l('login'); ?>" class="btn-primary" />
					</div>
				</div>
			</form>
			<?= HTML::link(l('forgot_password'), '/login/resetpassword'); ?>
		<?php else : ?>
			<div class="alert alert-danger">
				<?= l('errors.email_validation_required') ?>
			</div>
		<?php endif; ?>
	</div>
</section>
