<?php extendView('layouts/default.phtml'); ?>

<section id="register_form" class="content">
	<div class="mx-auto w-3/4">
		<h2 class="page-title"><?= l('register'); ?></h2>
		<?php if (!isset($validation_required) || !$validation_required) : ?>
			<?php if (isset($user)) :
				echo show_errors($user->errors);
			endif; ?>
			<form action="<?= Request::base('register'); ?>" method="post">
				<div class="panel">
					<div class="panel-content">
						<div class="form-group-row">
							<label for="username"><?= l('username'); ?></label>
							<?= Form::text('username', array('value' => $user->username)); ?>
						</div>
						<div class="form-group-row">
							<label for="name"><?= l('name'); ?></label>
							<?= Form::text('name', array('value' => $user->name)); ?>
						</div>
						<div class="form-group-row">
							<label for="password"><?= l('password'); ?></label>
							<?= Form::password('password'); ?>
						</div>
						<div class="form-group-row">
							<label for="email"><?= l('email'); ?></label>
							<?= Form::text('email', array('value' => $user->email)); ?>
						</div>
						<?php FishHook::run('template:users/register'); ?>
					</div>
					<div class="panel-footer">
						<input type="submit" value="<?= l('register'); ?>" class="btn-primary" />
					</div>
				</div>
			</form>
		<?php else : ?>
			<?= l('please_validate_your_account') ?>
		<?php endif; ?>
	</div>
</section>
