<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="admin admin-priorities-edit content container">
	<h1 class="page-header"><?=t('edit_priority')?></h1>

	<form action="<?=routeUrl('admin_save_priority')?>" method="post" class="form-horizontal">
		<input type="hidden" name="_method" value="put">
		<?=View::render('admin/priorities/_form.phtml', ['priority' => $priority])?>
		<div class="form-actions text-center">
			<button type="submit" class="btn btn-success"><?=t('create')?></button>
		</div>
	</form>
</div>
<?php $this->endSection(); ?>
