<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'edit-priority-modal');
$this->startSection('modal-size', 'modal-sm');
$this->startSection('modal-title', t('edit_priority'));
$this->startSection('modal-primary-btn-txt', t('save'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('admin_save_priority')?>" method="post" class="form-horizontal">
<input type="hidden" name="_method" value="put">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('admin/priorities/_form.phtml', ['priority' => $priority])?>
<?php $this->endSection(); ?>
