<div class="admin-priorities container">
	<h1 class="page-header"><?=$t('edit_priority')?></h1>

	<form action="<?=Request::basePath($route('edit_admin_priority'))?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($priority)?>
		<?=View::render('admin/priorities/_form.phtml', ['priority' => $priority])?>
		<div class="form-actions">
			<?=Form::submit($t('save'), ['class' => 'btn btn-success'])?>
		</div>
	</form>
</div>
