<div class="admin priorities container">
    <h1 class="page-header"><?=$t('priorities')?></h1>

    <div class="page-actions">
        <?=HTML::link(TWBS::fa('plus', $t('new_priority')), "admin/priorities/new", [
            'class'        => 'btn btn-success',
            'data-overlay' => true
        ])?>
    </div>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th><?=$t('name')?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($priorities as $priority): ?>
            <tr>
                <td><?=HTML::link($priority->name, "admin/priorities/{$priority->id}/edit")?></td>
                <td class="actions">
                    <?=HTML::link(TWBS::fa('edit', $t('edit')), "admin/priorities/{$priority->id}/edit", [
                        'class'   => 'btn btn-xs btn-warning',
                        'data-overlay' => true
                    ])?>
                    <?=HTML::link(TWBS::fa('times', $t('delete')), "admin/priorities/{$priority->id}/delete", [
                        'class'        => 'btn btn-xs btn-danger',
                        'data-confirm' => $t('confirm.delete')
                    ])?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
