<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="admin admin-priorities-new content container">
	<h1 class="page-header"><?=t('new_priority')?></h1>

	<form action="<?=routeUrl('admin_create_priority')?>" method="post" class="form-horizontal">
		<?=View::render('admin/priorities/_form.phtml', ['priority' => $priority])?>
		<div class="form-actions text-center">
			<button type="submit" class="btn btn-success"><?=t('create')?></button>
		</div>
	</form>
</div>
<?php $this->endSection(); ?>
