<div class="form-group-row">
	<label><?= l('name'); ?></label>
	<?= Form::text('name', array('value' => $role->name)); ?>
</div>
<div class="form-group-row">
	<?= Form::label(l('assignable'), 'assignable'); ?>
	<?= Form::checkbox('assignable', 1, array('checked' => $role->assignable)); ?>
</div>
<div class="form-group-row">
	<?= Form::label(l('project'), 'project'); ?>
	<?= Form::select('project', array_merge(array(array('label' => l('all'), 'value' => 0)), traq\models\Project::select_options()), array('value' => $role->project_id)); ?>
</div>
