<h3><?= l('edit_role'); ?></h3>
<form action="<?= Request::requestUri(); ?>" method="post" class="overlay">
	<?= show_errors($role->errors); ?>
	<div class="content">
		<?= view('admin/project_roles/_form', ['role' => $role]); ?>
	</div>
	<div class="actions">
		<input type="submit" value="<?= l('save'); ?>" />
		<input type="button" value="<?= l('cancel'); ?>" onclick="close_overlay();" />
	</div>
</form>
