<?php extendView('layouts/admin.phtml'); ?>

<div class="content">
	<h3><?= l('new_role'); ?></h3>
	<form action="<?= Request::requestUri(); ?>" method="post">
		<?= show_errors($role->errors); ?>
		<div class="panel">
			<div class="panel-content">
				<?= view('admin/project_roles/_form', ['role' => $role]); ?>
			</div>
		</div>
		<div class="actions">
			<input type="submit" value="<?= l('create'); ?>" />
		</div>
	</form>
</div>
