<div class="form-group">
    <?=Form::label($t('name'), 'name', ['class' => 'control-label col-md-3'])?>
    <div class="col-md-9">
        <?=Form::text('name', ['value' => $status->name, 'class' => 'form-control'])?>
    </div>
</div>
<div class="form-group">
    <?=Form::label($t('type'), 'type', ['class' => 'control-label col-md-3'])?>
    <div class="col-md-9">
        <?=Form::select('type', $typeSelectOptions, [
            'value' => $status->status, 'class' => 'form-control'
        ])?>
    </div>
</div>
<div class="form-group">
    <?=Form::label($t('show_on_changelog'), 'changelog', ['class' => 'control-label col-md-3'])?>
    <div class="col-md-9">
        <?=Form::checkbox('changelog', 1, ['checked' => $status->changelog])?>
    </div>
</div>
