<div class="form-group <?=$status->hasError('name') ? 'has-error' : ''?>">
	<label for="name" class="control-label col-md-3"><?=t('name')?></label>
	<div class="col-md-9">
		<input type="text" name="name" id="name" class="form-control" value="<?=e($status['name'])?>">
		<?php if ($status->hasError('name')) : ?>
		<div class="help-block"><?=$status->getError('name')[0]?></div>
		<?php endif ?>
	</div>
</div>
<div class="form-group">
	<label for="type" class="control-label col-md-3"><?=t('type')?></label>
	<div class="col-md-9">
		<?=Form::select('type', $typeSelectOptions, [
			'value' => $status['status'], 'class' => 'form-control'
		])?>
	</div>
</div>
<div class="form-group">
	<label for="show_on_changelog" class="control-label col-md-3"><?=t('show_on_changelog')?></label>
	<div class="col-md-9">
		<?=Form::checkbox('show_on_changelog', 1, ['checked' => $status['show_on_changelog']])?>
	</div>
</div>
