<div class="admin statuses container">
    <h1 class="page-header"><?=$t('statuses')?></h1>

    <div class="page-actions">
        <?=HTML::link(TWBS::fa('plus', $t('new_status')), "admin/statuses/new", [
            'class'        => 'btn btn-success',
            'data-overlay' => true
        ])?>
    </div>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th><?=$t('name')?></th>
                <th><?=$t('type')?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($statuses as $status): ?>
            <tr>
                <td><?=HTML::link($status->name, "admin/statuses/{$status->id}")?></td>
                <td><?=$t("status.type.{$status->status}")?></td>
                <td class="actions">
                    <?=HTML::link(TWBS::fa('edit', $t('edit')), "admin/statuses/{$status->id}", [
                        'class'   => 'btn btn-xs btn-warning',
                        'data-overlay' => true
                    ])?>
                    <?=HTML::link(TWBS::fa('times', $t('delete')), "admin/statuses/{$status->id}/delete", [
                        'class'        => 'btn btn-xs btn-danger',
                        'data-confirm' => $t('confirm.delete')
                    ])?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
