<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="admin admin-statuses container">
	<h1 class="page-header"><?=t('statuses')?></h1>

	<div class="page-actions">
		<a href="<?=routeUrl('admin_new_status')?>" class="btn btn-success" data-overlay="true">
			<span class="fa fa-plus"></span> <?=t('new_status')?>
		</a>
	</div>

	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th><?=t('name')?></th>
				<th><?=t('type')?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($statuses as $status) : ?>
			<tr>
				<td>
					<a href="<?=routeUrl('admin_edit_status', ['id' => $status['id']])?>" data-overlay="true">
						<?=$status['name']?>
					</a>
				</td>
				<td><?=t("status.type.{$status->status}")?></td>
				<td class="actions text-right">
					<a href="<?=routeUrl('admin_edit_status', ['id' => $status['id']])?>" class="btn btn-xs btn-warning" data-overlay="true">
						<span class="fa fa-edit"></span> <?=t('edit')?>
					</a>
					<a href="<?=routeUrl('admin_delete_status', ['id' => $status['id']])?>" class="btn btn-xs btn-danger" data-method="delete" data-confirm="<?=t('confirm.delete')?>">
						<span class="fa fa-times"></span> <?=t('delete')?>
					</a>
				</td>
			</tr>
		<?php endforeach ?>
		</tbody>
	</table>
</div>
<?php $this->endSection(); ?>
