<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'new-status-modal');
$this->startSection('modal-size', 'modal-lg');
$this->startSection('modal-title', t('new_status'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('admin_create_status')?>" method="post" class="form-horizontal">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('admin/statuses/_form.phtml', ['status' => $status])?>
<?php $this->endSection(); ?>
