<?php extendView('layouts/default.phtml'); ?>

<div class="profile content">
	<h2 class="page-title"><?= l('xs_profile', $profile->name) ?></h2>

	<div class="flex">
		<div class="w-[400px]">
			<div class="panel">
				<div class="panel-content">
					<h3><?= l('information'); ?></h3>
					<dl>
						<dt><?= l('group'); ?></dt>
						<dd><?= $profile->group->name; ?></dd>

						<dt><?= l('assigned_tickets'); ?></dt>
						<dd><?= $profile->assigned_tickets->exec()->row_count(); ?></dd>

						<dt><?= l('tickets_created'); ?></dt>
						<dd><?= $profile->tickets->exec()->row_count(); ?></dd>

						<dt><?= l('ticket_updates'); ?></dt>
						<dd><?= $profile->ticket_updates->exec()->row_count(); ?></dd>

						<dt><?= l('member_since'); ?></dt>
						<dd><?= ($profile->created_at ? ldate(settings('date_format')) : l('unknown')); ?></dd>
						<?php FishHook::run('template:users/users/view', array($profile)); ?>
					</dl>
				</div>
			</div>

			<?php if (count($memberships)) : ?>
				<div class="panel mt-4">
					<div class="panel-content">
						<h3><?= l('projects'); ?></h3>
						<ul class="mb-0">
							<?php foreach ($memberships as $membership) : ?>
								<?php if (currentUser()->permission($membership->project->id, 'view')) : ?>
									<li>
										<a href="<?= Request::base($membership->project->href()) ?>"><?= $membership->project->name ?></a>, <?= $membership->role->name ?>
									</li>
								<?php endif; ?>
							<?php endforeach; ?>
						</ul>
					</div>
				</div>
			<?php endif; ?>
		</div>

		<div class="ml-4 w-full">
			<?php if (count($memberships)) { ?>
				<div id="assigned_to">
					<h3><?= l('assigned_tickets'); ?></h3>

					<?php foreach ($memberships as $membership) : ?>
						<div class="panel" x-data="profileTickets({ userName: '<?= $profile->name; ?>', projectSlug: '<?= $membership->project->slug; ?>' })">
							<div class="panel-title" @click="open = !open">
								<h3><?= l($membership->project->name); ?></h3>
								<i class="fa-solid fa-chevron-down" x-show="!open"></i>
								<i class="fa-solid fa-chevron-up" x-show="open"></i>
							</div>
							<div x-show="open" x-transition>
								<div>
									<table x-show="tickets.length > 0">
										<thead>
											<th class="id"><?= l('id'); ?></th>
											<th class="summary"><?= l('summary'); ?></th>
											<th class="status"><?= l('status'); ?></th>
											<th class="type"><?= l('type'); ?></th>
											<th class="milestone"><?= l('milestone'); ?></th>
											<th class="component"><?= l('component'); ?></th>
										</thead>
										<tbody>
											<template x-for="ticket in tickets" :key="ticket.ticket_id">
												<tr>
													<td x-text="ticket.ticket_id"></td>
													<td>
														<a :href="window.traq.base + projectSlug + '/tickets/' + ticket.ticket_id" x-text="ticket.summary"></a>
													</td>
													<td x-text="ticket.status"></td>
													<td x-text="ticket.type"></td>
													<td x-text="ticket.milestone"></td>
													<td x-text="ticket.component"></td>
												</tr>
											</template>
										</tbody>
									</table>
									<div x-show="tickets.length === 0">
										<div class="panel-content text-center"><?= l('no_tickets_assigned'); ?></div>
									</div>
								</div>

								<div class="pagination px-2">
									<button @click="page--" type="button" :disabled="page <= 1">
										<i class="fa-solid fa-chevron-left"></i>
										<span><?= l('previous'); ?></span>
									</button>
									<div>
										<span x-text="page"></span>
										<span>/</span>
										<span x-text="totalPages"></span>
									</div>
									<button @click="page++" type="button" :disabled="page >= totalPages">
										<span><?= l('next'); ?></span>
										<i class="fa-solid fa-chevron-right"></i>
									</button>
								</div>
							</div>
						</div>
					<?php endforeach; ?>
				</div>
			<?php } ?>
		</div>
	</div>
</div>
