<?php
$totalTickets = $milestone['open_tickets'] + $milestone['closed_tickets'];
$closedPercent = getPercent($milestone['closed_tickets'], $totalTickets);
$startedPercent = getPercent($milestone['started_tickets'], $totalTickets);
$openPercent = getPercent($milestone['open_tickets'] - $milestone['started_tickets'], $totalTickets);
?>
<div class="milestone-progress">
	<div class="progress">
		<div class="progress-bar progress-bar-success" role="progressbar" style="width: <?=$closedPercent?>%;"></div>
		<div class="progress-bar progress-bar-warning" role="progressbar" style="width: <?=$startedPercent?>%;"></div>
		<div class="progress-bar progress-bar-danger" role="progressbar" style="width: <?=$openPercent?>%;"></div>
	</div>
	<ul class="issue-counts">
		<li>
			<a href="<?=routeUrl('tickets')?>?closed&amp;milestone=<?=$milestone['slug']?>"><?=t('x_closed', $milestone['closed_tickets'])?></a>
		</li>
		<li>
			<a href="<?=routeUrl('tickets')?>?started&amp;milestone=<?=$milestone['slug']?>"><?=t('x_started', $milestone['started_tickets'])?></a>
		</li>
		<li>
			<a href="<?=routeUrl('tickets')?>?open&amp;milestone=<?=$milestone['slug']?>"><?=t('x_open', $milestone['open_tickets'])?></a>
		</li>
	</ul>
</div>
