<div class="roadmap container">
	<h1 class="page-header"><?=t('roadmap')?></h1>

	<nav>
		<ul class="nav nav-tabs">
			<li<?=Request::matches('/{pslug}/roadmap') ? ' class="active"' : ''?>>
				<a href="<?=routeUrl('roadmap')?>"><?=t('active')?></a>
			</li>
			<li<?=Request::matches('/{pslug}/roadmap/completed') ? ' class="active"' : ''?>>
				<a href="<?=routeUrl('roadmap_completed')?>"><?=t('completed')?></a>
			</li>
			<li<?=Request::matches('/{pslug}/roadmap/all') ? ' class="active"' : ''?>>
				<a href="<?=routeUrl('roadmap_all')?>"><?=t('all')?></a>
			</li>
		</ul>
	</nav>

	<ul class="milestones">
	<?php foreach ($milestones as $milestone) : ?>
		<li>
			<h2>
				<a href="<?=routeUrl('milestone', ['mslug' => $milestone['slug']])?>"><?=$milestone['name']?></a>
				<?php if ($milestone['codename']) : ?>
					<small><em class="project-codename"><?=$milestone['codename']?></em></small>
				<?php endif ?>
			</h2>
			<?=View::render('roadmap/_progress_bar.phtml', ['milestone' => $milestone])?>
			<ul class="issue-counts">
				<li>
					<a href="<?=routeUrl('tickets')?>?open&amp;milestone=<?=$milestone['slug']?>"><?=t('x_open', $milestone['open_tickets'])?></a>
				</li>
				<li>
					<a href="<?=routeUrl('tickets')?>?started&amp;milestone=<?=$milestone['slug']?>"><?=t('x_started', $milestone['started_tickets'])?></a>
				</li>
				<li>
					<a href="<?=routeUrl('tickets')?>?closed&amp;milestone=<?=$milestone['slug']?>"><?=t('x_closed', $milestone['closed_tickets'])?></a>
				</li>
			</ul>
			<div>
				<?=Format::text($milestone['info'])?>
			</div>
		</li>
	<?php endforeach ?>
	</ul>
</div>
