<div class="form-group <?=iif($field->hasError('name'), 'has-error')?>">
	<label for="name" class="control-label col-md-3"><?=t('name')?></label>
	<div class="col-md-9">
		<?=Form::text('name', ['value' => $field['name'], 'class' => 'form-control'])?>
		<?php if ($field->hasError('name')) : ?>
		<div class="help-block"><?=$field->getError('name')[0]?></div>
		<?php endif ?>
	</div>
</div>
<div class="form-group <?=iif($field->hasError('slug'), 'has-error')?>">
	<label for="slug" class="control-label col-md-3"><?=t('slug')?></label>
	<div class="col-md-9">
		<?=Form::text('slug', ['value' => $field['slug'], 'class' => 'form-control'])?>
		<?php if ($field->hasError('slug')) : ?>
		<div class="help-block"><?=$field->getError('slug')[0]?></div>
		<?php endif ?>
	</div>
</div>
<div class="form-group <?=iif($field->hasError('type'), 'has-error')?>">
	<label for="type" class="control-label col-md-3"><?=t('type')?></label>
	<div class="col-md-9">
		<?=Form::select('type', Traq\Models\CustomField::typesSelectOptions(), ['value' => $field['type'], 'id' => 'field_type', 'class' => 'form-control'])?>
		<?php if ($field->hasError('type')) : ?>
		<div class="help-block"><?=$field->getError('type')[0]?></div>
		<?php endif ?>
	</div>
</div>
<div class="form-group">
	<div class="col-md-9 col-md-offset-3">
		<label>
			<input type="checkbox" name="is_required" value="1" <?=iif($field['is_required'], "checked")?>> <?=t('required')?>
		</label>
	</div>
</div>

<div class="dynamic-fields">
	<div class="form-group cf-type-text cf-type-integer <?=iif($field->hasError('min_length'), 'has-error')?>">
		<label for="min_length" class="control-label col-md-3"><?=t('min_length')?></label>
		<div class="col-md-9">
			<?=Form::text('min_length', ['class' => 'form-control', 'value' => $field['min_length']])?>
			<small class="help-text"><?=t('help.custom_fields.min_length')?></small>
			<?php if ($field->hasError('min_length')) : ?>
			<div class="help-block"><?=$field->getError('min_length')[0]?></div>
			<?php endif ?>
		</div>
	</div>

	<div class="form-group cf-type-text cf-type-integer <?=iif($field->hasError('max_length'), 'has-error')?>">
		<label for="max_length" class="control-label col-md-3"><?=t('max_length')?></label>
		<div class="col-md-9">
			<?=Form::text('max_length', ['class' => 'form-control', 'value' => $field['max_length']])?>
			<small class="help-text"><?=t('help.custom_fields.max_length')?></small>
			<?php if ($field->hasError('max_length')) : ?>
			<div class="help-block"><?=$field->getError('max_length')[0]?></div>
			<?php endif ?>
		</div>
	</div>

	<div class="form-group cf-type-text cf-type-integer <?=iif($field->hasError('regex'), 'has-error')?>">
		<label for="regex" class="control-label col-md-3"><?=t('regex')?></label>
		<div class="col-md-9">
			<?=Form::text('regex', ['class' => 'form-control', 'value' => $field['regex']])?>
			<small class="help-text"><?=t('help.custom_fields.regex')?></small>
			<?php if ($field->hasError('regex')) : ?>
			<div class="help-block"><?=$field->getError('regex')[0]?></div>
			<?php endif ?>
		</div>
	</div>

	<div class="form-group cf-type-text cf-type-integer <?=iif($field->hasError('default_value'), 'has-error')?>">
		<label for="default_value" class="control-label col-md-3"><?=t('default_value')?></label>
		<div class="col-md-9">
			<?=Form::text('default_value', ['class' => 'form-control', 'value' => $field['default_value']])?>
			<?php if ($field->hasError('default_value')) : ?>
			<div class="help-block"><?=$field->getError('default_value')[0]?></div>
			<?php endif ?>
		</div>
	</div>

	<div class="form-group cf-type-select">
		<div class="col-md-9 col-md-offset-3">
			<label>
				<input type="checkbox" name="multiple" value="1" <?=iif($field['multiple'], "checked")?>> <?=t('multichoice')?>
			</label>
		</div>
	</div>

	<div class="form-group cf-type-select <?=iif($field->hasError('values'), 'has-error')?>">
		<label for="field_values" class="control-label col-md-3"><?=t('values')?></label>
		<div class="col-md-9">
			<textarea name="field_values" id="field_values" class="form-control"><?=$field['field_values']?></textarea>
			<small class="help-text"><?=t('help.custom_fields.values')?></small>
			<?php if ($field->hasError('field_values')) : ?>
			<div class="help-block"><?=$field->getError('field_values')[0]?></div>
			<?php endif ?>
		</div>
	</div>
</div>

<div class="form-group <?=iif($field->hasError('ticket_type_ids'), 'has-error')?>">
	<label for="ticket_type_ids[]" class="control-label col-md-3"><?=t('ticket_types')?></label>
	<div class="col-md-9">
		<?=Form::select(
			'ticket_type_ids[]',
			array_merge(
				[['label' => t('all'), 'value' => 0]],
				Traq\Models\Type::selectOptions()
			),
			[
				'class' => 'form-control',
				'value' => $field['ticket_type_ids'],
				'multiple' => true
			]
		)?>
		<?php if ($field->hasError('ticket_type_ids')) : ?>
		<div class="help-block"><?=$field->getError('ticket_type_ids')[0]?></div>
		<?php endif ?>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	// Show only text field properties
	show_properties_for($('#field_type').val());

	function show_properties_for(type) {
		// Text field
		if (type == 'text') {
			$('.cf-type-integer').hide();
			$('.cf-type-select').hide();
			$('.cf-type-text').show();
		}
		// Integer field
		else if (type == 'integer') {
			$('.cf-type-text').hide();
			$('.cf-type-select').hide();
			$('.cf-type-integer').show();
		}
		// Select field
		else if (type == 'select') {
			$('.cf-type-text').hide();
			$('.cf-type-integer').hide();
			$('.cf-type-select').show();
		}
	}

	$("#field_type").change(function(){
		var e = $(this);
		show_properties_for(e.val());
	});
});
</script>
