<div class="form-group">
	<label><?php echo l('page_title'); ?></label>
	<?php echo Form::text('title', array('value' => $page->title)); ?>
</div>
<div class="form-group">
	<label><?php echo l('slug'); ?></label>
	<div class="input-group">
		<?php echo Form::text('slug', array('value' => $page->slug)); ?> <abbr class="input-group-hint" title="<?php echo l('help.slug'); ?>">?</abbr>
	</div>
</div>
<div>
	<label><?php echo l('page_content'); ?></label>
	<textarea name="body" x-data x-mde="{}"><?= htmlspecialchars($page->revision->content) ?></textarea>
</div>
