<?php extendView('layouts/default.phtml'); ?>

<?php echo View::render('wiki/_nav'); ?>
<div class="wiki content">
	<div id="head">
		<h2 class="page-title"><?php echo l('new_page'); ?></h2>
	</div>
	<form action="<?php echo Request::requestUri(); ?>" method="post">
		<?php echo show_errors($page->errors); ?>
		<div class="tabular box">
			<?php echo View::render('wiki/_form', array('page' => $page)); ?>
		</div>
		<div class="actions">
			<input type="submit" value="<?php echo l('create'); ?>" />
		</div>
	</form>
</div>
