<?php $this->extend('layouts/project_settings.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="project-settings members container">
	<form action="<?=routeUrl('project_settings_create_member')?>" method="post" class="form-inline">
		<div class="form-group">
			<?=Form::label(t("username"), "username")?>
			<?=Form::text("username", ['class' => "form-control"])?>
		</div>
		<div class="form-group">
			<?=Form::label(t("role"), "role_id")?>
			<?=Form::select('role_id', Traq\Models\ProjectRole::selectOptions(currentProject()['id']), ['class' => 'form-control'])?>
		</div>

		<?=Form::submit(t("add"), ['class' => "btn btn-success"])?>
	</form>

	<form action="<?=routeUrl('project_settings_save_members')?>" method="post">
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th><?=t('name')?></th>
					<th><?=t('role')?></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($userRoles as $relation) : ?>
				<tr>
					<td><?=$relation['user_name']?></td>
					<td>
						<?=Form::select("user[{$relation['user_id']}][role_id]", Traq\Models\ProjectRole::selectOptions(currentProject()['id']), ['value' => $relation['project_role_id'], 'class' => 'form-control'])?>
					</td>
					<td class="actions">
						<a href="<?=routeUrl('project_settings_delete_member', ['id' => $relation['user_id']])?>" data-method="delete" class="btn btn-xs btn-danger">
							<span class="fa fa-times"></span> <?=t('delete')?>
						</a>
					</td>
				</tr>
			<?php endforeach ?>
			</tbody>
		</table>

		<div class="form-actions">
			<?=Form::submit(t("save"), ['class' => "btn btn-success"])?>
		</div>
	</form>
</div>
<?php $this->endSection(); ?>
