<div class="project-settings members container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<?=View::render('errors/_messages_for.phtml', ['title' => $t('errors.correct_the_following'), 'messages' => $errors])?>

			<form action="" method="post" class="form-horizontal">
				<div class="form-group">
					<?=Form::label($t("username"), "username", ['class' => "control-label col-md-3"])?>
					<div class="col-md-9">
						<?=Form::text("username", ['value' => Request::post('username'), 'class' => "form-control"])?>
					</div>
				</div>

				<div class="form-group">
					<?=Form::label($t("role"), "role", ['class' => "control-label col-md-3"])?>
					<div class="col-md-9">
						<?=Form::select('role_id', Traq\Models\ProjectRole::selectOptions($project->id))?>
					</div>
				</div>

				<div class="form-actions">
					<?=Form::submit($t('add'), ['class' => "btn btn-success"])?>
				</div>
			</form>
		</div>
	</div>
</div>

