<div class="form-group <?=$severity->hasError('name') ? 'has-error' : ''?>">
	<label for="name" class="control-label col-md-3"><?=t('name')?></label>
	<div class="col-md-9">
		<input type="text" name="name" id="name" class="form-control" value="<?=e($severity['name'])?>">
		<?php if ($severity->hasError('name')) : ?>
		<div class="help-block"><?=$severity->getError('name')[0]?></div>
		<?php endif ?>
	</div>
</div>
<div class="form-group">
	<label for="level" class="control-label col-md-3"><?=t('level')?></label>
	<div class="col-md-9">
		<input type="text" name="level" id="level" class="form-control" value="<?=e($severity['level'])?>">
	</div>
</div>
