<div class="form-group">
	<?=Form::label($t('name'), 'name', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::text('name', ['value' => $severity->name, 'class' => 'form-control'])?>
	</div>
</div>
<div class="form-group">
	<?=Form::label($t('level'), 'level', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::text('level', ['value' => $severity->level, 'class' => 'form-control'])?>
	</div>
</div>
