<div class="admin-severities container">
	<h1 class="page-header"><?=t('edit_status')?></h1>

	<form action="<?=routeUrl('admin_save_severity', ['id' => $severity['id']])?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($severity)?>
		<?=View::render('admin/severities/_form.phtml', ['severity' => $severity])?>
		<div class="form-actions">
			<?=Form::submit(t('save'), ['class' => 'btn btn-success'])?>
		</div>
	</form>
</div>
