<div class="modal fade">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<form action="<?=routeUrl('admin_save_severity', ['id' => $severity['id']])?>" method="post" class="form-horizontal">
				<?=TWBS::modalHeader(t('edit_severity'))?>
				<div class="modal-body">
					<?=View::render('admin/severities/_form.phtml', ['severity' => $severity])?>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-success"><?=t('save')?></button>
					<button type="button" class="btn btn-default" data-dismiss="modal"><?=t('cancel')?></button>
				</div>
			</form>
		</div>
	</div>
</div>
