<div class="modal fade">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form action="<?=Request::basePath($route('edit_admin_severity'))?>" method="post" class="form-horizontal">
				<?=TWBS::modalHeader($t('edit_severity'))?>
				<div class="modal-body">
					<?=View::render('admin/severities/_form.phtml', ['severity' => $severity])?>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-success"><?=$t('save')?></button>
					<button type="button" class="btn btn-default" data-dismiss="modal"><?=$t('cancel')?></button>
				</div>
			</form>
		</div>
	</div>
</div>
