<div class="admin severities container">
	<h1 class="page-header"><?=t('severities')?></h1>

	<div class="page-actions">
		<a href="<?=routeUrl('admin_new_severity')?>" class="btn btn-success" data-overlay="1">
			<span class="fa fa-plus"></span> <?=t('new_severity')?>
		</a>
	</div>

	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th><?=t('name')?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($severities as $severity) : ?>
			<tr>
				<td>
					<a href="<?=routeUrl('admin_edit_severity', ['id' => $severity['id']])?>" data-overlay="1">
						<?=$severity['name']?>
					</a>
				</td>
				<td class="actions">
					<a href="<?=routeUrl('admin_edit_severity', ['id' => $severity['id']])?>" data-overlay="1" class="btn btn-xs btn-warning">
						<span class="fa fa-edit"></span> <?=t('edit')?>
					</a>
					<a href="<?=routeUrl('admin_delete_severity', ['id' => $severity['id']])?>" data-confirm="<?=t('confirm.delete')?>" class="btn btn-xs btn-danger">
						<span class="fa fa-times"></span> <?=t('delete')?>
					</a>
				</td>
			</tr>
		<?php endforeach ?>
		</tbody>
	</table>
</div>
