<div class="admin-severities container">
    <h1 class="page-header"><?=$t('new_severity')?></h1>

    <form action="<?=Request::basePath('/admin/severities/new')?>" method="post" class="form-horizontal">
        <?=Errors::messagesFor($severity)?>
        <?=View::render('admin/severities/_form.phtml', ['severity' => $severity])?>
        <div class="form-actions">
            <?=Form::submit($t('create'), ['class' => 'btn btn-success'])?>
        </div>
    </form>
</div>
