<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="admin admin-severities content container">
	<h1 class="page-header"><?=t('new_severity')?></h1>

	<form action="<?=routeUrl('admin_create_severity')?>" method="post" class="form-horizontal">
		<?=View::render('admin/severities/_form.phtml', ['severity' => $severity])?>
		<div class="form-actions text-center">
			<button type="submit" class="btn btn-success"><?=t('create')?></button>
		</div>
	</form>
</div>
<?php $this->endSection(); ?>
