<div class="tabular box" id="question_<?php echo $id; ?>" style="margin-bottom: 10px;">
	<div class="group">
		<label for="<?php echo $id; ?>_question"><?php echo l('question'); ?></label>
		<textarea name="questions[<?php echo $id; ?>][question]" id="<?php echo $id; ?>_question"<?php echo iif(isset($errors[$id]['question']), ' class="error"') ?>><?php echo $question['question']; ?></textarea>
	</div>
	<div class="group">
		<label for="<?php echo $id; ?>_answer"><?php echo l('answers'); ?></label>
		<input type="text" name="questions[<?php echo $id; ?>][answers]" id="<?php echo $id; ?>_answer" value="<?php echo $question['answers']; ?>"<?php echo iif(isset($errors[$id]['answers']), ' class="error"') ?> /> <abbr title="<?php echo l('help.security_questions.answers'); ?>">?</abbr>
	</div>
	<div class="group">
		<input type="button" onclick="$('#question_<?php echo $id; ?>').slideUp('fast', function(){ $(this).remove() })" value="<?php echo l('delete'); ?>" />
	</div>
</div>