<h3><?= l('new_milestone'); ?></h3>
<form action="<?= Request::requestUri(); ?>" method="post">
	<?php echo show_errors($milestone->errors); ?>
	<div class="tabular box">
		<?= view('project_settings/milestones/_form.phtml', ['milestone' => $milestone]); ?>
	</div>
	<div class="actions">
		<input type="submit" value="<?= l('create'); ?>" />
		<input type="button" value="<?= l('cancel'); ?>" onclick="close_overlay();" />
	</div>
</form>
