<?php extendView('layouts/default.phtml'); ?>

<div class="content">
	<h2 class="page-title"><?= l('project_settings'); ?></h2>
</div>
<?= view('project_settings/_nav.phtml'); ?>
<div class="content">
	<h3><?= l('new_milestone'); ?></h3>
	<form action="<?= Request::requestUri(); ?>" method="post">
		<?= show_errors($milestone->errors); ?>
		<div class="tabular box">
			<?= view('project_settings/milestones/_form.phtml', ['milestone' => $milestone]); ?>
		</div>
		<div class="actions">
			<input type="submit" value="<?= l('create'); ?>" />
		</div>
	</form>
</div>
