<?php extendView('layouts/admin.phtml'); ?>

<div class="content">
	<?= HTML::link(l('new_project'), '/admin/projects/new', ['class' => 'btn-success', 'icon' => 'fas fa-fw fa-plus']) ?>
</div>
<div>
	<table class="admin projects list">
		<thead>
			<th class="fixed_name"><?= l('name') ?></th>
			<th class="codename"><?= l('codename') ?></th>
			<th class="actions text-right"><?= l('actions') ?></th>
		</thead>
		<tbody>
			<?php foreach ($projects as $project) : ?>
				<tr>
					<td><?= HTML::link($project->name, "/{$project->slug}/settings") ?></td>
					<td><?= $project->codename ?></td>
					<td>
						<div class="btn-group justify-end">
							<?= HTML::link(l('edit'), "/{$project->slug}/settings", ['class' => 'btn-warning btn-sm', 'icon' => 'fas fa-fw fa-pencil', 'sr-only' => true]) ?>
							<a href="/admin/projects/<?= $project->id ?>/delete" class="btn-danger btn-sm"
								x-data="popoverConfirm({ position: 'center' , message: '<?= l('confirm.delete') ?>', post: true })"
								@click.prevent="toggle()">
								<i class="fas fa-fw fa-trash"></i>
								<span class="sr-only"><?= l('delete') ?></span>
							</a>

						</div>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
