<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'edit-type-modal');
$this->startSection('modal-size', 'modal-lg');
$this->startSection('modal-title', t('edit_type'));
$this->startSection('modal-primary-btn-txt', t('save'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('admin_save_type')?>" method="post" class="form-horizontal">
<input type="hidden" name="_method" value="put">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('admin/types/_form.phtml', ['type' => $type])?>
<?php $this->endSection(); ?>
