<div class="admin-statuses container">
	<h1 class="page-header"><?=$t('edit_type')?></h1>

	<form action="<?=Request::basePath($route('edit_admin_type', ['id' => $type->id]))?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($type)?>
		<?=View::render('admin/types/_form.phtml', ['type' => $type])?>
		<div class="form-actions">
			<?=Form::submit($t('save'), ['class' => 'btn btn-success'])?>
		</div>
	</form>
</div>
