<div class="modal fade">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form action="<?=routeUrl('admin_save_type', ['id' => $type->id])?>" method="post" class="form-horizontal">
				<?=TWBS::modalHeader(t('edit_type'))?>
				<div class="modal-body">
					<?=View::render('admin/types/_form.phtml', ['type' => $type])?>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-success"><?=t('save')?></button>
					<button type="button" class="btn btn-default" data-dismiss="modal"><?=t('cancel')?></button>
				</div>
			</form>
		</div>
	</div>
</div>
