<div class="admin-statuses container">
	<h1 class="page-header"><?=$t('new_type')?></h1>

	<form action="<?=Request::basePath($route('new_admin_type'))?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($type)?>
		<?=View::render('admin/types/_form.phtml', ['type' => $type])?>
		<div class="form-actions">
			<?=Form::submit($t('create'), ['class' => 'btn btn-success'])?>
		</div>
	</form>
</div>
