<?php form('/step/2'); ?>
	<?php if (isset($error)) { ?>
	<div class="error">
		Invalid username and/or password.
	</div>
	<?php } ?>
	<div class="tabular">
		<div class="group">
			<label for="username">Username</label>
			<input type="text" name="username" id="username" value="<?php echo isset($_POST['username']) ? $_POST['username'] : ''; ?>" />
		</div>
		<div class="group">
			<label for="password">Password</label>
			<input type="password" name="password" id="password" value="" />
		</div>
		<div class="group">
			<input type="submit" value="Login" />
		</div>
	</div>
</form>
