<div
	x-data="{
		sort: '<?= $sort ?>',
		order: '<?= $order ?>',
		updateUrl() {
			const newSearch = `?sort=${this.sort}.${this.order}`;
			window.location.search = newSearch;
		}
	}"
	class="mb-4 flex shadow-sm rounded-md">
	<select
		x-model="sort"
		@change="updateUrl()"
		name="sort"
		id="sort"
		class="block w-full border-gray-300 rounded-r-none rounded-l-md pl-3 pr-10 py-2 sm:text-sm">
		<option value="display_order"><?= l('sort_by_x', l('display_order')) ?></option>
		<option value="due"><?= l('sort_by_x', l('due')) ?></option>
		<option value="name"><?= l('sort_by_x', l('name')) ?></option>
	</select>

	<button
		type="button"
		@click="order = (order === 'ASC') ? 'DESC' : 'ASC'; updateUrl()"
		class="relative -ml-px inline-flex items-center rounded-l-none rounded-r-md border px-4 py-2 text-sm font-medium ">
		<span x-show="order === 'ASC'" class="m-0">
			<svg class="h-5 w-5 text-gray-600" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640">
				<path d="M297.4 169.4C309.9 156.9 330.2 156.9 342.7 169.4L534.7 361.4C547.2 373.9 547.2 394.2 534.7 406.7C522.2 419.2 501.9 419.2 489.4 406.7L320 237.3L150.6 406.6C138.1 419.1 117.8 419.1 105.3 406.6C92.8 394.1 92.8 373.8 105.3 361.3L297.3 169.3z" />
			</svg>
		</span>
		<span x-show="order === 'DESC'" class="m-0">
			<svg class="h-5 w-5 text-gray-600" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640">
				<path d="M297.4 470.6C309.9 483.1 330.2 483.1 342.7 470.6L534.7 278.6C547.2 266.1 547.2 245.8 534.7 233.3C522.2 220.8 501.9 220.8 489.4 233.3L320 402.7L150.6 233.4C138.1 220.9 117.8 220.9 105.3 233.4C92.8 245.9 92.8 266.2 105.3 278.7L297.3 470.7z" />
			</svg>
		</span>
	</button>
</div>
