<?php extendView('layouts/default.phtml'); ?>

<div class="roadmap content">
	<div class="flex">
		<h2 class="page-title flex-grow"><?= l('roadmap') ?></h2>
		<div class="flex items-center gap-4">
			<?= View::render('projects/_roadmap_sort', ['sort' => $sort, 'order' => $order]) ?>
			<div class="btn-pill-group mt-2">
				<a href="<?= Request::base($project->href('roadmap')) ?>" class="<?= active_nav('/:slug/roadmap') ? 'active' : '' ?>"><?= l('active') ?></a>
				<a href="<?= Request::base($project->href('roadmap/completed')) ?>" class="<?= active_nav('/:slug/roadmap/completed') ? 'active' : '' ?>"><?= l('completed') ?></a>
				<a href="<?= Request::base($project->href('roadmap/all')) ?>" class="<?= active_nav('/:slug/roadmap/all') ? 'active' : '' ?>"><?= l('all') ?></a>
			</div>
		</div>
	</div>

	<?php foreach ($milestones as $milestone) : ?>
		<div class="milestone">
			<h3 class="milestone-name">
				<a href="<?= Request::base($milestone->href()) ?>">
					<span><?= $milestone->name ?></span>
					<?php if ($milestone->codename) : ?>
						<em>"<?= $milestone->codename ?>"</em>
					<?php endif; ?>
				</a>
			</h3>

			<div class="milestone-meta">
				<?php if ($milestone->due > 0 and $milestone->status == 1) : ?>
					<span class="due">
						<em><?= l('due_x', time_from_now_ago($milestone->due)) ?></em>
					</span>
				<?php endif; ?>
			</div>

			<?= View::render('milestones/_progress', ['milestone' => $milestone]) ?>

			<div class="milestone-info">
				<?= format_text($milestone->info) ?>
			</div>
		</div>
	<?php endforeach; ?>
</div>
