<title><?php echo implode(' - ', array_reverse($traq->title)); ?></title>
<meta charset="UTF-8" />

<script src="https://code.jquery.com/jquery-1.11.0.min.js" type="text/javascript"></script>
<script src="https://code.jquery.com/ui/1.10.4/jquery-ui.min.js" type="text/javascript"></script>
<script src="<?= Request::base('assets/js/sexytooltips.js') ?>" type="text/javascript"></script>
<script src="<?= Request::base('assets/js/popover.js') ?>" type="text/javascript"></script>
<script src="<?= Request::base('assets/js/ticket_tasks.js') ?>" type="text/javascript"></script>

<script src="<?= Request::base('assets/js/traq.js') ?>" type="text/javascript"></script>

<script src="<?= Request::base('_js') ?>" type="text/javascript"></script>
<?= ui_package('src/assets/main.ts') ?>

<?php if (isset($project)) : ?>
	<script>
		window.traq.project_slug = <?php echo json_encode($project->slug); ?>
	</script>
<?php endif; ?>

<?php FishHook::run('template:layouts/global/head'); ?>
<?php foreach ($app->feeds as $feed) { ?>
	<link type="application/atom+xml" rel="alternate" href="<?php echo $feed[0]; ?>">
<?php } ?>
