<nav id="wiki-nav" class="container">
	<ul class="nav nav-tabs" role="tablist">
		<li<?=Request::matches('/{pslug}/wiki') ? ' class="active"' :''?>>
			<a href="<?=routeUrl('wiki')?>"><?=t('home')?></a>
		</li>
		<li<?=Request::matches('/{pslug}/wiki/_pages') ? ' class="active"' :''?>>
			<a href="<?=routeUrl('wiki_pages')?>"><?=t('pages')?></a>
		</li>

		<?php if (isset($page) && $page) : ?>
			<li><a href="<?=routeUrl('wiki_revisions', ['slug' => $page['slug']])?>">
				<span class="fa fa-files-o"></span> <?=t('revisions')?>
			</a></li>
		<?php endif ?>
	</ul>
</nav>
