<nav id="wiki-nav" class="container">
	<ul class="nav nav-tabs" role="tablist">
		<li<?=Request::matches('/{pslug}/wiki') ? ' class="active"' :''?>>
			<a href="<?=routeUrl('wiki')?>"><?=t('home')?></a>
		</li>
		<li<?=Request::matches('/{pslug}/wiki/_pages') ? ' class="active"' :''?>>
			<a href="<?=routeUrl('wiki_pages')?>"><?=t('pages')?></a>
		</li>

		<?php if (has_permission('create_wiki_page')) : ?>
			<li<?=Request::matches('/{pslug}/wiki/_new') ? ' class="active"' :''?>>
				<a href="<?=routeUrl('wiki_new')?>"><span class="fa fa-plus"></span> <?=t('new_page')?></a>
			</li>
		<?php endif ?>
		<?php if (isset($page) && $page && has_permission('edit_wiki_page')) : ?>
			<li<?=Request::matches('/{pslug}/wiki/{slug}/_edit') ? ' class="active"' :''?>>
				<a href="<?=routeUrl('wiki_edit', ['slug' => $page['slug']])?>">
					<span class="fa fa-pencil"></span> <?=t('edit_page')?>
				</a>
			</li>
		<?php endif ?>
		<?php if (isset($page) && $page && has_permission('delete_wiki_page')) : ?>
			<li>
				<a href="<?=routeUrl('wiki_delete', ['slug' => $page['slug']])?>" data-confirm="<?=t('confirm.delete')?>">
					<span class="fa fa-trash"></span> <?=t('delete_page')?>
				</a>
			</li>
		<?php endif ?>
		<?php if (isset($page) && $page) : ?>
			<li<?=Request::matches('/{pslug}/wiki/{slug}/_revisions(/[0-9]+)?') ? ' class="active"' :''?>>
				<a href="<?=routeUrl('wiki_revisions', ['slug' => $page['slug']])?>">
					<span class="fa fa-files-o"></span> <?=t('revisions')?>
				</a>
			</li>
		<?php endif ?>
	</ul>
</nav>
