<?=View::render('wiki/_nav.phtml')?>
<div class="new-wiki-page container">
    <h1 class="page-header"><?=t('new_page')?></h1>

    <?=Errors::messagesFor($page)?>

    <form action="<?=routeUrl('wiki_create')?>" method="post" class="form-horizontal">
        <?=View::render('wiki/_form.phtml', ['page' => $page])?>

        <div class="form-actions">
            <?=Form::submit(t('create'), ['class' => 'btn btn-success'])?>
        </div>
    </form>
</div>
