<?php $this->extend('layouts/default.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="wiki wiki-pages content container">
    <?=View::render('wiki/_nav.phtml')?>

    <h1 class="page-header"><?=t('pages')?></h1>

    <ul>
    <?php foreach ($pages as $page) : ?>
        <li><a href="<?=routeUrl('wiki_page', ['slug' => $page['slug']])?>"><?=e($page['title'])?></a></li>
    <?php endforeach ?>
    </ul>
</div>
<?php $this->endSection(); ?>
