<?php $this->extend('layouts/default.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="wiki wiki-revisions content container">
    <?=View::render('wiki/_nav.phtml', ['page' => $page])?>

    <h1 class="page-header"><?=t('revisions_for_x', [$page['title']])?></h1>

    <ul>
    <?php foreach ($revisions as $revision) : ?>
        <li>
            <?=t('x_by_x', [
                HTML::link(
                    t('revision_x', $revision['revision']),
                    routePath('wiki_revision', ['slug' => $page['slug'], 'id' => $revision['revision']])
                ),
                gravatarProfileLink($revision['user_email'], $revision['user_name'], $revision['user_id'], 15),
            ])?>
        </li>
    <?php endforeach ?>
    </ul>
</div>
<?php $this->endSection(); ?>
