<tr id="filter-<?=$name?>">
	<td class="filter-name"><?=t($name)?></td>
	<td class="filter-condition">
		<?=Form::select("filters[{$name}][prefix]", TicketFilters::isIsNotSelectOptions(), [
			'value' => $filter['cond'] ? '' : '!',
			'id'	=> false,
			'class' => 'form-control'
		])?>
	</td>
	<td class="filter-value">
		<?=Form::select("filters[{$name}][values][]", TicketFilters::selectOptionsFor($name, raw($currentProject)), [
			'value'	=> $filter['values'],
			'multiple' => true,
			'class'	=> 'form-control'
		])?>
	</td>
	<td class="filter-actions">
		<a href="#" class="btn btn-sm btn-danger remove-filter" data-filter="<?=$name?>">-</a>
	</td>
</tr>
