<form action="<?=routeUrl('tickets_set_columns')?>?<?=Request::queryString()?>" method="post">
	<fieldset id="ticketlist-columns">
		<legend><a href="#" id="ticketlist-columns-toggle"><?=t('columns')?></a></legend>

		<div id="ticketlist-columns-content">
			<div class="row">
			<?php foreach (Ticketlist::allowedColumns() as $column) : ?>
				<div class="col-md-2">
					<?=Form::checkbox("columns[{$column}]", $column, ['checked' => in_array($column, $columns)])?>
					<?=Form::label(Ticketlist::headerFor($column), "columns[{$column}]")?>
				</div>
			<?php endforeach ?>
			<?php foreach ($customFields as $column) : ?>
				<div class="col-md-2">
					<?php echo Form::checkbox("columns[{$column->id}]", $column->id, ['checked' => in_array($column->name, $columns)])?>
					<?php echo Form::label($column->name, "columns[{$column->id}]")?>
				</div>
			<?php endforeach ?>
			</div>

			<div class="actions">
				<?=Form::submit(t('update'), ['name' => 'update_columns', 'class' => 'btn btn-default'])?>
			</div>
		</div>
	</fieldset>
</form>
