<form action="<?=routeUrl('tickets_set_filters')?>" method="post">
    <fieldset id="ticket-filters">
        <legend><a href="#" id="ticket-filters-toggle"><?=t('filters')?></a></legend>

        <div id="ticket-filters-content">
            <table class="table table-striped">
                <tbody>
                <?php foreach ($filters as $filterName => $filter) : ?>
                    <?php if (in_array($filterName, ['milestone', 'status', 'version', 'type', 'component', 'priority', 'severity'])) : ?>
                        <?=View::render('ticket_listing/filters/multiselect.phtml', [
                            'name'    => $filterName,
                            'filter'  => $filter
                        ])?>
                    <?php elseif (in_array($filterName, ['summary', 'description'])) : ?>
                        <?=View::render('ticket_listing/filters/contains.phtml', [
                            'name'    => $filterName,
                            'filter'  => $filter
                        ])?>
                    <?php elseif (in_array($filterName, ['owner', 'assigned_to'])) : ?>
                        <?=View::render('ticket_listing/filters/is_is_not.phtml', [
                            'name'    => $filterName,
                            'filter'  => $filter
                        ])?>
                    <?php endif ?>
                <?php endforeach ?>
                </tbody>
            </table>
            <div class="actions">
                <div class="row">
                    <div class="col-sm-3 col-sm-offset-8">
                        <div class="input-group input-group-sm">
                            <?=Form::select('new_filter', TicketFilters::selectOptions(currentProject()), ['class' => 'form-control'])?>
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-success btn-filter-add">+</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-1">
                        <?=Form::submit(t('update'), ['class' => 'btn btn-sm btn-success'])?>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
</form>
