<div class="tickets container">
	<h1 class="page-header"><?=t('tickets')?></h1>

	<?php require __DIR__ . '/_columns.phtml'; ?>

	<table class="table table-striped table-hover">
		<thead>
			<tr>
		<?php foreach ($columns as $column) : ?>
			<th>
				<?=Ticketlist::headerFor($column)?>
			</th>
		<?php endforeach ?>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($tickets as $ticket) : ?>
			<tr>
			<?php foreach ($columns as $column) : ?>
				<?php if ($column == 'summary') : ?>
					<td>
						<a href="<?=routeUrl('ticket', ['id' => $ticket['ticket_id']])?>"><?=e($ticket['summary'])?></a>
					</td>
				<?php elseif ($column == 'owner') : ?>
					<td>
						<a href="<?=routeUrl('user', ['id' => $ticket['user_id']])?>">
							<?=$ticket['user_name']?>
						</a>
					</td>
				<?php elseif ($column == 'milestone') : ?>
					<td>
						<a href="<?=routeUrl('milestone', ['mslug' => $ticket['milestone_slug']])?>">
							<?=$ticket['milestone_name']?>
						</a>
					</td>
				<?php elseif ($column == 'version') : ?>
					<td>
					<?php if ($ticket['version_id']) : ?>
						<a href="<?=routeUrl('milestone', ['mslug' => $ticket['version_slug']])?>">
							<?=$ticket['version_name']?>
						</a>
					<?php endif; ?>
					</td>
				<?php elseif ($column == 'assigned_to') : ?>
					<td>
					<?php if ($ticket['assigned_to_id']) : ?>
						<a href="<?=routeUrl('user', ['id' => $ticket['assigned_to_id']])?>"><?=$ticket['assigned_to_name']?></a>
					<?php endif; ?>
					</td>
				<?php elseif ($column == 'created_at') : ?>
					<td data-moment="<?=$ticket['created_at']?>"><?=$ticket['created_at']?></td>
				<?php elseif ($column == 'updated_at') : ?>
					<td data-moment="<?=$ticket['updated_at']?>"><?=$ticket['updated_at']?></td>
				<?php else : ?>
					<td><?=Ticketlist::dataFor($column, $ticket)?></td>
				<?php endif ?>
			<?php endforeach ?>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>

	<?=View::render('layouts/_pagination.phtml', ['pagination' => $pagination])?>
</div>
