<?php $multiSelectFilter = function ($name, $filter) use ($t, $project) { ?>
<tr id="filter-<?=$name?>">
	<td class="filter-name"><?=$t($name)?></td>
	<td class="filter-condition">
		<?=Form::select("filters[{$name}][prefix]", TicketFilters::isIsNotSelectOptions(), [
			'value' => $filter['prefix'],
			'id'    => false,
			'class' => 'form-control'
		])?>
	</td>
	<td class="filter-value">
		<?=Form::select("filters[{$name}][values][]", TicketFilters::selectOptionsFor($name, $project), [
			'value'    => $filter['values'],
			'multiple' => true,
			'class'    => 'form-control'
		])?>
	</td>
	<td class="filter-actions">
		<button class="btn btn-sm btn-danger" class="remove-filter" data-filter="<?=$name?>">-</button>
	</td>
</tr>
<?php } ?>
<?php $containsFilter = function ($name, $filter) use ($t, $project) { ?>
	<?php foreach ($filter['values'] as $key => $value): ?>
	<tr id="filter-<?=$name?>-<?=$key?>">
		<td class="filter-name"><?=($key === 0 ? $t($name) : '')?></td>
		<td class="filter-condition">
		<?php if ($key === 0): ?>
			<?=Form::select("filters[{$name}][prefix]", TicketFilters::containsFilterSelectOptions(), [
				'value' => $filter['prefix'],
				'id'    => false,
				'class' => 'form-control'
			])?>
		<?php else: ?>
			<?=$t('or')?>
		<?php endif; ?>
		</td>
		<td class="filter-value">
			<?=Form::text("filters[{$name}][values][]", [
				'value' => $filter['values'][$key],
				'class' => 'form-control'
			])?>
		</td>
		<td class="filter-actions">
			<button class="btn btn-sm btn-danger" class="remove-filter" data-filter="<?=$name?>-<?=$key?>">-</button>
		</td>
	</tr>
	<?php endforeach; ?>
<?php } ?>
<?php $isIsNotFilter = function ($name, $filter) use ($t, $project) { ?>
	<?php foreach ($filter['values'] as $key => $value): ?>
	<tr id="filter-<?=$name?>-<?=$key?>">
		<td class="filter-name"><?=($key === 0 ? $t($name) : '')?></td>
		<td class="filter-condition">
		<?php if ($key === 0): ?>
			<?=Form::select("filters[{$name}][prefix]", TicketFilters::isIsNotSelectOptions(), [
				'value' => $filter['prefix'],
				'id'    => false,
				'class' => 'form-control'
			])?>
		<?php else: ?>
			<?=$t('or')?>
		<?php endif; ?>
		</td>
		<td class="filter-value">
			<?=Form::text("filters[{$name}][values][]", [
				'value' => $filter['values'][$key],
				'class' => 'form-control'
			])?>
		</td>
		<td class="filter-actions">
			<button class="btn btn-sm btn-danger" class="remove-filter" data-filter="<?=$name?>-<?=$key?>">-</button>
		</td>
	</tr>
	<?php endforeach; ?>
<?php } ?>
<form action="<?=Request::basePath($project->href('issues/update-filters'))?>" method="post">
	<fieldset id="ticket-filters">
		<legend><a href="#"><?=$t('filters')?></a></legend>

		<div id="ticket-filters-content">
			<table class="table table-striped">
				<tbody>
				<?php foreach ($filters as $filterName => $filter): ?>
					<?php if (in_array($filterName, ['milestone', 'status', 'version', 'type', 'component', 'priority', 'severity'])): ?>
						<?=$multiSelectFilter($filterName, $filter)?>
					<?php elseif(in_array($filterName, ['summary', 'description'])): ?>
						<?=$containsFilter($filterName, $filter)?>
					<?php elseif(in_array($filterName, ['owner', 'assigned_to'])): ?>
						<?=$isIsNotFilter($filterName, $filter)?>
					<?php endif; ?>
				<?php endforeach; ?>
				</tbody>
			</table>
			<div class="actions">
				<div class="row">
					<div class="col-sm-3 col-sm-offset-8">
						<div class="input-group input-group-sm">
							<?=Form::select('new_filter', TicketFilters::selectOptions($project), ['class' => 'form-control'])?>
							<div class="input-group-btn">
								<button type="submit" class="btn btn-success btn-filter-add">+</button>
							</div>
						</div>
					</div>
					<div class="col-sm-1">
						<?=Form::submit($t('update'), ['class' => 'btn btn-sm btn-success'])?>
					</div>
				</div>
			</div>
		</div>
	</fieldset>
</form>
