<div class="form-group">
    <?=Form::label($t('type'), 'type', ['class' => 'control-label col-md-3'])?>
    <div class="col-md-9">
        <?=Form::select('type', $typeSelectOptions, [
            'value' => $ticket->type_id,
            'class' => "form-control"
        ])?>
    </div>
</div>

<div class="form-group">
    <?=Form::label($t('summary'), 'summary', ['class' => 'control-label col-md-3'])?>
    <div class="col-md-9">
        <?=Form::text('summary', [
            'value' => $ticket->type_id,
            'class' => "form-control"
        ])?>
    </div>
</div>

<div class="form-group">
    <?=Form::label($t('description'), 'description', ['class' => 'control-label col-md-3'])?>
    <div class="col-md-9">
        <?=Form::textarea('description', [
            'value' => $ticket->body,
            'class' => "form-control"
        ])?>
    </div>
</div>

<div class="form-group">
    <?=Form::label($t('status'), 'status', ['class' => 'control-label col-md-3'])?>
    <div class="col-md-9">
        <?=Form::select('status', $statusSelectOptions, [
            'value' => $ticket->assigned_to_id,
            'class' => "form-control"
        ])?>
    </div>
</div>

<div class="form-group">
    <?=Form::label($t('assigned_to'), 'assigned_to', ['class' => 'control-label col-md-3'])?>
    <div class="col-md-9">
        <?=Form::select('assigned_to', array_merge([['label' => '', 'value' => '']], $project->memberSelectOptions()), [
            'value' => $ticket->assigned_to_id,
            'class' => "form-control"
        ])?>
    </div>
</div>

<div class="form-group">
    <?=Form::label($t('milestone'), 'milestone', ['class' => 'control-label col-md-3'])?>
    <div class="col-md-9">
        <?=Form::select('milestone', $project->milestoneSelectOptions('open'), [
            'value' => $ticket->type_id,
            'class' => "form-control"
        ])?>
    </div>
</div>

<div class="form-group">
    <?=Form::label($t('version'), 'version', ['class' => 'control-label col-md-3'])?>
    <div class="col-md-9">
        <?=Form::select('version', array_merge([['label' => '', 'value' => '']], $project->milestoneSelectOptions('closed', 'DESC')), [
            'value' => $ticket->type_id,
            'class' => "form-control"
        ])?>
    </div>
</div>

<div class="form-group">
    <?=Form::label($t('component'), 'component', ['class' => 'control-label col-md-3'])?>
    <div class="col-md-9">
        <?=Form::select('component', array_merge([['label' => '', 'value' => '']], $project->componentSelectOptions()), [
            'value' => $ticket->type_id,
            'class' => "form-control"
        ])?>
    </div>
</div>
