<div class="form-group">
	<?=Form::label(t('type'), 'type_id', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::select('type_id', Traq\Models\Type::selectOptions(), [
			'value' => $ticket->type_id,
			'class' => "form-control"
		])?>
	</div>
</div>

<div class="form-group">
	<?=Form::label(t('summary'), 'summary', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::text('summary', [
			'value' => $ticket->summary,
			'class' => "form-control"
		])?>
	</div>
</div>

<div class="form-group">
	<?=Form::label(t('description'), 'description', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::textarea('info', [
			'value' => $ticket->info,
			'class' => "form-control"
		])?>
	</div>
</div>

<?php if (has_permission($currentProject['id'], 'ticket_properties_set_status')) : ?>
<div class="form-group">
	<?=Form::label(t('status'), 'status_id', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::select('status_id', Traq\Models\Status::selectOptions(), [
            'value' => $ticket->status_id,
            'class' => "form-control"
        ])?>
	</div>
</div>
<?php endif ?>

<?php if (has_permission($currentProject['id'], 'ticket_properties_set_assigned_to')) : ?>
<div class="form-group">
	<?=Form::label(t('assigned_to'), 'assigned_to_id', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::select('assigned_to_id', array_merge([['label' => t('no_one'), 'value' => 0]], $currentProject->memberSelectOptions()), [
            'value' => $ticket->assigned_to_id,
            'class' => "form-control"
        ])?>
	</div>
</div>
<?php endif ?>

<?php if (has_permission($currentProject['id'], 'ticket_properties_set_milestone')) : ?>
<div class="form-group">
	<?=Form::label(t('milestone'), 'milestone_id', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::select('milestone_id', $currentProject->milestoneSelectOptions('id', 1), [
            'value' => $ticket->milestone_id,
            'class' => "form-control"
        ])?>
	</div>
</div>
<?php endif ?>

<?php if (has_permission($currentProject['id'], 'ticket_properties_set_version')) : ?>
<div class="form-group">
	<?=Form::label(t('version'), 'version_id', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::select('version_id', array_merge([['label' => t('none'), 'value' => 0]], $currentProject->milestoneSelectOptions('id', 2, 'DESC')), [
            'value' => $ticket->version_id,
            'class' => "form-control"
        ])?>
	</div>
</div>
<?php endif ?>

<?php if (has_permission($currentProject['id'], 'ticket_properties_set_component')) : ?>
<div class="form-group">
	<?=Form::label(t('component'), 'component_id', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::select('component_id', array_merge([['label' => t('none'), 'value' => 0]], $currentProject->componentSelectOptions()), [
            'value' => $ticket->component_id,
            'class' => "form-control"
        ])?>
	</div>
</div>
<?php endif ?>

<?php if (has_permission($currentProject['id'], 'ticket_properties_set_severity')) : ?>
<div class="form-group">
	<?=Form::label(t('severity'), 'severity_id', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::select('severity_id', Traq\Models\Severity::selectOptions(), [
            'value' => $ticket->severity_id,
            'class' => "form-control"
        ])?>
	</div>
</div>
<?php endif ?>

<?php if (has_permission($currentProject['id'], 'ticket_properties_set_priority')) : ?>
<div class="form-group">
    <?=Form::label(t('priority'), 'priority_id', ['class' => 'control-label col-md-3'])?>
    <div class="col-md-9">
        <?=Form::select('priority_id', Traq\Models\Priority::selectOptions(), [
            'value' => $ticket->priority_id,
            'class' => "form-control"
        ])?>
    </div>
</div>
<?php endif ?>
