<div class="modal fade">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form action="<?=routeUrl('ticket_save_description', ['pslug' => $currentProject['slug'], 'id' => $ticket['ticket_id']])?>" method="post" class="form-horizontal">
				<?=TWBS::modalHeader(t('edit_ticket_description'))?>
				<div class="modal-body">
					<textarea name="body" class="form-control" required><?=e($ticket['body'])?></textarea>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-success"><?=t('save')?></button>
					<button type="button" class="btn btn-default" data-dismiss="modal"><?=t('cancel')?></button>
				</div>
			</form>
		</div>
	</div>
</div>
