<div class="tickets container">
	<h1 class="page-header"><?=$t('tickets')?></h1>

	<?php //View::render('tickets/_filters.phtml')?>
	<?php //View::render('tickets/_columns.phtml')?>

	<table id="tickets" class="table table-striped table-hover table-bordered">
		<thead>
			<tr>
			<?php if($currentUser->permission($project->id, 'perform_mass_actions')): ?>
				<th class="mass-actions"><?=Form::checkbox('all_tickets', 1, ['id' => "select-all-tickets"])?></th>
			<?php endif; ?>
			<?php foreach ($columns as $column): ?>
				<th>
					<a href="<?=Ticketlist::sortUrlFor($column)?>"><?=Ticketlist::headerFor($column)?></a>
				</th>
			<?php endforeach; ?>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($tickets as $ticket): ?>
			<tr>
				<td class="mass-actions">
					<?=Form::checkbox('tickets[]', $ticket->ticket_id, ['id' => "mass-action-ticket-{$ticket->ticket_id}"])?>
				</td>
			<?php foreach ($columns as $column): ?>
				<td><?=Ticketlist::dataFor($column, $ticket)?></td>
			<?php endforeach; ?>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>

	<?php //View::render('tickets/_mass_actions')?>

	<?=View::render('layouts/_pagination.phtml', ['pagination' => $pagination])?>
</div>
