<div class="tickets container">
	<h1 class="page-header"><?=t('tickets')?></h1>

	<table class="table table-striped table-hover">
		<thead>
			<tr>
		<?php foreach ($columns as $column) : ?>
			<?php if ($column == 'ticket_id') : ?>
				<th><?=t('id')?></th>
			<?php elseif ($column == 'summary') : ?>
				<th><?=t('summary')?></th>
			<?php elseif ($column == 'owner') : ?>
				<th><?=t('owner')?></th>
			<?php elseif ($column == 'type') : ?>
				<th><?=t('type')?></th>
			<?php elseif ($column == 'status') : ?>
				<th><?=t('status')?></th>
			<?php elseif ($column == 'milestone') : ?>
				<th><?=t('milestone')?></th>
			<?php elseif ($column == 'version') : ?>
				<th><?=t('version')?></th>
			<?php elseif ($column == 'component') : ?>
				<th><?=t('component')?></th>
			<?php elseif ($column == 'priority') : ?>
				<th><?=t('priority')?></th>
			<?php elseif ($column == 'severity') : ?>
				<th><?=t('severity')?></th>
			<?php elseif ($column == 'assigned_to') : ?>
				<th><?=t('assigned_to')?></th>
			<?php elseif ($column == 'votes') : ?>
				<th><?=t('votes')?></th>
			<?php elseif ($column == 'created_at') : ?>
				<th><?=t('created_at')?></th>
			<?php elseif ($column == 'updated_at') : ?>
				<th><?=t('updated_at')?></th>
			<?php endif ?>
		<?php endforeach ?>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($tickets as $ticket) : ?>
			<tr>
			<?php foreach ($columns as $column) : ?>
				<?php if ($column == 'ticket_id') : ?>
					<td><?=$ticket['ticket_id']?></td>
				<?php elseif ($column == 'summary') : ?>
					<td>
						<a href="<?=routeUrl('ticket', ['id' => $ticket['ticket_id']])?>"><?=e($ticket['summary'])?></a>
					</td>
				<?php elseif ($column == 'owner') : ?>
					<td>
						<a href="<?=routeUrl('user', ['id' => $ticket['user_id']])?>">
							<?=$ticket['user_name']?>
						</a>
					</td>
				<?php elseif ($column == 'type') : ?>
					<td><?=$ticket['type_name']?></td>
				<?php elseif ($column == 'status') : ?>
					<td><?=$ticket['status_name']?></td>
				<?php elseif ($column == 'milestone') : ?>
					<td>
						<a href="<?=routeUrl('milestone', ['mslug' => $ticket['milestone_slug']])?>">
							<?=$ticket['milestone_name']?>
						</a>
					</td>
				<?php elseif ($column == 'version') : ?>
					<td>
					<?php if ($ticket['version_id']) : ?>
						<a href="<?=routeUrl('milestone', ['mslug' => $ticket['version_slug']])?>">
							<?=$ticket['version_name']?>
						</a>
					<?php endif; ?>
					</td>
				<?php elseif ($column == 'component') : ?>
					<td>
					<?php if ($ticket['component_id']) : ?>
						<?=$ticket['component_name']?>
					<?php endif; ?>
					</td>
				<?php elseif ($column == 'priority') : ?>
					<td><?=$ticket['priority_name']?></td>
				<?php elseif ($column == 'severity') : ?>
					<td><?=$ticket['severity_name']?></td>
				<?php elseif ($column == 'assigned_to') : ?>
					<td>
					<?php if ($ticket['assigned_to_id']) : ?>
						<a href="<?=routeUrl('user', ['id' => $ticket['assigned_to_id']])?>"><?=$ticket['assigned_to_name']?></a>
					<?php endif; ?>
					</td>
				<?php elseif ($column == 'votes') : ?>
					<td><?=$ticket['votes']?></td>
				<?php elseif ($column == 'created_at') : ?>
					<td data-moment="<?=$ticket['created_at']?>"><?=$ticket['created_at']?></td>
				<?php elseif ($column == 'updated_at') : ?>
					<td data-moment="<?=$ticket['updated_at']?>"><?=$ticket['updated_at']?></td>
				<?php endif ?>
			<?php endforeach ?>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>

	<?=View::render('layouts/_pagination.phtml', ['pagination' => $pagination])?>
</div>
