<div class="new-ticket container">
	<h1 class="page-header"><?=t('new_ticket')?></h1>

	<?=Errors::messagesFor($ticket)?>

	<form action="<?=routeUrl('create_ticket', ['pslug' => $currentProject['slug']])?>" method="post" class="form-horizontal">
		<?=View::render('tickets/_form.phtml', ['ticket' => $ticket])?>
		<div class="form-actions">
			<?=Form::submit(t('create_ticket'), ['class' => 'btn btn-success'])?>
		</div>
	</form>
</div>
