<?php $this->extend('layouts/default.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="new-ticket container">
	<h1 class="page-header"><?=t('new_ticket')?></h1>

	<form action="<?=routeUrl('create_ticket', ['pslug' => currentProject()['slug']])?>" method="post" class="form-horizontal">
		<?=View::render('tickets/_form.phtml', ['ticket' => $ticket])?>
		<div class="form-actions">
			<button type="submit" class="btn btn-success"><?=t('create_ticket')?></button>
		</div>
	</form>
</div>
<?php $this->endSection(); ?>
