<div class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form action="<?=Request::basePath($project->href('issues/new'))?>" method="post" class="form-horizontal">
                <?=TWBS::modalHeader($t('new_issue'))?>
                <div class="modal-body">
                    <?=View::render('tickets/_form.phtml', ['ticket' => $ticket])?>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success"><?=$t('create')?></button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?=$t('cancel')?></button>
                </div>
            </form>
        </div>
    </div>
</div>
