<div class="show-issue container">
	<div id="issue" class="well well-sm">
		<div class="issue-actions pull-right">

		</div>

		<h1 class="page-header"><?=t('ticket.page-header', $ticket['ticket_id'], $ticket['summary'])?></h1>

		<div class="issue-properties">
			<?=View::render('tickets/_properties.phtml', ['ticket' => $ticket])?>
		</div>

		<div class="issue-description">
			<?=Format::text($ticket['info'])?>
		</div>

		<div class="issue-attachments">

		</div>
	</div>

	<div class="ticket-history">
		<h2><?=t('history')?></h2>

		<?php foreach ($history as $update) : ?>
			<div class="ticket-update">
				<header>
					<span data-moment="<?=$update['created_at']?>"><?=$update['created_at']?></span>
					by <a href="<?=routeUrl('user', ['id' => $update['user_id']])?>"><?=$update['user_name']?></a>
				</header>
				<?php if (count($update['changes'])) : ?>
				<div class="ticket-update-changes">
					<?=$update['changes']?>
				</div>
				<?php endif ?>
				<?php if ($update['comment']) : ?>
				<div class="ticket-update-comment">
					<?=Format::text($update['comment'])?>
				</div>
				<?php endif ?>
			</div>
		<?php endforeach ?>
	</div>
</div>

