<div class="form-group <?=iif($milestone->hasError('name'), 'has-error')?>">
	<label for="name" class="control-label col-md-3"><?=t('name')?></label>
	<div class="col-md-9">
		<input type="text" name="name" id="name" class="form-control" value="<?=e($milestone['name'])?>">
		<?php if ($milestone->hasError('name')) : ?>
		<div class="help-block"><?=$milestone->getError('name')[0]?></div>
		<?php endif ?>
	</div>
</div>
<div class="form-group <?=iif($milestone->hasError('slug'), 'has-error')?>">
	<label for="slug" class="control-label col-md-3"><?=t('slug')?></label>
	<div class="col-md-9">
		<input type="text" name="slug" id="slug" class="form-control" value="<?=e($milestone['slug'])?>">
		<?php if ($milestone->hasError('slug')) : ?>
		<div class="help-block"><?=$milestone->getError('slug')[0]?></div>
		<?php endif ?>
	</div>
</div>
<div class="form-group">
	<label for="codename" class="control-label col-md-3"><?=t('codename')?></label>
	<div class="col-md-9">
		<input type="text" name="codename" id="codename" class="form-control" value="<?=e($milestone['codename'])?>">
	</div>
</div>
<div class="form-group">
	<label for="due_date" class="control-label col-md-3"><?=t('due_date')?></label>
	<div class="col-md-9">
		<input type="text" name="due" id="due_date" class="form-control" placeholder="YYYY-MM-DD HH:MM:SS" value="<?=e($milestone['due'])?>">
	</div>
</div>
<div class="form-group">
	<label for="status" class="control-label col-md-3"><?=t('status')?></label>
	<div class="col-md-9">
		<?=Form::select('status', Traq\Models\Milestone::statusSelectOptions(), [
			'value' => $milestone->isNew() ? 1 : $milestone->status,
			'class' => 'form-control'
		])?>
	</div>
</div>
<div class="form-group">
	<label for="description" class="control-label col-md-3"><?=t('description')?></label>
	<div class="col-md-9">
		<?=Form::textarea('info', ['value' => $milestone->info, 'class' => 'form-control rich-editor'])?>
	</div>
</div>
<div class="form-group">
	<label for="changelog" class="control-label col-md-3"><?=t('changelog')?></label>
	<div class="col-md-9">
		<textarea name="changelog" id="changelog" class="form-control"><?=e($milestone['changelog'])?></textarea>
	</div>
</div>
<div class="form-group">
	<label for="display_order" class="control-label col-md-3"><?=t('display_order')?></label>
	<div class="col-md-9">
		<input type="text" name="display_order" id="display_order" class="form-control" value="<?=e($milestone['display_order'])?>">
	</div>
</div>
