<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'edit-milestone-modal');
$this->startSection('modal-size', 'modal-lg');
$this->startSection('modal-title', t('edit_milestone'));
$this->startSection('modal-primary-btn-txt', t('save'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('project_settings_save_milestone')?>" method="post" class="form-horizontal">
<input type="hidden" name="_method" value="put">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('project_settings/milestones/_form.phtml', ['milestone' => $milestone])?>
<?php $this->endSection(); ?>
