<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'edit-group-modal');
$this->startSection('modal-size', 'modal-md');
$this->startSection('modal-title', t('edit_group'));
$this->startSection('modal-primary-btn-txt', t('save'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('admin_save_group')?>" method="post" class="form-horizontal">
<input type="hidden" name="_method" value="put">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('admin/groups/_form.phtml', ['group' => $group])?>
<?php $this->endSection(); ?>
