<div class="container">
	<style type="text/css">
		.license {
			font-family: monospace;
			max-height: 400px;
			overflow: auto;
		}
	</style>

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1 class="page-header">License Agreement</h1>

			<form action="<?=$installStep("database_info")?>" method="post">
					<pre class="license"><?=htmlentities($license)?></pre>
					<button class="btn btn-block btn-primary">Accept</button>
				</div>
			</form>
		</div>
	</div>
</div>
