<div class="container">
	<h1 class="page-title">License Agreement</h1>

	<form action="<?=$installStep("step1")?>" method="post">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<pre class="license"><?=htmlentities($license)?></pre>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<button class="btn btn-block btn-primary">Accept</button>
			</div>
		</div>
	</form>
</div>
