<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'edit-component-modal');
$this->startSection('modal-size', 'modal-sm');
$this->startSection('modal-title', t('edit_component'));
$this->startSection('modal-primary-btn-txt', t('save'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('project_settings_save_component')?>" method="post" class="form-horizontal">
<input type="hidden" name="_method" value="put">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('project_settings/components/_form.phtml', ['component' => $component])?>
<?php $this->endSection(); ?>
