<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'new-component-modal');
$this->startSection('modal-size', 'modal-sm');
$this->startSection('modal-title', t('new_component'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('project_settings_create_component')?>" method="post" class="form-horizontal">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('project_settings/components/_form.phtml', ['component' => $component])?>
<?php $this->endSection(); ?>
