<div class="changelog container">
	<h1 class="page-header"><?=t('changelog')?></h1>

	<?php foreach ($milestones as $milestone) : ?>
		<div class="changeset">
			<h2><?=$milestone['name']?></h2>
			<ul>
			<?php foreach ($milestone['changes'] as $ticket) : ?>
				<li class="type_<?=$ticket['type_id']?>">
					<a href="<?=routeUrl('ticket', ['id' => $ticket['ticket_id']])?>"><?=$ticket['summary']?></a>
				</li>
			<?php endforeach; ?>
			</ul>
		</div>
	<?php endforeach ?>
	</div>

	<style>
		<?php foreach ($types as $type => $bullet) : ?>
			.type_<?=$type?>:before {
				content: "<?=utf8_encode($bullet)?>";
			}
		<?php endforeach ?>
	</style>
</div>
