<?php $this->extend('layouts/default.phtml'); ?>

<?php $this->startSection('content'); ?>
<main class="project-listing content container">
    <h1 class="page-header"><?=t('projects')?></h1>

    <ul id="projects-list">
    <?php foreach ($projects as $project) : ?>
        <li>
            <h2 class="project-name">
                <a href="<?=routeUrl('project', ['pslug' => $project['slug']])?>"><?=e($project['name'])?></a>
            </h2>

            <nav>
                <ul class="nav nav-justified nav-pills">
                    <li><a href="<?=routeUrl('roadmap', ['pslug' => $project['slug']])?>"><?=t('roadmap')?></a></li>
                    <li><a href="<?=routeUrl('tickets', ['pslug' => $project['slug']])?>"><?=t('tickets')?></a></li>
                    <li><a href="<?=routeUrl('timeline', ['pslug' => $project['slug']])?>"><?=t('timeline')?></a></li>
                    <?php Hook::run('template:projects/index/project/nav', [$project]); ?>
                </ul>
            </nav>
        </li>
    <?php endforeach ?>
    </ul>
</main>
<?php $this->endSection(); ?>
