<div class="project-listing container">
    <h1 class="page-header"><?=t('projects')?></h1>
    <ul id="project-list">
        <?php foreach ($projects as $project) :
            if (!has_permission($project['id'], 'view', true)) {
                continue;
            }
        ?>
        <li>
            <h2>
                <a href="<?=routeUrl('project', ['pslug' => $project['slug']])?>"><?=$project['name']?></a>
                <?php if ($project['codename']) : ?>
                <small>
                    <em class="project-codename"><?=$project['codename']?></em>
                </small>
                <?php endif ?>
            </h2>
            <nav>
                <ul class="nav nav-justified nav-pills">
                    <li><a href="<?=routeUrl('roadmap', ['pslug' => $project['slug']])?>"><?=t('roadmap')?></a></li>
                    <li><a href="<?=routeUrl('tickets', ['pslug' => $project['slug']])?>"><?=t('tickets')?></a></li>
                    <li><a href="<?=routeUrl('timeline', ['pslug' => $project['slug']])?>"><?=t('timeline')?></a></li>
                    <?php Hook::run('template:projects/index/project/nav', [$project]); ?>
                </ul>
            </nav>
            <div class="description">
                <?=Format::text($project['info'])?>
            </div>
            <?php Hook::run('template:projects/index/project', [$project]); ?>
        </li>
        <?php endforeach ?>
    </ul>
</div>
