<h3><?= l('edit_field'); ?></h3>
<form action="<?= Request::requestUri(); ?>" method="post" class="overlay">
	<?= show_errors($field->errors); ?>
	<div class="content">
		<?= view('project_settings/custom_fields/_form', ['field' => $field]); ?>
	</div>
	<div class="actions">
		<input type="submit" value="<?= l('save'); ?>" />
		<input type="button" value="<?= l('cancel'); ?>" onclick="close_overlay();" />
	</div>
</form>
