<?php extendView('layouts/default.phtml'); ?>

<div class="content">
	<h2 class="page-title"><?= l('project_settings') ?></h2>
</div>
<?= view('project_settings/_nav') ?>
<div class="content">
	<?= HTML::link(l('new_field'), "{$project->slug}/settings/custom_fields/new", ['class' => 'btn-success', 'data-overlay' => true, 'icon' => 'fas fa-fw fa-plus']) ?>
</div>
<div>
	<table class="list">
		<thead>
			<tr>
				<th class="name"><?= l('name'); ?></th>
				<th class="type"><?= l('type'); ?></th>
				<th class="actions text-right"><?= l('actions'); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($customFields as $field) { ?>
				<tr>
					<td><?= HTML::link($field->name, "{$project->slug}/settings/custom_fields/{$field->id}/edit", ['data-overlay' => true]) ?></td>
					<td><?= l($field->type) ?></td>
					<td>
						<div class="btn-group justify-end">
							<?= HTML::link(l('edit'), "{$project->slug}/settings/custom_fields/{$field->id}/edit", ['class' => 'btn-warning btn-sm', 'data-overlay' => true, 'icon' => 'fas fa-fw fa-pencil', 'sr-only' => true]) ?>
							<a href="<?= Request::base($project->href("settings/custom_fields/{$field->id}/delete")) ?>" class="btn-danger btn-sm"
								x-data="popoverConfirm({ position: 'center' , message: '<?= l('confirm.delete') ?>', post: true })"
								@click.prevent="toggle()">
								<i class="fas fa-fw fa-trash"></i>
								<span class="sr-only"><?= l('delete'); ?></span>
							</a>
						</div>
					</td>
				</tr>
			<?php } ?>
		</tbody>
	</table>
</div>
