<?php extendView('layouts/default.phtml'); ?>

<div class="content">
	<h2 class="page-title"><?= l('project_settings'); ?></h2>
</div>
<?php view('project_settings/_nav'); ?>
<div class="content">
	<h3><?= l('new_field'); ?></h3>
	<form action="<? Request::requestUri(); ?>" method="post">
		<?= show_errors($field->errors); ?>
		<div class="tabular box">
			<?= view('project_settings/custom_fields/_form', ['field' => $field]); ?>
		</div>
		<div class="actions">
			<input type="submit" value="<?= l('create'); ?>" />
		</div>
	</form>
</div>
