<h3><?= l('new_type'); ?></h3>
<form action="<?= Request::uri(); ?>" method="post" class="overlay">
	<?= show_errors($type->errors); ?>
	<div class="content">
		<?= view('admin/types/_form', ['type' => $type]); ?>
	</div>
	<div class="actions">
		<input type="submit" value="<?= l('create'); ?>" class="btn-primary" />
		<input type="button" value="<?= l('cancel'); ?>" onclick="close_overlay();" />
	</div>
</form>
