<div class="profile container">
    <h1 class="page-header"><?=$t('xs_profile', [$profile->name])?></h1>

    <div class="row">
        <div class="sidebar col-md-3">
            <div class="profile-information well">
                <h3><?php echo $t('information'); ?></h3>
                <dl>
                    <dt><?php echo $t('group'); ?></dt>
                    <dd><?php echo $profile->group()->name; ?></dd>

                    <dt><?php echo $t('assigned_tickets'); ?></dt>
                    <dd><?php echo $profile->assignedTickets()->rowCount(); ?></dd>

                    <dt><?php echo $t('tickets_created'); ?></dt>
                    <dd><?php echo $profile->tickets()->rowCount(); ?></dd>

                    <dt><?php echo $t('ticket_updates'); ?></dt>
                    <dd><?php echo $profile->ticketUpdates()->rowCount(); ?></dd>

                    <dt><?php echo $t('member_since'); ?></dt>
                    <dd><?php echo ($profile->created_at ? $l(settings('date_format')) : $t('unknown')); ?></dd>
                    <?php Hook::run('template:profile/show', array($profile)); ?>
                </dl>
            </div>
        </div>
    </div>
</div>
