<h3><?= l('edit_ticket_history'); ?></h3>
<form action="<?= Request::requestUri(); ?>" method="post">
	<?= show_errors($history->errors); ?>
	<div class="flex p-4">
		<?= View::render('ticket_history/_form', ['history' => $history]); ?>
	</div>
	<div class="actions">
		<input type="submit" value="<?= l('save'); ?>" class="btn-success" />
		<input type="button" value="<?= l('cancel'); ?>" onclick="close_overlay();" />
	</div>
</form>
