<?php

use Traq\Models\Milestone;
?>
<div class="milestone-progress">
	<?php if ($milestone->status == Milestone::COMPLETE) : ?>
		<a href="<?= Request::base($project->href('tickets') . "?milestone={$milestone->slug}&status=allclosed") ?>" class="progress-closed" style="width: 100%;"></a>
	<?php elseif ($milestone->ticketCount('total') === 0) : ?>
		<a href="<?= Request::base($project->href('tickets') . "?milestone={$milestone->slug}&status=allopen") ?>" class="progress-open" style="width: 100%;"></a>
	<?php else : ?>
		<?php if ($milestone->ticketCount('closed') > 0) : ?>
			<a href="<?= Request::base($project->href('tickets') . "?milestone={$milestone->slug}&status=allclosed") ?>" class="progress-closed" style="width: <?= $milestone->ticketCount('closed_percent') ?>%;"></a>
		<?php endif; ?>

		<?php if ($milestone->ticketCount('started') > 0) : ?>
			<a href="<?= Request::base($project->href('tickets') . "?milestone={$milestone->slug}&status=allstarted") ?>" class="progress-started" style="width: <?= $milestone->ticketCount('started_percent') ?>%;"></a>
		<?php endif; ?>

		<?php if ($milestone->ticketCount('open') > 0) : ?>
			<a href="<?= Request::base($project->href('tickets') . "?milestone={$milestone->slug}&status=allopen") ?>" class="progress-open" style="width: <?= $milestone->ticketCount('open_percent') ?>%;"></a>
		<?php endif; ?>
	<?php endif; ?>
</div>
<ul class="milestone-progress-info">
	<li>
		<a href="<?= Request::base($project->href('tickets') . "?milestone={$milestone->slug}&status=allclosed") ?>"><?= l('x_closed', $milestone->ticketCount('closed')) ?></a>
	</li>
	<li>
		<a href="<?= Request::base($project->href('tickets') . "?milestone={$milestone->slug}&status=allopen") ?>"><?= l('x_open', $milestone->ticketCount('open')) ?></a>
	</li>
	<li>
		<a href="<?= Request::base($project->href('tickets') . "?milestone={$milestone->slug}&status=allstarted") ?>"><?= l('x_started', $milestone->ticketCount('started')) ?></a>
	</li>
	<li>
		<a href="<?= Request::base($project->href('tickets') . "?milestone={$milestone->slug}") ?>"><?= l('x_total', $milestone->ticketCount('total')) ?></a>
	</li>
</ul>
