<?php extendView('layouts/default.phtml'); ?>

<div class="content">
	<h2 id="page-title"><?= l('project_settings') ?></h2>
</div>
<?= view('project_settings/_nav.phtml') ?>
<div class="content">
	<?php if (isset($errors)) : show_errors($errors);
	endif; ?>

	<form action="<?= Request::base($project->href("settings/members/new")) ?>" method="post" class="flex items-end">
		<div class="mr-2">
			<?= Form::label(l('username'), 'username') ?>
			<?= Form::text('username', array('data-autocomplete' => Request::base('/_ajax/autocomplete/username'))) ?>
		</div>
		<div class="mr-2">
			<?= Form::label(l('role'), 'role') ?>
			<?= Form::select('role', $projectRoles) ?>
		</div>
		<div>
			<?= Form::submit(l('add')) ?>
		</div>
	</form>
</div>
<div>
	<form action="<?= Request::base($project->href("settings/members/save")); ?>" method="post">
		<table class="list">
			<thead>
				<tr>
					<th class="fixed_name"><?= l('username') ?></th>
					<th class="role"><?= l('role'); ?></th>
					<th class="actions text-right"><?= l('actions') ?></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($userRoles as $rel) : ?>
					<tr>
						<td><?= $rel->user->username ?></td>
						<td><?= Form::select("role[{$rel->id}]", $projectRoles, ['value' => $rel->project_role_id]) ?></td>
						<td class="text-right">
							<a href="<?= Request::base($project->href("settings/members/{$rel->user_id}/delete")) ?>" class="btn-danger btn-sm"
								x-data="popoverConfirm({ position: 'center' , message: '<?= l('confirm.delete') ?>', post: true })"
								@click.prevent="toggle()">
								<i class="fas fa-fw fa-trash"></i>
								<span class="sr-only"><?= l('delete'); ?></span>
							</a>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
		<div class="actions">
			<?= Form::submit(l('save')) ?>
		</div>
	</form>
</div>
