<?php extendView('layouts/admin.phtml'); ?>

<div class="content">
	<h2 class="page-title"><?= l('settings'); ?></h2>
</div>
<?= View::render('admin/settings/_nav'); ?>
<div class="content">
	<form action="<?= Request::requestUri(); ?>" method="post">
		<?php if (isset($errors)) {
			show_errors($errors);
		} ?>
		<fieldset class="panel">
			<legend><?= l('traq'); ?></legend>

			<div class="panel-content">
				<div class="form-group-row">
					<label><?= l('traq_title'); ?></label>
					<?= Form::text('settings[title]', array('value' => settings('title'))); ?>
				</div>
				<div class="form-group-row">
					<label><?= l('default_language'); ?></label>
					<?= Form::select('settings[locale]', locale_select_options(), array('value' => settings('locale'))); ?>
				</div>
				<div class="form-group-row">
					<label><?= l('theme'); ?></label>
					<?= Form::select('settings[theme]', theme_select_options(), array('value' => settings('theme'))); ?>
				</div>
			</div>
		</fieldset>

		<fieldset class="panel">
			<legend><?= l('settings.site.legend'); ?></legend>

			<div class="panel-content">
				<div class="form-group-row">
					<label for="settings[site_name]"><?= l('settings.site.name'); ?></label>
					<?= Form::text('settings[site_name]', array('value' => settings('site_name'))); ?>
				</div>
				<div class="form-group-row">
					<label for="settings[site_url]"><?= l('settings.site.url'); ?></label>
					<?= Form::text('settings[site_url]', array('value' => settings('site_url'))); ?>
				</div>
			</div>
		</fieldset>

		<fieldset class="panel">
			<legend><?= l('users'); ?></legend>

			<div class="panel-content">
				<div class="form-group-row">
					<label><?= l('allow_registration'); ?></label>
					<?php echo Form::select(
						'settings[allow_registration]',
						array(array('label' => l('yes'), 'value' => 1), array('label' => l('no'), 'value' => 0)),
						array('value' => settings('allow_registration'))
					);
					?>
				</div>
				<div class="form-group-row">
					<label><?= l('email_validation'); ?></label>
					<?php echo Form::select(
						'settings[email_validation]',
						array(array('label' => l('yes'), 'value' => 1), array('label' => l('no'), 'value' => 0)),
						array('value' => settings('email_validation'))
					);
					?>
				</div>
			</div>
		</fieldset>

		<fieldset class="panel">
			<legend><?= l('date_and_time'); ?></legend>

			<div class="panel-content">
				<div class="form-group-row">
					<label><?= l('date_time_format'); ?></label>
					<?= Form::text('settings[date_time_format]', array('value' => settings('date_time_format'))); ?>
				</div>
				<div class="form-group-row">
					<label><?= l('date_format'); ?></label>
					<?= Form::text('settings[date_format]', array('value' => settings('date_format'))); ?>
				</div>
				<div class="form-group-row">
					<label><?= l('timeline_day_format'); ?></label>
					<?= Form::text('settings[timeline_day_format]', array('value' => settings('timeline_day_format'))); ?>
				</div>
				<div class="form-group-row">
					<label><?= l('timeline_time_format'); ?></label>
					<?= Form::text('settings[timeline_time_format]', array('value' => settings('timeline_time_format'))); ?>
				</div>
			</div>
		</fieldset>

		<fieldset class="panel">
			<legend><?= l('notifications'); ?></legend>

			<div class="panel-content">
				<div class="form-group-row">
					<label><?= l('notifications_from_email'); ?></label>
					<?= Form::text('settings[notification_from_email]', array('value' => settings('notification_from_email'))); ?>
				</div>
				<div class="form-group-row">
					<label><?= l('mailer_configuration'); ?></label>
					<div class="input-group">
						<?= Form::select('settings[mailer_config]', [
							['label' => 'Config file', 'value' => 'config'],
							['label' => 'Setting (DSN)', 'value' => 'setting']
						], ['value' => settings('mailer_config')]); ?>
						<abbr class="input-group-hint" title="<?= l('mailer_configuration_hint') ?>">?</abbr>
					</div>
				</div>
				<div class="form-group-row">
					<label><?= l('mailer_dsn'); ?></label>
					<div class="input-group">
						<?= Form::text('settings[mailer_dsn]', array('value' => settings('mailer_dsn'))); ?>
						<abbr class="input-group-hint" title="<?= l('mailer_dsn_hint') ?>">?</abbr>
					</div>
				</div>
			</div>
		</fieldset>

		<fieldset class="panel">
			<legend><?= l('tickets'); ?></legend>

			<div class="panel-content">
				<div class="form-group-row">
					<label><?= l('ticket_history_sorting'); ?></label>
					<?= Form::select('settings[ticket_history_sorting]', ticket_history_sorting_options(), array('value' => settings('ticket_history_sorting'))); ?>
				</div>
				<div class="form-group-row">
					<label><?= l('ticket_creation_delay'); ?></label>
					<div class="input-group">
						<?= Form::text('settings[ticket_creation_delay]', array('value' => settings('ticket_creation_delay'))); ?>
						<abbr class="input-group-hint" title="<?php echo l('help.ticket_creation_delay'); ?>">?</abbr>
					</div>
				</div>
			</div>
		</fieldset>

		<div class="actions">
			<button type="submit" class="btn-primary">
				<?= l('save'); ?>
			</button>
		</div>
	</form>
</div>
