<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'new-project-role-modal');
$this->startSection('modal-size', 'modal-md');
$this->startSection('modal-title', t('new_role'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('admin_create_project_role')?>" method="post" class="form-horizontal">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('admin/project_roles/_form.phtml', ['role' => $role])?>
<?php $this->endSection(); ?>
