<div class="form-group-row">
	<label><?= l('username'); ?></label>
	<?= Form::text('username', array('value' => $user->username)); ?>
</div>
<div class="form-group-row">
	<label><?= l('name'); ?></label>
	<?= Form::text('name', array('value' => $user->name)); ?>
</div>
<div class="form-group-row">
	<label><?= l('password'); ?></label>
	<?= Form::password('password'); ?>
</div>
<div class="form-group-row">
	<label><?= l('email'); ?></label>
	<?= Form::text('email', array('value' => $user->email)); ?>
</div>
<div class="form-group-row">
	<label><?= l('group'); ?></label>
	<?= Form::select('group_id', Traq\Models\Group::select_options(), array('value' => $user->group_id)); ?>
</div>
