<h3><?php echo l('edit_user'); ?></h3>
<form action="<?php echo Request::requestUri(); ?>" method="post" class="overlay">
	<?php echo show_errors($user->errors); ?>
	<div class="content">
		<div class="panel-content">
			<?php echo View::render('admin/users/_form'); ?>
		</div>
	</div>
	<div class="actions">
		<input type="submit" value="<?php echo l('save'); ?>" />
		<input type="button" value="<?php echo l('cancel'); ?>" onclick="close_overlay();" />
	</div>
</form>
