<h3><?= l('edit_user'); ?></h3>
<form action="<?= Request::uri(); ?>" method="post" class="overlay">
	<?php echo show_errors($user->errors); ?>
	<div class="content">
		<div class="panel-content">
			<?= view('admin/users/_form', ['user' => $user]); ?>
		</div>
	</div>
	<div class="actions">
		<input type="submit" value="<?php echo l('save'); ?>" />
		<input type="button" value="<?php echo l('cancel'); ?>" onclick="close_overlay();" />
	</div>
</form>
