<?php extendView('layouts/admin.phtml'); ?>

<div class="content">
	<?= HTML::link(l('new_user'), '/admin/users/new', ['class' => 'btn-success', 'data-overlay' => true, 'icon' => 'fas fa-fw fa-plus']) ?>
</div>
<div id="users">
	<form action="<?= Request::base('/admin/users/mass_actions') ?>" method="post">
		<table class="list">
			<thead>
				<th class="w-4">
					<?= Form::checkbox('all_users', 1, ['id' => "select_all_users"]) ?>
				</th>
				<th class="w-60"><?= l('username') ?></th>
				<th><?= l('group') ?></th>
				<th class="w-48 text-right"><?= l('actions') ?></th>
			</thead>
			<tbody>
				<?php foreach ($users as $user) : ?>
					<tr>
						<td class="mass_actions">
							<input type="checkbox" name="users[]" value="<?= $user->id ?>" />
						</td>
						<td><?= HTML::link($user->username, "/admin/users/{$user->id}/edit", array('data-overlay' => true)) ?></td>
						<td><?= $user->group->name ?></td>
						<td>
							<div class="btn-group justify-end">
								<?= HTML::link(l('edit'), "/admin/users/{$user->id}/edit", ['class' => 'btn-warning btn-sm', 'data-overlay' => true, 'icon' => 'fas fa-fw fa-pencil', 'sr-only' => true]) ?>
								<a href="/admin/users/<?= $user->id ?>/delete" class="btn-danger btn-sm" data-confirm="<?= l('confirm.delete_x', $user->username) ?>"
									x-data="popoverConfirm({ position: 'center', message: '<?= l('confirm.delete') ?>', post: true })"
									@click.prevent="toggle()">
									<i class="fas fa-fw fa-trash"></i>
									<span class="sr-only"><?= l('delete') ?></span>
								</a>
							</div>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>

		<div id=" mass_actions" class="content">
			<div class="column span-5">
				<?= Form::label(l('delete_user'), 'delete_user') ?>
				<?= Form::checkbox('delete_user', 1) ?>
			</div>

			<div class="column span-5">
				<?= Form::label(l('delete_tickets'), 'delete_tickets') ?>
				<?= Form::checkbox('delete_tickets', 1) ?>
			</div>

			<div class="column span-5">
				<?= Form::label(l('delete_comments'), 'delete_comments') ?>
				<?= Form::checkbox('delete_comments', 1) ?>
			</div>

			<div class="clearfix"></div>

			<div class="actions">
				<?= Form::submit(l('submit')) ?>
			</div>


		</div>
	</form>
</div>
