<?php extendView('layouts/admin.phtml'); ?>

<div class="content">
	<h3><?= l('new_user'); ?></h3>
	<form action="<?= Request::RequestUri(); ?>" method="post">
		<?= show_errors($user->errors); ?>
		<div class="panel">
			<div class="panel-content">
				<?= view('admin/users/_form', ['user' => $user]); ?>
			</div>
		</div>
		<div class="actions">
			<input type="submit" value="<?= l('create'); ?>" />
		</div>
	</form>
</div>
