<h3><?= l('new_user'); ?></h3>
<form action="<?= Request::uri(); ?>" method="post" class="overlay">
	<?php echo show_errors($user->errors); ?>
	<div class="content">
		<?= view('admin/users/_form', ['user' => $user]); ?>
	</div>
	<div class="actions">
		<input type="submit" value="<?= l('create'); ?>" />
		<input type="button" value="<?= l('cancel'); ?>" onclick="close_overlay();" />
	</div>
</form>
