<div class="admin-projects container">
	<h1 class="page-header"><?=t('edit_project')?></h1>

	<form action="<?=routeUrl('admin_save_project', ['id' => $project['id']])?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($project)?>
		<?=View::render('project_settings/options/_form.phtml', ['project' => $project])?>
		<div class="form-actions">
			<button type="submit" class="btn btn-success"><?=t('save')?></button>
		</div>
	</form>
</div>
