<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'edit-project-modal');
$this->startSection('modal-size', 'modal-lg');
$this->startSection('modal-title', t('edit_project'));
$this->startSection('modal-primary-btn-txt', t('save'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('admin_save_project')?>" method="post" class="form-horizontal">
<input type="hidden" name="_method" value="put">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('project_settings/options/_form.phtml', ['project' => $project])?>
<?php $this->endSection(); ?>
