<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="admin admin-projects content container">
	<h1 class="page-header"><?=t('projects')?></h1>

	<div class="page-actions">
		<a href="<?=routeUrl('admin_new_project')?>" class="btn btn-success" data-remote-modal="#new-project-modal">
			<span class="fa fa-plus"></span> <?=t('new_project')?>
		</a>
	</div>

	<table class="table table-striped table-hover">
		<thead>
			<th class="name"><?=t('name')?></th>
			<th class="codename"><?=t('codename')?></th>
			<th class="actions"></th>
		</thead>
		<tbody>
		<?php foreach ($projects as $project) : ?>
			<tr>
				<td>
					<a href="<?=routeUrl('admin_edit_project', ['id' => $project['id']])?>" data-remote-modal="#edit-project-modal">
						<?=$project['name']?>
					</a>
				</td>
				<td>
					<?php if ($project['codename']) : ?>
						<span class="project-codename"><?=$project['codename']?></span>
					<?php endif ?>
				</td>
				<td class="actions text-right">
					<a href="<?=routeUrl('admin_edit_project', ['id' => $project['id']])?>" class="btn btn-xs btn-warning" data-remote-modal="#edit-project-modal">
						<span class="fa fa-edit"></span> <?=t('edit')?>
					</a>
					<a href="<?=routeUrl('admin_delete_project', ['id' => $project['id']])?>" class="btn btn-xs btn-danger" data-method="delete" data-confirm="<?=t('confirm.delete')?>">
						<span class="fa fa-times"></span> <?=t('delete')?>
					</a>
				</td>
			</tr>
		<?php endforeach ?>
		</tbody>
	</table>
</div>
<?php $this->endSection(); ?>
