<div class="admin-projects container">
	<h1 class="page-header"><?=$t('projects')?></h1>

	<div class="page-actions">
		<?=HTML::link(
			TWBS::fa('plus', $t('new_project')), '/admin/projects/new', [
				'data-overlay' => true,
				'class' => 'btn btn-success'
		])?>
	</div>

	<table class="table table-striped table-hover">
		<thead>
			<th class="name"><?=$t('name')?></th>
			<th class="codename"><?=$t('codename')?></th>
			<th class="actions"></th>
		</thead>
		<tbody>
		<?php foreach ($projects as $project): ?>
			<tr>
				<td>
					<?=HTML::link(
						$project->name, "/admin/projects/{$project->id}/edit",
						['data-overlay' => true]
					)?>
				</td>
				<td>
					<?php if ($project->codename): ?>
						<span class="project-codename"><?=$project->codename?></span>
					<?php endif; ?>
				</td>
				<td class="actions">
					<?=HTML::link(
						TWBS::fa('edit', $t('edit')), "/admin/projects/{$project->id}/edit",
						['data-overlay' => true, 'class' => 'btn btn-xs btn-warning']
					)?>
					<?=HTML::link(
						TWBS::fa('times', $t('delete')), "/admin/projects/{$project->id}/delete",
						['data-confirm' => $t('confirm.delete'), 'class' => 'btn btn-xs btn-danger']
					)?>
				</td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>
