<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'new-project-modal');
$this->startSection('modal-size', 'modal-lg');
$this->startSection('modal-title', t('new_project'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('admin_create_project')?>" method="post" class="form-horizontal">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('project_settings/options/_form.phtml', ['project' => $project])?>
<?php $this->endSection(); ?>
