<div class="admin-projects container">
	<h1 class="page-header"><?=t('new_project')?></h1>

	<form action="<?=routeUrl('admin_new_project')?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($project)?>
		<?=View::render('project_settings/options/_form.phtml', ['project' => $project])?>
		<div class="form-actions">
		<button type="submit" class="btn btn-success"><?=t('create')?></button>
		</div>
	</form>
</div>
