<div class="admin-projects container">
	<h1 class="page-header"><?=$t('new_project')?></h1>

	<form action="<?=Request::basePath('/admin/projects/new')?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($project)?>
		<?=View::render('project_settings/options/_form.phtml', ['project' => $project])?>
		<div class="form-actions">
			<?=Form::submit($t('create'), array('class' => 'btn btn-success'))?>
		</div>
	</form>
</div>
