<?php if (currentUser()->permission($project->id, 'update_tickets') || currentUser()->permission($project->id, 'comment_on_tickets')) : ?>
	<div class="update-ticket">
		<h3><?= l('update_ticket') ?></h3>

		<?= show_errors($ticket->errors) ?>
		<form action="<?= Request::base($ticket->href('update')) ?>" method="post" id="update_tickets" enctype="multipart/form-data">
			<div class="panel">
				<?php if (currentUser()->permission($project->id, 'comment_on_tickets')) : ?>
					<textarea name="comment" x-data x-mde="{ height: '100px' }"></textarea>
				<?php endif; ?>

				<div class="panel-content">
					<?php if (currentUser()->permission($project->id, 'update_tickets')) { ?>
						<?php if (currentUser()->permission($project->id, 'ticket_properties_change_type')) { ?>
							<div class="form-group">
								<?= Form::label(l('type'), 'type'); ?>
								<?= Form::select('type', Traq\Models\Type::select_options(), array('value' => $ticket->type_id)); ?>
							</div>
						<?php } ?>
						<?php if (currentUser()->permission($project->id, 'ticket_properties_change_assigned_to')) { ?>
							<div class="form-group">
								<?= Form::label(l('assigned_to'), 'assigned_to'); ?>
								<?= Form::select('assigned_to', array_merge(array(array('value' => 0, 'label' => l('none'))), $project->assignable_member_select_options()), array('value' => $ticket->assigned_to_id)); ?>
							</div>
						<?php } ?>
						<?php if (currentUser()->permission($project->id, 'ticket_properties_change_milestone')) { ?>
							<div class="form-group">
								<?= Form::label(l('milestone'), 'milestone'); ?>
								<div class="input-group">
									<?= Form::select(
										'milestone',
										($ticket->milestone and $ticket->milestone->status != 1) ? array_merge($ticket->milestone->select_option(), $project->milestone_select_options('open')) : $project->milestone_select_options('open'),
										array('value' => $ticket->milestone_id)
									) ?>
									<abbr title="<?= l('help.milestone'); ?>" class="input-group-hint">?</abbr>
								</div>
							</div>
						<?php } ?>
						<?php if (currentUser()->permission($project->id, 'ticket_properties_change_version')) { ?>
							<div class="form-group">
								<?= Form::label(l('version'), 'version'); ?>
								<div class="input-group">
									<?= Form::select('version', array_merge(array(array('value' => 0, 'label' => l('none'))), $project->milestone_select_options('all', 'DESC')), array('value' => $ticket->version_id)); ?>
									<abbr title="<?= l('help.version'); ?>" class="input-group-hint">?</abbr>
								</div>
							</div>
						<?php } ?>
						<?php if (currentUser()->permission($project->id, 'ticket_properties_change_component')) { ?>
							<div class="form-group">
								<?= Form::label(l('component'), 'component'); ?>
								<div class="input-group">
									<?= Form::select('component', array_merge(array(array('value' => 0, 'label' => l('none'))), Traq\Models\Component::select_options($project->id)), array('value' => $ticket->component_id)); ?>
									<abbr title="<?= l('help.component'); ?>" class="input-group-hint">?</abbr>
								</div>
							</div>
						<?php } ?>
						<?php if (currentUser()->permission($project->id, 'ticket_properties_change_severity')) { ?>
							<div class="form-group">
								<?= Form::label(l('severity'), 'severity'); ?>
								<div class="input-group">
									<?= Form::select('severity', Traq\Models\Severity::select_options(), array('value' => $ticket->severity_id)); ?>
									<abbr title="<?= l('help.severity'); ?>" class="input-group-hint">?</abbr>
								</div>
							</div>
						<?php } ?>
						<?php if (currentUser()->permission($project->id, 'ticket_properties_change_priority')) { ?>
							<div class="form-group">
								<?= Form::label(l('priority'), 'priority'); ?>
								<?= Form::select('priority', Traq\Models\Priority::select_options(), array('value' => $ticket->priority_id)); ?>
							</div>
						<?php } ?>
						<?php if (currentUser()->permission($project->id, 'ticket_properties_change_status')) { ?>
							<div class="form-group">
								<?= Form::label(l('status'), 'status'); ?>
								<?= Form::select('status', Traq\Models\Status::select_options(), array('value' => $ticket->status_id)); ?>
							</div>
						<?php } ?>
						<?php if (currentUser()->permission($project->id, 'ticket_properties_change_summary')) { ?>
							<div class="form-group">
								<?= Form::label(l('summary'), 'summary'); ?>
								<?= Form::text('summary', array('value' => htmlspecialchars($ticket->summary))); ?>
							</div>
						<?php } ?>
						<?php if (currentUser()->permission($project->id, 'ticket_properties_change_tasks')) { ?>
							<div class="form-group">
								<?= Form::label(l('tasks')) ?>
								<button type="button" id="manage_ticket_tasks" data-url="<?= Request::base($project->href("tickets/{$ticket->ticket_id}/tasks/manage")) ?>"><?php echo l('manage') ?></button>
								<div id="ticket_tasks_data">
									<input type="hidden" name="task_count" value="<?= count($ticket->tasks) ?>">
									<input type="hidden" name="tasks" value="<?= htmlentities(json_encode($ticket->tasks)) ?>">
								</div>
							</div>
						<?php } ?>
						<?php if (currentUser()->permission($project->id, 'add_attachments')) { ?>
							<div class="form-group">
								<?= Form::label(l('attachment'), 'attachment'); ?>
								<input type="file" id="attachment" name="attachment" />
							</div>
						<?php } ?>
						<?php if (currentUser()->permission($project->id, 'ticket_properties_change_time_proposed')) { ?>
							<div class="form-group">
								<?= Form::label(l('proposed_time'), 'time_proposed'); ?>
								<?= Form::text('time_proposed', array('value' => $ticket->time_proposed)); ?>
							</div>
						<?php } ?>
						<?php if (currentUser()->permission($project->id, 'ticket_properties_change_time_worked')) { ?>
							<div class="form-group">
								<?= Form::label(l('worked_time'), 'time_worked'); ?>
								<?= Form::text('time_worked', array('value' => $ticket->time_worked)); ?>
							</div>
						<?php } ?>
						<div class="form-group">
							<?= Form::label(l('is_private'), 'is_private'); ?>
							<?= Form::checkbox('is_private', 1, ['checked' => $ticket->is_private]); ?>
						</div>
						<?= View::render('tickets/_custom_fields_form'); ?>
					<?php } ?>
				</div>

				<div class="panel-footer">
					<button class="btn-primary"><?= l('update') ?></button>
				</div>
			</div>
		</form>
	</div>
	<script type="text/javascript">
		$(document).ready(function() {
			traq.show_hide_custom_fields();
			$('#type').change(function() {
				traq.show_hide_custom_fields();
			});
		});
	</script>
<?php endif; ?>
