<div class="new-ticket content">
	<h2 class="page-title"><?= l('new_ticket') ?></h2>

	<form action="<?= Request::requestUri() ?>" method="post">
		<?= show_errors($ticket->errors) ?>

		<div class="panel">
			<div class="panel-content">
				<div class="form-group-row">
					<label for="type"><?= l('type') ?></label>
					<?= Form::select(
						'type',
						traq\models\Type::select_options(),
						[
							'value' => $ticket->type_id,
							'x-data' => '',
							'x-ticket-template' => "{'mde-instance': 'description'}"
						]
					); ?>
				</div>
				<div class="form-group-row">
					<label for="summary"><?= l('summary') ?></label>
					<input type="text" id="summary" name="summary" value="<?= $ticket->summary ?>">
				</div>
				<?php if (current_user()->permission($project->id, 'ticket_properties_set_status')) : ?>
					<div class="form-group-row">
						<label for="status"><?= l('status') ?></label>
						<?= Form::select('status', traq\models\Status::select_options(), array('value' => $ticket->status_id)); ?>
					</div>
				<?php endif; ?>
				<div>
					<textarea name="description" x-data x-mde="{ height: '200px' }"><?= $ticket->body ?></textarea>
				</div>

				<div class="form-group-grid">
					<div class="form-group">
						<label for="milestone"><?= l('milestone') ?></label>
						<div class="input-group">
							<?= Form::select('milestone', $project->milestone_select_options('open'), array('value' => $ticket->milestone_id)); ?>
							<abbr title="<?= l('help.milestone'); ?>" class="input-group-hint">?</abbr>
						</div>
					</div>

					<?php if (current_user()->permission($project->id, 'ticket_properties_set_version')) : ?>
						<div class="form-group">
							<label for="version"><?= l('version') ?></label>
							<div class="input-group">
								<?= Form::select('version', array_merge([['value' => 0, 'label' => l('none')]], $project->milestone_select_options('all', 'DESC')), ['value' => $ticket->version_id]) ?>
								<abbr title="<?= l('help.version') ?>" class="input-group-hint">?</abbr>
							</div>
						</div>
					<?php endif; ?>

					<?php if (current_user()->permission($project->id, 'ticket_properties_set_component')) : ?>
						<div class="form-group">
							<label for="component"><?= l('component') ?></label>
							<div class="input-group">
								<?= Form::select('component', array_merge(array(array('value' => 0, 'label' => l('none'))), traq\models\Component::select_options($project->id)), array('value' => $ticket->component_id)); ?>
								<abbr title="<? l('help.component') ?>" class="input-group-hint">?</abbr>
							</div>
						</div>
					<?php endif; ?>

					<?php if (current_user()->permission($project->id, 'ticket_properties_set_priority')) : ?>
						<div class="form-group">
							<label for="priority"><?= l('priority') ?></label>
							<?= Form::select('priority', traq\models\Priority::select_options(), array('value' => $ticket->priority_id)) ?>
						</div>
					<?php endif ?>

					<?php if (current_user()->permission($project->id, 'ticket_properties_set_assigned_to')) : ?>
						<div class="form-group">
							<label for="assigned_to"><?= l('assignee') ?></label>
							<?= Form::select('assigned_to', array_merge(array(array('value' => 0, 'label' => l('none'))), $project->assignable_member_select_options()), array('value' => $ticket->assigned_to_id)) ?>
						</div>
					<?php endif; ?>

					<?php if (current_user()->permission($project->id, 'ticket_properties_set_tasks')) : ?>
						<div class="form-group">
							<label><?= l('tasks') ?></label>
							<button type="button" id="manage_ticket_tasks" data-url="<?= Request::base($project->href('tickets/0/tasks/manage')) ?>"><?= l('manage') ?></button>
							<div id="ticket_tasks_data">
								<input type="hidden" name="task_count" value="0">
								<input type="hidden" name="tasks">
							</div>
						</div>
					<?php endif; ?>

					<?php if ($current_user->permission($project->id, 'ticket_properties_set_related_tickets')) : ?>
						<div class="form-group">
							<label for="related_tickets"><?= l('related_tickets') ?></label>
							<?= Form::text('related_tickets'); ?>
						</div>
					<?php endif; ?>
					<?php if ($current_user->permission($project->id, 'ticket_properties_set_time_proposed')) : ?>
						<div class="form-group">
							<label for="time_proposed"><?= l('time_proposed') ?></label>
							<?= Form::text('time_proposed'); ?>
						</div>
					<?php endif; ?>
					<?php if ($current_user->permission($project->id, 'ticket_properties_set_time_worked')) : ?>
						<div class="form-group">
							<label for="time_worked"><?= l('time_worked') ?></label>
							<?= Form::text('time_worked'); ?>
						</div>
					<?php endif; ?>
					<div class="form-group">
						<?= Form::label(l('is_private'), 'is_private'); ?>
						<?= Form::checkbox('is_private', 1); ?>
					</div>
					<?= View::render('tickets/_custom_fields_form'); ?>
				</div>
			</div>
			<div class="panel-footer">
				<button class="btn-primary">
					<?= l('create') ?>
				</button>
			</div>
		</div>
	</form>
</div>
