<?php extendView('layouts/default.phtml'); ?>

<div class="view-ticket">
	<div class="ticket-header">
		<div class="ticket-summary">
			#<?= $ticket->ticket_id ?> - <?= htmlspecialchars($ticket->summary) ?>
		</div>
		<div class="ticket-actions">
			<div class="btn-group">
				<?= subscription_icon_for($ticket) ?>
				<?php if ($current_user->permission($ticket->project_id, 'delete_tickets')) : ?>
					<button class="btn-danger btn-sm" x-data="popoverConfirm({ message: '<?= addslashes(l('confirm.delete_x', $ticket->summary)) ?>', post: '<?= Request::base($ticket->href('delete')) ?>' })" @click="toggle()" title="<?= l('delete') ?>">
						<span class="fas fa-fw fa-trash"></span>
						<span class="visually-hidden"><?= l('delete') ?></span>
					</button>
				<?php endif; ?>
				<?php if ($current_user->permission($ticket->project_id, 'move_tickets')) : ?>
					<a href="<?= Request::base($ticket->href('move')) ?>" class="btn-warning btn-sm" title="<?= l('move') ?>">
						<span class="fas fa-fw fa-angles-right"></span>
						<span class="visually-hidden"><?= l('move') ?></span>
					</a>
				<?php endif; ?>
			</div>
		</div>
	</div>

	<div class="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-8">
		<div class="lg:col-span-2 flex flex-col space-y-6">
			<div class="ticket-description" x-data="{ editing: false }">
				<div class="flex justify-between items-center mb-3">
					<h3 class="text-lg font-semibold flex-grow"><?= l('description') ?></h3>
					<?php if ($current_user->permission($project->id, 'edit_ticket_description')) : ?>
						<button @click="editing = !editing" class="btn-warning btn-sm ticket-edit-btn" x-show="!editing">
							<span class="fas fa-fw fa-pencil"></span>
						</button>
					<?php endif ?>
				</div>
				<section>
					<div x-show="!editing" x-ref="ticketDescription">
						<?= format_text($ticket->body, true) ?>
					</div>
					<?php if ($current_user->permission($project->id, 'edit_ticket_description')) : ?>
						<div x-show="editing" x-data="remoteMde({ url: '<?= Request::base($ticket->href('edit')) ?>' })">
							<textarea name="body" x-ref="editor"><?= $ticket->body ?></textarea>
							<div class="ticket-edit-actions">
								<button class="btn-success" :disabled="saving" @click="save()">
									<span x-show="!saving">
										<?= l('update') ?>
									</span>
									<span x-show="saving" class="fas fa-fw fa-spin fa-circle-notch"></span>
								</button>
								<button class="btn-warning" :disabled="saving" @click="cancel()">
									<?= l('cancel') ?>
								</button>
							</div>
						</div>
					<?php endif; ?>
				</section>
				<?php if (is_array($ticket->tasks) && count($ticket->tasks)) { ?>
					<section class="ticket-tasks">
						<h3><?= l('tasks') ?></h3>
						<ul x-data="ticketTasks({ url: '<?= Request::base($ticket->href('tasks')) ?>', can: <?= $current_user->permission($project->id, 'ticket_properties_complete_tasks') ? 'true' : 'false' ?> })">
							<?php foreach ($ticket->tasks as $id => $task) { ?>
								<li class="ticket-task" id="task-<?= $id ?>" x-data="{ complete: <?= $task['completed'] ? 'true' : 'false' ?> }" @click="toggle(<?= $id ?>)">
									<span class="far fa-fw fa-square" x-show="!isSaving(<?= $id ?>) && !complete"></span>
									<span class="far fa-fw fa-square-check" x-show="!isSaving(<?= $id ?>) && complete"></span>
									<span class="fas fa-fw fa-circle-notch fa-spin" x-show="isSaving(<?= $id ?>)"></span>
									<?= ticket_links($task['task']) ?>
								</li>
							<?php } ?>
						</ul>
					</section>
				<?php } ?>

				<?php if ($current_user->permission($ticket->project_id, 'view_attachments')) : ?>
					<?php if ($attachments && is_array($attachments) && count($attachments)) : ?>
						<section class="ticket-attachments">
							<h3><?= l('attachments') ?></h3>

							<ul>
								<?php foreach ($attachments as $attachment) : ?>
									<li id="attachment-<?= $attachment->id ?>">
										<a href="<?= Request::base($attachment->href()) ?>"><span class="attachment-filename"><?= $attachment->name ?></span></a>,
										<?= l('x_by_x', time_ago($attachment->created_at, false), HTML::link($attachment->user->name, $attachment->user->href())) ?>
										<?php if ($current_user->permission($ticket->project_id, 'delete_attachments')) : ?>
											<button class="btn-danger btn-xs" title="<?= l('delete') ?>" x-data="popoverConfirm({ position: 'center', message: '<?= l('confirm.delete') ?>', remote: '<?= Request::base($attachment->href('/delete')) ?>', success: () => { document.getElementById('attachment-<?= $attachment->id ?>').remove() } })" @click="toggle()">
												<span class="fas fa-fw fa-trash"></span>
												<span class="visually-hidden"><?= l('delete') ?></span>
											</button>
										<?php endif; ?>
									</li>
								<?php endforeach; ?>
							</ul>
						</section>
					<?php endif; ?>
				<?php endif; ?>
			</div>

			<?php if (count($ticket->relatedTickets()) || count($ticket->relatedTickets(true)) || currentUser()->permission($project->id, 'ticket_properties_change_related_tickets')) : ?>
				<div class="ticket-related-tickets" :class="{ 'open': open }" x-data="relatedTickets({ ticketId: <?= $ticket->ticket_id ?>, canEdit: <?= currentUser()->permission($project->id, 'ticket_properties_change_related_tickets') ? 'true' : 'false' ?> })">
					<h3>
						<span @click="open = !open"><?= l('related_tickets') ?></span>
						<div>
							<button class="btn-primary btn-sm" @click.prevent="add()">
								<span class="fas fa-fw fa-plus"></span>
								<span class="sr-only"><?= l('add') ?></span>
							</button>
							<button class="btn-link btn-sm" @click.prevent="open = !open">
								<i class="fas fa-fw fa-chevron-down" x-show="!open"></i>
								<i class="fas fa-fw fa-chevron-up" x-show="open"></i>
							</button>
						</div>
					</h3>
					<div x-show="open" x-transition>
						<?php if (currentUser()->permission($project->id, 'ticket_properties_change_related_tickets')) : ?>
							<div>
								<ul class="editable">
									<template x-for="relatedTicket in relatedTickets" :key="relatedTicket.id">
										<li>
											<select name="relation_type" class="relation-type" @change="updateRelationType(relatedTicket, $event.target.value)">
												<template x-for="relationType in relationTypes" :key="relationType.id">
													<option :value="relationType.id" x-text="relationType.name" :selected="relatedTicket.display_relation_type_id === relationType.id"></option>
												</template>
											</select>
											<a :href="ticketHref(relatedTicket)" class="summary">
												<span :class="`badge priority-${relationPriority(relatedTicket)}`" x-text="`#${relationTicketId(relatedTicket)}`"></span>
												<span x-text="relationSummary(relatedTicket)"></span>
											</a>
											<button class="btn-danger btn-xs action" type="button" @click="remove(relatedTicket)">
												<span class="fas fa-fw fa-trash"></span>
												<span class="sr-only"><?= l('delete') ?></span>
											</button>
										</li>
									</template>
									<template x-for="newRelation in newRelations" :key="newRelation.id">
										<li>
											<select name="relation_type" class="relation-type" x-model="newRelation.relation_type_id">
												<template x-for="relationType in relationTypes" :key="relationType.id">
													<option :value="relationType.id" x-text="relationType.name"></option>
												</template>
											</select>
											<input type="text" name="summary" class="summary" x-model="newRelation.summary" placeholder="<?= l('search') ?>" autocomplete="off" @keyup.debounce.500ms="searchTicket(newRelation, $event.target)" @focus="focusSummary(newRelation)" @click.outsidea="blurSummary(newRelation, $event.target)" />
											<button class="btn-danger btn-xs action" type="button" @click="removeNewRelation(newRelation)">
												<span class="fas fa-fw fa-trash"></span>
												<span class="sr-only"><?= l('delete') ?></span>
											</button>
										</li>
									</template>
								</ul>

								<template x-teleport="body">
									<div x-show="searchResults.length > 0" x-ref="searchResults" class="related-tickets-search-results">
										<ul>
											<template x-for="searchResult in searchResults" :key="searchResult.id">
												<li>
													<a :href="ticketHref(searchResult)" @click.prevent="selectTicket(searchResult)" x-text="`#${searchResult.ticket_id} - ${searchResult.summary}`"></a>
												</li>
											</template>
										</ul>
									</div>
								</template>

								<div x-show="changed || newRelations.length > 0">
									<button class="btn-primary btn-sm" @click="save()">
										<span class="fas fa-fw fa-save"></span>
										<?= l('save') ?>
									</button>
									<button class="btn-warning btn-sm" @click="cancel()">
										<span class="fas fa-fw fa-undo"></span>
										<?= l('cancel') ?>
									</button>
								</div>
							</div>
						<?php else : ?>
							<div>
								<?php foreach ($ticket->relatedTickets() as $relatedTicket) : ?>
									<ul>
										<li>
											<span class="relation-type"><?= $relatedTicket->relation_type_name ?></span>
											<a href="<?= Request::base($relatedTicket->href()) ?>" class="col-span-10">
												<span class="badge priority-<?= $relatedTicket->priority_id ?>">#<?= $relatedTicket->ticket_id ?></span>
												<span><?= htmlspecialchars($relatedTicket->summary) ?></span>
											</a>
										</li>
									</ul>
								<?php endforeach; ?>
							</div>
						<?php endif; ?>
					</div>
				</div>
			<?php endif; ?>

			<div class="ticket-history">
				<h3><?= l('activity') ?></h3>

				<?php foreach ($ticketHistory as $update) : ?>
					<?= View::render('tickets/_history_change', ['ticket' => $ticket, 'update' => $update]) ?>
				<?php endforeach; ?>

				<?php if (!count($ticketHistory)) : ?>
					<div class="alert"><?= l('ticket_history.no_ticket_updates') ?></div>
				<?php endif; ?>
			</div>
			<?= View::render('tickets/_update_ticket_form', ['ticket' => $ticket]) ?>
		</div>

		<div class="lg:col-span-1 relative">
			<div class="sticky top-8 flex flex-col space-y-6">
				<section class="ticket-info-section" :class="{ 'open': open }" x-data="{ open: true }">
					<h3 @click="open = !open">
						<span><?= l('status') ?></span>
						<i class="fas fa-fw fa-chevron-down" x-show="!open"></i>
						<i class="fas fa-fw fa-chevron-up" x-show="open"></i>
					</h3>
					<div class="ticket-info-content" x-show="open" x-transition>
						<div>
							<label for="status"><?= l('status') ?></label>
							<div>
								<?= $ticket->status->name ?>
							</div>
						</div>
						<div>
							<label for="assignee"><?= l('assignee') ?></label>
							<div>
								<?= $ticket->assigned_to ? $ticket->assigned_to->name : '-'; ?>
							</div>
						</div>
						<div>
							<label for="priority"><?= l('priority') ?></label>
							<div>
								<?= $ticket->priority->name ?>
							</div>
						</div>
					</div>
				</section>

				<section class="ticket-info-section" :class="{ 'open': open }" x-data="{ open: true }">
					<h3 @click="open = !open">
						<span><?= l('details') ?></span>
						<i class="fas fa-fw fa-chevron-down" x-show="!open"></i>
						<i class="fas fa-fw fa-chevron-up" x-show="open"></i>
					</h3>
					<div class="ticket-info-content" x-show="open" x-transition>
						<div>
							<label for="type"><?= l('type') ?></label>
							<div>
								<?= $ticket->type->name ?>
							</div>
						</div>
						<div>
							<label for="milestone"><?= l('milestone') ?></label>
							<div>
								<?= $ticket->milestone ? $ticket->milestone->name : '-' ?>
							</div>
						</div>
						<div>
							<label for="component"><?= l('component') ?></label>
							<div>
								<?= $ticket->component ? $ticket->component->name : '-'; ?>
							</div>
						</div>
						<div>
							<label for="version"><?= l('version') ?></label>
							<div>
								<?= $ticket->version ? $ticket->version->name : '-'; ?>
							</div>
						</div>
						<div>
							<label for="severity"><?= l('severity') ?></label>
							<div>
								<?= $ticket->severity->name ?>
							</div>
						</div>
					</div>
				</section>

				<section class="ticket-info-section" :class="{ 'open': open }" x-data="{ open: true }">
					<h3 @click="open = !open">
						<span><?= l('tracking') ?></span>
						<i class="fas fa-fw fa-chevron-down" x-show="!open"></i>
						<i class="fas fa-fw fa-chevron-up" x-show="open"></i>
					</h3>
					<div class="ticket-info-content" x-show="open" x-transition>
						<div>
							<label for="owner"><?= l('owner') ?></label>
							<div>
								<?= $ticket->user->name ?>
							</div>
						</div>
						<div>
							<label for="reported"><?= l('reported') ?></label>
							<div>
								<?= time_ago($ticket->created_at) ?>
							</div>
						</div>
						<div>
							<label for="updated"><?= l('updated') ?></label>
							<div>
								<?= $ticket->updated_at ? time_ago($ticket->updated_at) : '-' ?>
							</div>
						</div>
						<div>
							<label for="votes"><?= l('votes') ?></label>
							<div>
								<?php if ($ticket->votes === 0) : ?>
									<span id="votes"><?= $ticket->votes ?></span>
								<?php else: ?>
									<span id="votes" data-popover-hover="<?= Request::base($ticket->href('/voters')) ?>"><?= $ticket->votes ?></span>
								<?php endif; ?>
								<?php if (LOGGEDIN && currentUser()->permission($project->id, 'vote_on_tickets') && !in_array(currentUser()->id, $ticket->extra['voted']) && currentUser()->id != $ticket->user_id) : ?>
									<a href="<?= Request::base($ticket->href('/vote')) ?>" class="btn-primary btn-sm" data-ajax="1">
										<span class="fas fa-fw fa-plus"></span>
										<span class="visually-hidden"><?= l('vote') ?></span>
									</a>
								<?php endif; ?>
							</div>
						</div>
						<div>
							<label for="time_proposed"><?= l('time_proposed') ?></label>
							<div>
								<?= strlen($ticket->time_proposed) > 0 ? $ticket->time_proposed : '-' ?>
							</div>
						</div>
						<div>
							<label for="time_worked"><?= l('time_worked') ?></label>
							<div>
								<?= strlen($ticket->time_worked) > 0 ? $ticket->time_worked : '-' ?>
							</div>
						</div>
					</div>
				</section>

				<?php if (count($custom_fields)) : ?>
					<section class="ticket-info-section" :class="{ 'open': open }" x-data="{ open: true }">
						<h3 @click="open = !open">
							<span><?= l('custom_fields') ?></span>
							<i class="fas fa-fw fa-chevron-down" x-show="!open"></i>
							<i class="fas fa-fw fa-chevron-up" x-show="open"></i>
						</h3>
						<div class="ticket-info-content" x-show="open" x-transition>
							<?php foreach ($custom_fields as $field) : ?>
								<?php if ($field_value = $ticket->custom_field_value($field->id)) : ?>
									<div class="ticket-property">
										<label><?= $field->name ?></label>
										<span class="value"><?= implode(', ', (array)$field_value->value); ?></span>
									</div>
								<?php endif; ?>
							<?php endforeach; ?>
						</div>
					</section>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>
