<?php extendView('layouts/admin.phtml'); ?>

<div class="admin new custom_tab content">
	<h3><?= l('edit_tab'); ?></h3>
	<form action="<?= Request::uri(); ?>" method="post">
		<?= show_errors($tab->errors); ?>
		<div class="tabular box">
			<?= view('custom_tabs/_form', [
				'tab' => $tab,
			]); ?>
		</div>
		<div class="actions">
			<input type="submit" value="<?= l('save'); ?>" />
		</div>
	</form>
</div>
