<?php extendView('layouts/admin.phtml'); ?>

<div class="admin custom_tabs listing content">
	<?= HTML::link(l('new_tab'), '/admin/custom-tabs/new', ['class' => 'btn-success', 'data-overlay' => true, 'icon' => 'fas fa-fw fa-plus']); ?>
</div>
<div>
	<table class="list">
		<thead>
			<th><?= l('name'); ?></th>
			<th class="w-48 text-right"><?= l('actions'); ?></th>
		</thead>
		<tbody>
			<?php foreach ($custom_tabs as $tab) : ?>
				<tr>
					<td><?= HTML::link($tab->label, "/admin/custom-tabs/{$tab->id}/edit", array('data-overlay' => true)); ?></td>
					<td>
						<div class="btn-group justify-end">
							<?= HTML::link(l('edit'), "/admin/custom-tabs/{$tab->id}/edit", ['class' => 'btn-warning btn-sm', 'data-overlay' => true, 'icon' => 'fas fa-fw fa-pencil', 'sr-only' => true]); ?>
							<a href="/admin/custom-tabs/<?= $tab->id ?>/delete" class="btn-danger btn-sm"
								x-data="popoverConfirm({ message: '<?= l('confirm.delete') ?>', post: true })"
								@click.prevent="toggle()">
								<i class="fas fa-fw fa-trash"></i>
								<span class="sr-only"><?= l('delete'); ?></span>
							</a>
						</div>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
