<div class="form-group">
	<?=Form::label($t('name'), 'name', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::text('name', ['value' => $role->name, 'class' => 'form-control'])?>
	</div>
</div>
<div class="form-group">
	<?=Form::label($t('assignable'), 'is_assignable', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::checkbox('is_assignable', 1, ['checked' => $role->is_assignable])?>
	</div>
</div>
<div class="form-group">
	<?=Form::label($t('project'), 'project_id', ['class' => 'control-label col-md-3'])?>
	<div class="col-md-9">
		<?=Form::select(
			'project_id',
			array_merge(
				[['label' => $t('all'), 'value' => 0]],
				Traq\Models\Project::selectOptions()
			),
			['value' => $role->project_id, 'class' => 'form-control']
		)?>
	</div>
</div>
