<div class="form-group <?=$role->hasError('name') ? 'has-error' : ''?>">
	<label for="name" class="control-label col-md-3"><?=t('name')?></label>
	<div class="col-md-9">
		<input type="text" name="name" id="name" class="form-control" value="<?=e($role['name'])?>">
		<?php if ($role->hasError('name')) : ?>
		<div class="help-block"><?=$role->getError('name')[0]?></div>
		<?php endif ?>
	</div>
</div>
<div class="form-group">
	<label for="is_assignable" class="control-label col-md-3"><?=t('assignable')?></label>
	<div class="col-md-9">
		<?=Form::checkbox('is_assignable', 1, ['checked' => $role['is_assignable']])?>
	</div>
</div>
<div class="form-group">
	<label for="project_id" class="control-label col-md-3"><?=t('project')?></label>
	<div class="col-md-9">
		<?=Form::select(
			'project_id',
			array_merge(
				[['label' => t('all'), 'value' => 0]],
				Traq\Models\Project::selectOptions()
			),
			['value' => $role['project_id'], 'class' => 'form-control']
		)?>
	</div>
</div>
