<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'edit-project-role-modal');
$this->startSection('modal-size', 'modal-md');
$this->startSection('modal-title', t('edit_role'));
$this->startSection('modal-primary-btn-txt', t('save'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('admin_save_project_role')?>" method="post" class="form-horizontal">
<input type="hidden" name="_method" value="put">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('admin/project_roles/_form.phtml', ['role' => $role])?>
<?php $this->endSection(); ?>
