<div class="edit admin roles container">
	<h1 class="page-header"><?=$t('edit_role')?></h1>

	<form action="<?=Request::basePath($route('edit_admin_project_role'))?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($role)?>
		<?=View::render('admin/project_roles/_form.phtml', ['role' => $role])?>
		<div class="form-actions">
			<?=Form::submit($t('save'), ['class' => 'btn btn-success'])?>
		</div>
	</form>
</div>
