<div class="edit admin roles container">
	<h1 class="page-header"><?=t('edit_role')?></h1>

	<form action="<?=routeUrl('admin_save_project_role', ['id' => $role['id']])?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($role)?>
		<?=View::render('admin/project_roles/_form.phtml', ['role' => $role])?>
		<div class="form-actions">
			<?=Form::submit(t('save'), ['class' => 'btn btn-success'])?>
		</div>
	</form>
</div>
