<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="admin admin-project-roles content container">
	<h1 class="page-header"><?=t('roles')?></h1>

	<div class="page-actions">
		<a href="<?=routeUrl('admin_new_project_role')?>" class="btn btn-success" data-overlay="true">
			<span class="fa fa-plus"></span> <?=t('new_role')?>
		</a>
	</div>

	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th><?=t('name')?></th>
				<th><?=t('assignable')?></th>
				<th><?=t('project')?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($roles as $role) : ?>
			<tr>
				<td>
					<a href="<?=routeUrl('admin_edit_project_role', ['id' => $role['id']])?>" data-overlay="true"><?=$role['name']?></a>
				</td>
				<td><?=($role['is_assignable'] ? TWBS::fa('check') : TWBS::fa('times'))?></td>
				<td><?=($role['project_id'] ? $role['project_name'] : t('all'))?></td>
				<td class="actions text-right">
					<a href="<?=routeUrl('admin_edit_project_role', ['id' => $role['id']])?>" class="btn btn-xs btn-warning" data-overlay="true">
						<span class="fa fa-edit"></span> <?=t('edit')?>
					</a>
					<a href="<?=routeUrl('admin_delete_project_role', ['id' => $role['id']])?>" class="btn btn-xs btn-danger" data-method="delete" data-confirm="<?=t('confirm.delete')?>">
						<span class="fa fa-times"></span> <?=t('delete')?>
					</a>
				</td>
			</tr>
		<?php endforeach ?>
		</tbody>
	</table>
</div>
<?php $this->endSection(); ?>
