<div class="admin roles container">
	<h1 class="page-header"><?=$t('roles')?></h1>

	<div class="page-actions">
		<?=HTML::link(TWBS::fa('plus', $t('new_role')), $route('new_admin_project_role'), [
			'class' => 'btn btn-success',
			'data-overlay' => true
		])?>
	</div>

	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th><?=$t('name')?></th>
				<th><?=$t('assignable')?></th>
				<th><?=$t('project')?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($roles as $role): ?>
			<tr>
				<td><?=HTML::link($role->name, $route('edit_admin_project_role', ['id' => $role->id]))?></td>
				<td><?=($role->is_assignable ? TWBS::fa('check') : TWBS::fa('times'))?></td>
				<td><?=($role->project_id ? $role->project()->name : $t('all'))?></td>
				<td class="actions">
					<?=HTML::link(TWBS::fa('edit', $t('edit')), $route('edit_admin_project_role', ['id' => $role->id]), [
						'class' => 'btn btn-xs btn-warning',
						'data-overlay' => true
					])?>
					<?=HTML::link(TWBS::fa('times', $t('delete')), $route('delete_admin_project_role', ['id' => $role->id]), [
						'class' => 'btn btn-xs btn-danger',
						'data-confirm' => $t('confirm.delete')
					])?>
				</td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>
