<div class="new admin roles container">
	<h1 class="page-header"><?=t('new_role')?></h1>

	<form action="<?=routeUrl('admin_new_project_role')?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($role)?>
		<?=View::render('admin/project_roles/_form.phtml', ['role' => $role])?>
		<div class="form-actions">
			<?=Form::submit(t('create'), ['class' => 'btn btn-success'])?>
		</div>
	</form>
</div>
