<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="admin admin-severities content container">
	<h1 class="page-header"><?=t('severities')?></h1>

	<div class="page-actions">
		<a href="<?=routeUrl('admin_new_severity')?>" class="btn btn-success" data-remote-modal="#new-severity-modal">
			<span class="fa fa-plus"></span> <?=t('new_severity')?>
		</a>
	</div>

	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th><?=t('name')?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($severities as $severity) : ?>
			<tr>
				<td>
					<a href="<?=routeUrl('admin_edit_severity', ['id' => $severity['id']])?>" data-remote-modal="#edit-severity-modal">
						<?=$severity['name']?>
					</a>
				</td>
				<td class="actions text-right">
					<a href="<?=routeUrl('admin_edit_severity', ['id' => $severity['id']])?>" class="btn btn-xs btn-warning" data-remote-modal="#edit-severity-modal">
						<span class="fa fa-edit"></span> <?=t('edit')?>
					</a>
					<a href="<?=routeUrl('admin_delete_severity', ['id' => $severity['id']])?>" class="btn btn-xs btn-danger" data-method="delete" data-confirm="<?=t('confirm.delete')?>">
						<span class="fa fa-times"></span> <?=t('delete')?>
					</a>
				</td>
			</tr>
		<?php endforeach ?>
		</tbody>
	</table>
</div>
<?php $this->endSection(); ?>
