<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'new-severity-modal');
$this->startSection('modal-size', 'modal-sm');
$this->startSection('modal-title', t('new_severity'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('admin_create_severity')?>" method="post" class="form-horizontal">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('admin/severities/_form.phtml', ['severity' => $severity])?>
<?php $this->endSection(); ?>
