<div class="modal fade">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form action="<?=routeUrl('project_settings_save_milestone', ['id' => $milestone['id']])?>" method="post" class="form-horizontal">
				<?=TWBS::modalHeader(t('edit_milestone'))?>
				<div class="modal-body">
					<?=View::render('project_settings/milestones/_form.phtml', ['milestone' => $milestone])?>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-success"><?=t('save')?></button>
					<button type="button" class="btn btn-default" data-dismiss="modal"><?=t('cancel')?></button>
				</div>
			</form>
		</div>
	</div>
</div>
