<div class="project-settings milestones container">
	<div class="page-actions">
		<?=HTML::link(TWBS::fa('plus', $t('new_milestone')), $route('new_project_settings_milestone'), [
			'class' => 'btn btn-success',
			'data-overlay' => true
		])?>
	</div>

	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th><?=$t('name')?></th>
				<th><?=$t('codename')?></th>
				<th><?=$t('status')?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($milestones as $milestone): ?>
			<tr>
				<td><?=HTML::link($milestone->name, $route('edit_project_settings_milestone', ['id' => $milestone->id]))?></td>
				<td><?=$milestone->codename?></td>
				<td>
					<?=$milestone->status == 0
							? $t('cancelled') : $milestone->status == 1
							? $t('active') : $t('completed');
					?>
				</td>
				<td class="actions">
					<?=HTML::link(TWBS::fa('edit', $t('edit')), $route('edit_project_settings_milestone', ['id' => $milestone->id]), [
						'class' => 'btn btn-xs btn-warning',
						'data-overlay' => true
					])?>
					<?=HTML::link(TWBS::fa('times', $t('delete')), $route('delete_project_settings_milestone', ['id' => $milestone->id]), [
						'class' => 'btn btn-xs btn-danger',
						'data-confirm' => $t('confirm.delete')
					])?>
				</td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>
