<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'new-milestone-modal');
$this->startSection('modal-size', 'modal-lg');
$this->startSection('modal-title', t('new_milestone'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('project_settings_create_milestone')?>" method="post" class="form-horizontal">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('project_settings/milestones/_form.phtml', ['milestone' => $milestone])?>
<?php $this->endSection(); ?>
