<div class="content">
	<?= HTML::link(l('new_severity'), '/admin/severities/new', ['class' => 'btn-success', 'data-overlay' => true, 'icon' => 'fas fa-fw fa-plus']) ?>
</div>
<div>
	<table class="list">
		<thead>
			<th class="name"><?= l('name') ?></th>
			<th class="w-48 text-right"><?= l('actions') ?></th>
		</thead>
		<tbody>
			<?php foreach ($severities as $severity) : ?>
				<tr>
					<td><?= HTML::link($severity->name, "/admin/severities/{$severity->id}/edit", array('data-overlay' => true)) ?></td>
					<td>
						<div class="btn-group justify-end">
							<?= HTML::link(l('edit'), "/admin/severities/{$severity->id}/edit", ['class' => 'btn-warning btn-sm', 'data-overlay' => true, 'icon' => 'fas fa-fw fa-pencil', 'sr-only' => true]) ?>
							<?= HTML::link(l('delete'), "/admin/severities/{$severity->id}/delete", ['class' => 'btn-danger btn-sm', 'data-confirm' => l('confirm.delete_x', $severity->name), 'icon' => 'fas fa-fw fa-trash', 'sr-only' => true]) ?>
						</div>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
