<h3><?= l('new_severity'); ?></h3>
<form action="<?= Request::uri(); ?>" method="post" class="overlay">
	<?= show_errors($severity->errors); ?>
	<div class="content">
		<?= view('admin/severities/_form', ['severity' => $severity]); ?>
	</div>
	<div class="actions">
		<input type="submit" value="<?= l('create'); ?>" class="btn-primary" />
		<input type="button" value="<?= l('cancel'); ?>" onclick="close_overlay();" />
	</div>
</form>
