<h3><?= l('new_severity'); ?></h3>
<form action="<?= Request::requestUri(); ?>" method="post" class="overlay">
	<?= show_errors($severity->errors); ?>
	<div class="content">
		<?= View::render('admin/severities/_form'); ?>
	</div>
	<div class="actions">
		<input type="submit" value="<?= l('create'); ?>" />
		<input type="button" value="<?= l('cancel'); ?>" onclick="close_overlay();" />
	</div>
</form>
