<div id="<?=$this->getSection('modal-id', 'modal')?>" class="modal fade" tabindex="-1" role="dialog">
	<div class="modal-dialog <?=$this->getSection('modal-size')?>">
		<div class="modal-content">
		<?php if ($this->hasSection('modal-form-start')) : $form = true; ?>
			<?=$this->getSection('modal-form-start')?>
		<?php endif ?>
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title"><?=$this->getSection('modal-title')?></h4>
			</div>
			<div class="modal-body">
				<?=$this->getSection('modal-content')?>
			</div>
			<div class="modal-footer">
			<?php if ($this->hasSection('modal-footer')) : ?>
				<?=$this->getSection('modal-footer')?>
			<?php else : ?>
				<button type="button" class="btn btn-default" data-dismiss="modal"><?=t('close')?></button>
				<?php if ($this->hasSection('modal-primary-btn')) : ?>
					<?=$this->getSection('modal-primary-btn')?>
				<?php else : ?>
					<button type="submit" class="btn btn-success">
						<?=$this->getSection('modal-primary-btn-txt', t('create'))?>
					</button>
				<?php endif ?>
			<?php endif ?>
			</div>
		<?php if (isset($form) && $form) : ?>
			</form>
		<?php endif ?>
		</div>
	</div>
</div>
