<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'new-priority-modal');
$this->startSection('modal-size', 'modal-sm');
$this->startSection('modal-title', t('new_priority'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('admin_create_priority')?>" method="post" class="form-horizontal">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('admin/priorities/_form.phtml', ['priority' => $priority])?>
<?php $this->endSection(); ?>
