<?php extendView('layouts/admin.phtml'); ?>

<div class="content">
	<h3><?= l('edit_group'); ?></h3>
	<form action="<?= Request::uri(); ?>" method="post">
		<?= show_errors($group->errors); ?>
		<div class="panel">
			<div class="panel-content">
				<?= view('admin/groups/_form', ['group' => $group]); ?>
			</div>
		</div>
		<div class="actions">
			<input type="submit" value="<?= l('save'); ?>" />
		</div>
	</form>
</div>
