<h3><?= l('new_group'); ?></h3>
<form action="<?= Request::uri(); ?>" method="post" class="overlay">
	<?= show_errors($group->errors); ?>
	<div class="content">
		<?= view('admin/groups/_form', ['group' => $group]); ?>
	</div>
	<div class="actions">
		<input type="submit" value="<?= l('create'); ?>" class="btn-primary" />
		<input type="button" value="<?= l('cancel'); ?>" onclick="close_overlay();" />
	</div>
</form>
