<?php extendView('layouts/default.phtml'); ?>

<div class="usercp password content">
	<h2 class="page-title"><?= l('usercp') ?></h2>
</div>
<?= View::render('usercp/_nav') ?>
<div class="usercp password content">
	<?= show_errors($user->errors) ?>
	<form action="<?= Request::requestUri() ?>" method="post">
		<fieldset class="panel panel-content">
			<legend><?= l('password') ?></legend>

			<div>
				<div class="form-group-row">
					<?= Form::label(l('old_password'), 'old_password') ?>
					<?= Form::password('password') ?>
				</div>
				<div class="form-group-row">
					<?= Form::label(l('new_password'), 'new_password') ?>
					<?= Form::password('new_password') ?>
				</div>
				<div class="form-group-row">
					<?= Form::label(l('confirm_password'), 'confirm_password') ?>
					<?= Form::password('confirm_password') ?>
				</div>
				<?php FishHook::run('template:users/usercp/password'); ?>
			</div>
		</fieldset>

		<div class="actions">
			<?= Form::submit(l('save')) ?>
		</div>
	</form>
</div>
