<?php extendView('layouts/default.phtml'); ?>

<div class="usercp content">
	<h2 class="page-title"><?= l('usercp') ?></h2>
</div>
<?= View::render('usercp/_nav') ?>
<table class="list">
	<thead>
		<tr>
			<th><?= l('type') ?></th>
			<th><?= l('for') ?></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($subscriptions as $sub) : ?>
			<tr>
				<td><?= l($sub->type) ?></td>
				<?php if ($sub->type == 'project' || $sub->type == 'milestone') : ?>
					<td><?= HTML::link($sub->object()->name, $sub->object()->href()) ?></td>
				<?php elseif ($sub->type == 'ticket') : ?>
					<td><?= HTML::link($sub->object()->summary, $sub->object()->href()) ?></td>
				<?php endif; ?>
				<td><?= HTML::link(l('unsubscribe'), $sub->object()->href('unsubscribe')); ?></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>
