<?=View::render('layouts/_meta_nav.phtml')?>
<header id="header" class="navbar navbar-default navbar-static-top">
	<div class="container">
		<div class="navbar-header">
			<?=HTML::link($t('admincp'), '/admin', ['class' => "navbar-brand"])?>
		</div>
		<nav id="nav-main">
		<?php if ($currentUser and $currentUser->group()->isAdmin()): ?>
			<ul class="nav navbar-nav navbar-left">
				<li><?=HTML::link($t('settings'), '/admin/settings')?></li>
				<li><?=HTML::link($t('projects'), '/admin/projects')?></li>
				<li><?=HTML::link($t('roles'), '/admin/roles')?></li>
				<li><?=HTML::link($t('users'), '/admin/users')?></li>
				<li><?=HTML::link($t('groups'), '/admin/groups')?></li>
				<li><?=HTML::link($t('plugins'), '/admin/plugins')?></li>
				<li><?=HTML::link($t('types'), '/admin/types')?></li>
				<li><?=HTML::link($t('statuses'), '/admin/statuses')?></li>
				<li><?=HTML::link($t('priorities'), '/admin/priorities')?></li>
				<li><?=HTML::link($t('severities'), '/admin/severities')?></li>
			</ul>
		<?php endif; ?>
		</nav>
	</div>
</header>
