<footer id="footer">
    <div class="container">
        <span class="text-muted"><?=$t('copyright')?></span>
    </div>
</footer>
<div id="overlay"></div>
<?=HTML::jsIncTag('assets/components/jquery/dist/jquery.min.js')?>
<?=HTML::jsIncTag('assets/components/jquery-ui/jquery-ui.min.js')?>
<?=HTML::jsIncTag('assets/components/bootstrap/dist/js/bootstrap.min.js')?>
<?=HTML::jsIncTag('assets/components/jquery-cookie/jquery.cookie.js')?>
<?=HTML::jsIncTag('assets/js/ujs.js')?>
<?=HTML::jsIncTag('assets/js/traq.js')?>
<?=HTML::jsIncTag('_js')?>
<!-- <?=round((microtime(true) - START_TIME), 2); ?>s, <?php echo round((memory_get_peak_usage() - START_MEM) / pow(1024, 2), 3)?>mb -->
