<footer id="footer">
	<div class="container">
		<?php if ($_ENV['environment'] === 'development') : ?>
		<div class="text-muted pull-right">
			<?=round((microtime(true) - START_TIME), 2); ?>s, <?php echo round((memory_get_peak_usage() - START_MEM) / pow(1024, 2), 3)?>mb
		</div>
		<?php endif ?>
		<div class="text-muted">Powered by Traq <?=TRAQ_VERSION?> &copy 2009-<?=date("Y")?> Traq.io</div>
	</div>
</footer>
<div id="overlay"></div>
