<meta charset="UTF-8">
<title><?=implode(' / ', $traq->title())?></title>

<link rel="stylesheet" type="text/css" href="<?=Request::$basePath?>/assets/css/traq.css">

<script type="text/javascript" src="<?=Request::$basePath?>/assets/js/js.js"></script>
<script type="text/javascript" src="<?=Request::$basePath?>/assets/js/traq.js"></script>
<script type="text/javascript" src="<?=routeUrl('js')?>"></script>
