<title><?=implode(' / ', $traq->title)?></title>
		<meta charset="UTF-8">

		<?=HTML::cssLinkTag("assets/css/traq.css")?>
		<?=HTML::cssLinkTag('assets/components/font-awesome/css/font-awesome.min.css')?>

		<?php Hook::run('template:layouts/global/head'); ?>

<?php foreach ($traq->feeds as $feed): ?>
		<link type="application/atom+xml" rel="alternate" title="<?=$feed[1]?>" href="<?=$feed[0]?>">
<?php endforeach; ?>
