<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2" aria-expanded="false">
                <span class="sr-only"><?=t('toggle_navigation')?></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-2">
            <ul class="nav navbar-nav">
            <?php if (setting('site_url')) : ?>
                <li><a href="<?=setting('site_url')?>"><?=setting('site_name')?></a></li>
            <?php endif ?>
            <?php if (currentProject() || Request::matches('/admin(.*)')) : ?>
                <li><a href="<?=routeUrl('root')?>"><?=setting('title')?></a></li>
            <?php endif ?>
            </ul>

            <ul class="nav navbar-nav navbar-right">
            <?php if (currentUser()) : ?>
                <?php if (currentUser()->isAdmin()) : ?>
                <li>
                    <a href="<?=routeUrl('admincp')?>" title="<?=t('admincp')?>">
                        <i class="fa fa-lock"></i> <span class="sr-only"><?=t('admincp')?></span>
                    </a>
                </li>
                <?php endif; ?>
                <li class="dropdown">
                    <a href="<?=routeUrl('user', ['id' => currentUser()['id']])?>" class="dropdown-toggle" data-toggle="dropdown">
                        <?=Gravatar::model(currentUser(), 16)?> <span class="sr-only"><?=currentUser()['name']?></span> <i class="caret"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?=routeUrl('user', ['id' => currentUser()['id']])?>"><?=t('profile')?></a>
                        </li>
                        <li>
                            <a href="<?=routeUrl('usercp')?>"><?=t('usercp')?></a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="<?=routeUrl('logout')?>" title="<?=t('logout')?>" data-method="delete"><i class="fa fa-sign-out"></i> <span class="sr-only"><?=t('logout')?></span></a>
                </li>
            <?php else : ?>
                <li<?=iif(Request::matches('/login'), ' class="active"')?>>
                    <a href="<?=routeUrl('login')?>" title="<?=t('login')?>"><i class="fa fa-sign-in"></i> <span class="sr-only"><?=t('login')?></span>
                </a></li>
                <li<?=iif(Request::matches('/register'), ' class="active"')?>>
                    <a href="<?=routeUrl('register')?>" title="<?=t('register')?>"><i class="fa fa-user-plus"></i> <span class="sr-only"><?=t('register')?></span></a>
                </li>
            <?php endif ?>
            </ul>
        </div>
    </div>
</nav>
