<?php if ($pagination->paginate): ?>
<div class="text-center">
	<ul class="pagination">
		<li class="previous<?=!$pagination->prevPageUri ? ' disabled' : ''?>">
			<?=HTML::link($t('previous'), $pagination->prevPageUri)?>
		</li>
		<?php foreach ($pagination->pageLinks as $page): ?>
		<li<?=$page['page'] == $pagination->page ? ' class="active"' : '' ?>>
			<?=HTML::link($page['page'], $page['uri'])?>
		</li>
		<?php endforeach; ?>
		<li class="next<?=!$pagination->nextPageUri ? ' disabled' : ''?>">
			<?=HTML::link($t('next'), $pagination->nextPageUri)?>
		</li>
	</ul>
</div>
<?php endif; ?>
