<?php if ($pagination->paginate) : ?>
<div class="text-center">
    <ul class="pagination">
        <li class="previous<?=!$pagination->prevPageUri ? ' disabled' : ''?>">
        <?php if ($pagination->prevPageUri) : ?>
            <a href="<?=Request::$basePath?><?=$pagination->prevPageUri?>"><?=t('previous')?></a>
        <?php else : ?>
            <a><?=t('previous')?></a>
        <?php endif?>
        </li>
        <?php foreach ($pagination->pageLinks as $page) : ?>
        <li<?=$page['page'] == $pagination->page ? ' class="active"' : '' ?>>
            <a href="<?=Request::$basePath?><?=$page['uri']?>"><?=$page['page']?></a>
        </li>
        <?php endforeach ?>
        <li class="next<?=!$pagination->nextPageUri ? ' disabled' : ''?>">
        <?php if ($pagination->nextPageUri) : ?>
            <a href="<?=Request::$basePath?><?=$pagination->nextPageUri?>"><?=t('next')?></a>
        <?php else : ?>
            <a><?=t('next')?></a>
        <?php endif?>
        </li>
    </ul>
</div>
<?php endif ?>
