<?php $this->extend('layouts/default.phtml'); ?>

<?php $this->startSection('navbar'); ?>
<div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
        <span class="sr-only"><?=t('toggle_navigation')?></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a href="<?=routeUrl('admincp')?>" class="navbar-brand"><?=t('admincp')?></a>
</div>
<?php $this->endSection(); ?>
