<!DOCTYPE html>
<html lang="en">
	<head>
		<?=View::render('layouts/_head.phtml')?>
		<?php Hook::run('template:layouts/usercp:head'); ?>
	</head>
	<body>
		<?php require __DIR__ . '/_header.phtml'; ?>
		<main id="page">
			<div class="container">
				<h1 class="page-header"><?=t('usercp')?></h1>
			</div>
			<?php echo View::render('usercp/_nav.phtml'); ?>
			<?=$content?>
		</main>
		<?php require __DIR__ . '/_footer.phtml'; ?>
		<?php Hook::run('template:layouts/usercp:foot'); ?>
	</body>
</html>
