<div class="form-group <?=$group->hasError('name') ? 'has-error' : ''?>">
	<label for="name" class="control-label col-md-3"><?=t('name')?></label>
	<div class="col-md-9">
		<input type="text" name="name" id="name" class="form-control" value="<?=e($group['name'])?>">
		<?php if ($group->hasError('name')) : ?>
		<div class="help-block"><?=$group->getError('name')[0]?></div>
		<?php endif ?>
	</div>
</div>
<div class="form-group">
	<label for="is_admin" class="control-label col-md-3"><?=t('is_admin')?></label>
	<div class="col-md-9">
		<?=Form::checkbox('is_admin', 1, ['checked' => $group['is_admin']])?>
	</div>
</div>
