<div class="form-group">
    <label for="name" class="control-label col-md-3"><?=t('name')?></label>
	<div class="col-md-9">
		<?=Form::text('name', ['value' => $group['name'], 'class' => 'form-control'])?>
	</div>
</div>
<div class="form-group">
    <label for="is_admin" class="control-label col-md-3"><?=t('is_admin')?></label>
	<div class="col-md-9">
		<?=Form::checkbox('is_admin', 1, ['checked' => $group['is_admin']])?>
	</div>
</div>
