<div class="admin-statuses container">
	<h1 class="page-header"><?=$t('edit_group')?></h1>

	<form action="<?=Request::basePath($route('edit_admin_group', ['id' => $group->id]))?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($group)?>
		<?=View::render('admin/groups/_form.phtml', ['group' => $group])?>
		<div class="form-actions">
			<?=Form::submit($t('save'), ['class' => 'btn btn-success'])?>
		</div>
	</form>
</div>
