<div class="admin-statuses container">
	<h1 class="page-header"><?=t('edit_group')?></h1>

	<form action="<?=routeUrl('admin_save_group')?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($group)?>
		<?=View::render('admin/groups/_form.phtml', ['group' => $group])?>
		<div class="form-actions">
			<button type="submit" class="btn btn-success"><?=t('save')?></button>
		</div>
	</form>
</div>
