<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="admin admin-types content container">
	<h1 class="page-header"><?=t('groups')?></h1>

	<div class="page-actions">
		<a href="<?=routeUrl('admin_new_group')?>" class="btn btn-success" data-remote-modal="#new-group-modal">
			<span class="fa fa-plus"></span> <?=t('new_group')?>
		</a>
	</div>

	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th><?=t('name')?></th>
				<th><?=t('is_admin')?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($groups as $group) : ?>
			<tr>
				<td>
					<a href="<?=routeUrl('admin_edit_group', ['id' => $group['id']])?>" data-remote-modal="#edit-group-modal">
						<?=$group['name']?>
					</a>
				</td>
				<td><?=$group['is_admin'] ? TWBS::fa('check') : TWBS::fa('times')?></td>
				<td class="actions text-right">
					<a href="<?=routeUrl('admin_edit_group', ['id' => $group['id']])?>" class="btn btn-xs btn-warning" data-remote-modal="#edit-group-modal">
						<span class="fa fa-edit"></span> <?=t('edit')?>
					</a>
					<a href="<?=routeUrl('admin_delete_group', ['id' => $group['id']])?>" class="btn btn-xs btn-danger" data-method="delete" data-confirm="<?=t('confirm.delete')?>">
						<span class="fa fa-times"></span> <?=t('delete')?>
					</a>
				</td>
			</tr>
		<?php endforeach ?>
		</tbody>
	</table>
</div>
<?php $this->endSection(); ?>
