<div class="admin types container">
	<h1 class="page-header"><?=$t('groups')?></h1>

	<div class="page-actions">
		<?=HTML::link(TWBS::fa('plus', $t('new_group')), $route('new_admin_group'), [
			'class' => 'btn btn-success',
			'data-overlay' => true
		])?>
	</div>

	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th><?=$t('name')?></th>
				<th><?=$t('is_admin')?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($groups as $group): ?>
			<tr>
				<td><?=HTML::link($group->name, $route('edit_admin_group', ['id' => $group->id]))?></td>
				<td><?=$group->is_admin ? TWBS::fa('check') : TWBS::fa('times')?></td>
				<td class="actions">
					<?=HTML::link(TWBS::fa('edit', $t('edit')), $route('edit_admin_group', ['id' => $group->id]), [
						'class' => 'btn btn-xs btn-warning',
						'data-overlay' => true
					])?>
					<?=HTML::link(TWBS::fa('times', $t('delete')), $route('delete_admin_group', ['id' => $group->id]), [
						'class' => 'btn btn-xs btn-danger',
						'data-confirm' => $t('confirm.delete')
					])?>
				</td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>
