<div class="admin groups container">
	<h1 class="page-header"><?=t('new_group')?></h1>

	<form action="<?=routeUrl('admin_create_group')?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($group)?>
		<?=View::render('admin/groups/_form.phtml', ['group' => $group])?>
		<div class="form-actions">
			<button type="submit" class="btn btn-success"><?=t('create')?></button>
		</div>
	</form>
</div>
