<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="admin admin-groups-new container">
	<h1 class="page-header"><?=t('new_group')?></h1>

	<form action="<?=routeUrl('admin_create_group')?>" method="post" class="form-horizontal">
		<?=View::render('admin/groups/_form.phtml', ['group' => $group])?>
		<div class="form-actions text-center">
			<button type="submit" class="btn btn-success"><?=t('create')?></button>
		</div>
	</form>
</div>
<?php $this->endSection(); ?>
