<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'new-group-modal');
$this->startSection('modal-size', 'modal-md');
$this->startSection('modal-title', t('new_group'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('admin_create_group')?>" method="post" class="form-horizontal">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('admin/groups/_form.phtml', ['group' => $group])?>
<?php $this->endSection(); ?>
