<div class="admin groups container">
	<h1 class="page-header"><?=$t('new_group')?></h1>

	<form action="<?=Request::basePath($route('new_admin_group'))?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($group)?>
		<?=View::render('admin/groups/_form.phtml', ['group' => $group])?>
		<div class="form-actions">
			<?=Form::submit($t('create'), ['class' => 'btn btn-success'])?>
		</div>
	</form>
</div>
