<div class="project-settings components container">
	<h1 class="page-header"><?=$t('components')?></h1>

	<div class="page-actions">
		<?=HTML::link(TWBS::fa('plus', $t('new_component')), $route('new_project_settings_component'), [
			'class' => 'btn btn-success',
			'data-overlay' => true
		])?>
	</div>

	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th><?=$t('name')?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($components as $component): ?>
			<tr>
				<td><?=HTML::link($component->name, $route('edit_project_settings_component', ['id' => $component->id]))?></td>
				<td class="actions">
					<?=HTML::link(TWBS::fa('edit', $t('edit')), $route('edit_project_settings_component', ['id' => $component->id]), [
						'class' => 'btn btn-xs btn-warning',
						'data-overlay' => true
					])?>
					<?=HTML::link(TWBS::fa('times', $t('delete')), $route('delete_project_settings_component', ['id' => $component->id]), [
						'class' => 'btn btn-xs btn-danger',
						'data-confirm' => $t('confirm.delete')
					])?>
				</td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>
