<?php extendView('layouts/default.phtml'); ?>

<div class="content">
	<h2 class="page-title"><?= l('project_settings') ?></h2>
</div>
<?= view('project_settings/_nav') ?>
<div class="content">
	<form action="<?= Request::requestUri() ?>" method="post">
		<?= show_errors($proj->errors) ?>
		<div class="panel">
			<div class="panel-content">
				<?= view('project_settings/options/_form', array('proj' => $proj)) ?>
			</div>
			<div class="panel-footer">
				<button type="submit" class="btn-primary">
					<?= l('save') ?>
				</button>
			</div>
		</div>
	</form>
</div>
