<div class="register container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1 class="page-header"><?=t("register")?></h1>

			<form action="<?=routeUrl('user_create')?>" method="post" class="form-horizontal">
				<div class="form-group">
					<label for="name" class="col-md-3 control-label"><?=t('name')?></label>
					<div class="col-md-9">
						<?=Form::text('name', ['value' => $user->name, 'class' => "form-control"])?>
					</div>
				</div>

				<div class="form-group <?=$user->hasError('username') ? 'has-error' : ''?>">
					<label for="username" class="col-md-3 control-label"><?=t('username')?></label>
					<div class="col-md-9">
						<?=Form::text('username', ['value' => $user->username, 'class' => "form-control"])?>
						<?php if ($user->hasError('username')) : ?>
							<span class="help-block"><?=$user->getError('username')[0]?></span>
						<?php endif ?>
					</div>
				</div>

				<div class="form-group <?=$user->hasError('email') ? 'has-error' : ''?>">
					<label for="email" class="col-md-3 control-label"><?=t('email')?></label>
					<div class="col-md-9">
						<?=Form::text('email', ['value' => $user->email, 'class' => "form-control"])?>
						<?php if ($user->hasError('email')) : ?>
							<span class="help-block"><?=$user->getError('email')[0]?></span>
						<?php endif ?>
					</div>
				</div>

				<div class="form-group <?=$user->hasError('password') ? 'has-error' : ''?>">
					<label for="password" class="col-md-3 control-label"><?=t('password')?></label>
					<div class="col-md-9">
						<?=Form::password('password', ['class' => "form-control"])?>
					</div>
				</div>

				<div class="form-group <?=$user->hasError('password') ? 'has-error' : ''?>">
					<div class="col-md-9 col-md-offset-3">
						<?=Form::password('password_confirmation', ['class' => "form-control", 'placeholder' => t("confirm_password")])?>
						<?php if ($user->hasError('password')) : ?>
							<span class="help-block"><?=$user->getError('password')[0]?></span>
						<?php endif ?>
					</div>
				</div>

				<div class="form-actions">
					<button type="submit" class="btn btn-success"><?=t('create_account')?></button>
				</div>
			</form>
		</div>
	</div>
</div>
