name: Build Tag

on:
  push:
    tags:
      - v*.**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup required tools
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.x

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: "8.3"

      # Node stuff
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install node dependencies
        run: pnpm i

      - name: Build assets
        run: pnpm run build

      - name: Install PHP dependencies
        run: composer install

      # Cleanup crap
      - name: Remove dev files
        run: |
          rm -rf .github
          rm -rf .vscode
          rm -rf .git
          rm -rf dev
          rm -rf node_modules
          rm -rf src/assets
          rm -rf vendor/avalon/framework/.git
          rm ./*.js
          rm ./*.ts
          rm ./*.yaml
          rm ./*.yml
          rm ./.eslintrc.cjs
          rm .gitignore
          rm ./.prettierrc.json
          rm ./docker-compose.yml
          rm ./env.d.ts
          rm ./package.json
          rm ./package-lock.json
          rm ./pnpm-lock.yaml
          rm ./postcss.config.js
          rm ./tailwind.config.js
          rm ./tsconfig.*
          rm ./vite.config.ts

      # Upload build artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: traq-${{ github.ref_name }}
          path: ./
