<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Traq Installation - <?=$stepTitle?></title>
		<link rel="stylesheet" type="text/css" href="<?=rtrim(dirname(Request::basePath()), '/')?>/assets/css/traq.css">
		<script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
	</head>
	<body>
		<header id="header" class="navbar navbar-default navbar-static-top">
			<div class="container">
				<div class="navbar-header">
					<span class="navbar-brand">Traq Installation</span>
				</div>
				<div class="navbar-collapse collapse">
					<p class="navbar-text">
						<?=$stepTitle?>
					</p>
				</div>
			</div>
		</header>
		<?=$content?>
		<footer id="footer">
			<div class="container">
				<span class="text-muted">Traq &copy; 2009-2015 Jack P.</span>
			</div>
		</footer>
	</body>
</html>
