<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Traq Installation - <?=$stepTitle?></title>
		<link rel="stylesheet" type="text/css" href="<?=dirname(Request::basePath())?>/assets/css/traq.css">
	</head>
	<body>
		<header id="header" class="navbar navbar-default navbar-static-top">
			<div class="container">
				<div class="navbar-header">
					<span class="navbar-brand">Traq Installation</span>
				</div>
				<div class="navbar-collapse collapse">
					<p class="navbar-text">
						<?=$stepTitle?>
					</p>
				</div>
			</div>
		</header>
		<?=$content?>
	</body>
</html>
