<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="admin admin-statuses-edit content container">
	<h1 class="page-header"><?=t('edit_type')?></h1>

	<form action="<?=routeUrl('admin_save_type')?>" method="post" class="form-horizontal">
		<input type="hidden" name="_method" value="put">
		<?=View::render('admin/types/_form.phtml', ['type' => $type])?>
		<div class="form-actions text-center">
			<button type="submit" class="btn btn-success"><?=t('save')?></button>
		</div>
	</form>
</div>
<?php $this->endSection(); ?>
