<?php $this->extend('layouts/modal.phtml'); ?>

<?php
$this->startSection('modal-id', 'new-type-modal');
$this->startSection('modal-size', 'modal-lg');
$this->startSection('modal-title', t('edit_user'));
?>

<?php $this->startSection('modal-form-start'); ?>
<form action="<?=routeUrl('admin_create_type')?>" method="post" class="form-horizontal">
<?php $this->endSection(); ?>

<?php $this->startSection('modal-content'); ?>
	<?=View::render('admin/types/_form.phtml', ['type' => $type])?>
<?php $this->endSection(); ?>
