<nav id="usercp-nav" class="container">
	<ul class="nav nav-tabs" role="tablist">
		<li<?=Request::matches('/usercp$') ? ' class="active"' :''?>>
			<a href="<?=routeUrl('usercp')?>"><?=t('information')?></a>
		</li>
		<li<?=Request::matches('/usercp/password$') ? ' class="active"' :''?>>
			<a href="<?=routeUrl('usercp_password')?>"><?=t('password')?></a>
		</li>
		<li<?=Request::matches('/usercp/subscriptions$') ? ' class="active"' :''?>>
		<a href="<?=routeUrl('usercp_subscriptions')?>"><?=t('subscriptions')?></a>
		</li>
		<?=Hook::run('template:usercp/_nav')?>
	</ul>
</nav>
