<div class="usercp container">
	<form action="<?=Request::basePath($route('usercp'))?>" method="post" class="form-horizontal">

		<?=Errors::messagesFor($user)?>

		<div class="row">
			<div class="col-md-6">
				<fieldset>
					<legend><?=$t("information")?></legend>

					<div class="form-group">
						<?=Form::label($t("name"), "name", ['class' => "control-label col-md-4"])?>
						<div class="col-md-8">
							<?=Form::text("name", ['class' => "form-control", 'value' => $user->name])?>
						</div>
					</div>
					<div class="form-group">
						<?=Form::label($t("email"), "email", ['class' => "control-label col-md-4"])?>
						<div class="col-md-8">
							<?=Form::text("email", ['class' => "form-control", 'value' => $user->email])?>
						</div>
					</div>
					<div class="form-group">
						<?=Form::label($t("api_key"), "api_key", ['class' => "control-label col-md-4"])?>
						<div class="col-md-8">
							<?php if ($user->api_key != null): ?>
								<?=Form::text('api_key', [
									'value' => $user->api_key,
									'readonly' => true,
									'class' => "form-control"
								])?>
							<?php endif; ?>
							<?=HTML::link($t($user->api_key ? 'renew' : 'create'), 'usercp/create_api_key', [
								'class' => 'btn btn-default btn-sm'
							])?>
						</div>
					</div>
					<div class="form-group">
						<?=Form::label($t("current_password"), "current_password", ['class' => "control-label col-md-4"])?>
						<div class="col-md-8">
							<?=Form::password("current_password", ['class' => "form-control"])?>
						</div>
					</div>
				</fieldset>
			</div>

			<div class="col-md-6">
				<legend><?=$t("options")?></legend>

				<div class="form-group">
					<?=Form::label($t("language"), "locale", ['class' => "control-label col-md-4"])?>
					<div class="col-md-8">

					</div>
				</div>
			</div>
		</div>
		<div class="row text-center">
			<?=Form::submit($t('save'), ['class' => 'btn btn-success'])?>
		</div>
	</form>
</div>
