<div class="usercp container">
	<div class="row">
		<form action="<?=Request::basePath($route('usercp'))?>" method="post" class="form-horizontal">
			<div class="col-md-6">
				<fieldset>
					<legend><?=$t("information")?></legend>

					<div class="form-group">
						<?=Form::label($t("name"), "user[name]", ['class' => "control-label col-md-3"])?>
						<div class="col-md-9">
							<?=Form::text("user[name]", ['class' => "form-control", 'value' => $user->name])?>
						</div>
					</div>
					<div class="form-group">
						<?=Form::label($t("email"), "user[email]", ['class' => "control-label col-md-3"])?>
						<div class="col-md-9">
							<?=Form::text("user[email]", ['class' => "form-control", 'value' => $user->email])?>
						</div>
					</div>
					<div class="form-group">
						<?=Form::label($t("api_key"), "user[api_key]", ['class' => "control-label col-md-3"])?>
						<div class="col-md-9">

						</div>
					</div>
					<div class="form-group">
						<?=Form::label($t("current_password"), "user[current_password]", ['class' => "control-label col-md-3"])?>
						<div class="col-md-9">
							<?=Form::text("user[current_password]", ['class' => "form-control"])?>
						</div>
					</div>
				</fieldset>
			</div>

			<div class="col-md-6">
				<legend><?=$t("options")?></legend>
			</div>
		</form>
	</div>
</div>