<div class="usercp container">
	<form action="<?=Request::basePath($route('usercp_password'))?>" method="post" class="form-horizontal">
		<?=Errors::messagesFor($user)?>
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="form-group">
					<?=Form::label($t("current_password"), "current_password", ['class' => "control-label col-md-4"])?>
					<div class="col-md-8">
						<?=Form::password("current_password", ['class' => "form-control"])?>
					</div>
				</div>

				<div class="form-group">
					<?=Form::label($t("password"), "password", ['class' => "control-label col-md-4"])?>
					<div class="col-md-8">
						<?=Form::password("password", ['class' => "form-control"])?>
					</div>
				</div>

				<div class="form-group">
					<?=Form::label($t("confirm_password"), "password_confirmation", ['class' => "control-label col-md-4"])?>
					<div class="col-md-8">
						<?=Form::password("password_confirmation", ['class' => "form-control"])?>
					</div>
				</div>
			</div>
		</div>

		<div class="row text-center">
			<?=Form::submit($t('save'), ['class' => "btn btn-success"])?>
		</div>
	</form>
</div>
